const vocabularyData = [
    { kanji: "先輩", kana: "せんぱい", romaji: "senpai", meaning: "kakak tingkat; senior", type: "noun", level: "N5" },
    { kanji: "後輩", kana: "こうはい", romaji: "kouhai", meaning: "adik tingkat; junior", type: "noun", level: "N5" },
    { kanji: "知り合い", kana: "しりあい", romaji: "shiriai", meaning: "kenalan", type: "noun", level: "N5" },
    { kanji: "久しぶり", kana: "ひさしぶり", romaji: "hisashiburi", meaning: "sudah lama tidak berjumpa", type: "expression", level: "N5" },
    { kanji: "元気", kana: "げんき", romaji: "genki", meaning: "sehat", type: "adj-na", level: "N5" },
    { kanji: "おかげさまで", kana: "おかげさまで", romaji: "okagesamade", meaning: "Terima kasih.", type: "expression", level: "N5" },
    { kanji: "半年", kana: "はんとし", romaji: "hantoshi", meaning: "setengah tahun", type: "noun", level: "N5" },
    { kanji: "1年", kana: "いちねん", romaji: "ichinen", meaning: "satu tahun", type: "noun", level: "N5" },
    { kanji: "先月", kana: "せんげつ", romaji: "sengetsu", meaning: "bulan lalu", type: "noun", level: "N5" },
    { kanji: "去年", kana: "きょねん", romaji: "kyonen", meaning: "tahun lalu", type: "noun", level: "N5" },
    { kanji: "生活", kana: "せいかつ", romaji: "seikatsu", meaning: "kehidupan", type: "noun", level: "N5" },
    { kanji: "もう", kana: "もう", romaji: "mou", meaning: "sudah", type: "adverb", level: "N5" },
    { kanji: "慣れる", kana: "なれる", romaji: "nareru", meaning: "terbiasa; betah", type: "verb-ru", level: "N5" },
    { kanji: "ちょうど", kana: "ちょうど", romaji: "choudo", meaning: "pas; tepat", type: "adverb", level: "N5" },
    { kanji: "なんとか", kana: "なんとか", romaji: "nantoka", meaning: "lumayan", type: "adverb", level: "N5" },
    { kanji: "まだ", kana: "まだ", romaji: "mada", meaning: "belum", type: "adverb", level: "N5" },
    { kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "pekerjaan", type: "noun", level: "N5" },
    { kanji: "働く", kana: "はたらく", romaji: "hataraku", meaning: "bekerja", type: "verb-godan", level: "N5" },
    { kanji: "ホテル", kana: "ホテル", romaji: "hoteru", meaning: "hotel", type: "noun", level: "N5" },
    { kanji: "工場", kana: "こうじょう", romaji: "koujou", meaning: "pabrik", type: "noun", level: "N5" },
    { kanji: "介護", kana: "かいご", romaji: "kaigo", meaning: "pengasuhan; perawatan (lansia)", type: "noun", level: "N5" },
    { kanji: "建設", kana: "けんせつ", romaji: "kensetsu", meaning: "konstruksi", type: "noun", level: "N5" },
    { kanji: "野菜", kana: "やさい", romaji: "yasai", meaning: "sayur", type: "noun", level: "N5" },
    { kanji: "作る", kana: "つくる", romaji: "tsukuru", meaning: "menanam (sayur); membuat", type: "verb-godan", level: "N5" },
    { kanji: "日本語学校", kana: "にほんごがっこう", romaji: "nihongo gakkou", meaning: "Sekolah Bahasa Jepang", type: "noun", level: "N5" },
    { kanji: "勉強する", kana: "べんきょうする", romaji: "benkyou suru", meaning: "belajar", type: "verb-irregular", level: "N5" },
    { kanji: "専門学校", kana: "せんもんがっこう", romaji: "senmon gakkou", meaning: "sekolah kejuruan", type: "noun", level: "N5" },
    { kanji: "通う", kana: "かよう", romaji: "kayou", meaning: "pergi; menjalani pendidikan (sekolah)", type: "verb-godan", level: "N5" },
    { kanji: "主婦", kana: "しゅふ", romaji: "shufu", meaning: "ibu rumah tangga", type: "noun", level: "N5" },
    { kanji: "主夫", kana: "しゅふ", romaji: "shufu", meaning: "bapak rumah tangga", type: "noun", level: "N5" },
    { kanji: "忙しい", kana: "いそがしい", romaji: "isogashii", meaning: "sibuk", type: "adj-i", level: "N5" },
    { kanji: "大変", kana: "たいへん", romaji: "taihen", meaning: "sulit; berat", type: "adj-na", level: "N5" },
    { kanji: "疲れる", kana: "つかれる", romaji: "tsukareru", meaning: "capek; lelah", type: "verb-ru", level: "N5" },
    { kanji: "まあまあ", kana: "まあまあ", romaji: "maamaa", meaning: "lumayan", type: "adj-na", level: "N5" },
    { kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "menyenangkan", type: "adj-i", level: "N5" },
    { kanji: "みんな", kana: "みんな", romaji: "minna", meaning: "semua orang", type: "noun", level: "N5" },
    { kanji: "親切", kana: "しんせつ", romaji: "shinsetsu", meaning: "ramah; baik hati", type: "adj-na", level: "N5" },
    { kanji: "勉強になる", kana: "べんきょうになる", romaji: "benkyou ni naru", meaning: "belajar banyak hal", type: "expression", level: "N5" },
    { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "setiap hari", type: "noun", level: "N5" },
    { kanji: "学生", kana: "がくせい", romaji: "gakusei", meaning: "siswa", type: "noun", level: "N5" },
    { kanji: "プログラミング", kana: "プログラミング", romaji: "puroguramingu", meaning: "pemrograman", type: "noun", level: "N5" },
    { kanji: "趣味", kana: "しゅみ", romaji: "shumi", meaning: "hobi", type: "noun", level: "N5" },
    { kanji: "音楽", kana: "おんがく", romaji: "ongaku", meaning: "musik", type: "noun", level: "N5" },
    { kanji: "聞く", kana: "きく", romaji: "kiku", meaning: "mendengar", type: "verb-godan", level: "N5" },
    { kanji: "本", kana: "ほん", romaji: "hon", meaning: "buku", type: "noun", level: "N5" },
    { kanji: "読む", kana: "よむ", romaji: "yomu", meaning: "membaca", type: "verb-godan", level: "N5" },
    { kanji: "写真", kana: "しゃしん", romaji: "shashin", meaning: "foto", type: "noun", level: "N5" },
    { kanji: "撮る", kana: "とる", romaji: "toru", meaning: "mengambil (foto; video)", type: "verb-godan", level: "N5" },
    { kanji: "ピアノ", kana: "ピアノ", romaji: "piano", meaning: "piano", type: "noun", level: "N5" },
    { kanji: "ギター", kana: "ギター", romaji: "gitaa", meaning: "gitar", type: "noun", level: "N5" },
    { kanji: "弾く", kana: "ひく", romaji: "hiku", meaning: "bermain (alat musik)", type: "verb-godan", level: "N5" },
    { kanji: "おしゃべり", kana: "おしゃべり", romaji: "oshaberi", meaning: "bincang-bincang; obrolan", type: "noun", level: "N5" },
    { kanji: "料理", kana: "りょうり", romaji: "ryouri", meaning: "masak; masakan", type: "noun", level: "N5" },
    { kanji: "旅行", kana: "りょこう", romaji: "ryokou", meaning: "perjalanan", type: "noun", level: "N5" },
    { kanji: "テニス", kana: "テニス", romaji: "tenisu", meaning: "tenis", type: "noun", level: "N5" },
    { kanji: "いろいろ", kana: "いろいろ", romaji: "iroiro", meaning: "bermacam-macam", type: "adj-na", level: "N5" },
    { kanji: "人", kana: "ひと", romaji: "hito", meaning: "orang", type: "noun", level: "N5" },
    { kanji: "話す", kana: "はなす", romaji: "hanasu", meaning: "berbicara", type: "verb-godan", level: "N5" },
    { kanji: "特にない", kana: "とくにない", romaji: "tokuni nai", meaning: "tidak ada yang khusus", type: "expression", level: "N5" },
    { kanji: "野球", kana: "やきゅう", romaji: "yakyuu", meaning: "bisbol; kasti", type: "noun", level: "N5" },
    { kanji: "バドミントン", kana: "バドミントン", romaji: "badominton", meaning: "bulu tangkis", type: "noun", level: "N5" },
    { kanji: "アニメ", kana: "アニメ", romaji: "anime", meaning: "anime (animasi)", type: "noun", level: "N5" },
    { kanji: "市", kana: "し", romaji: "shi", meaning: "kota", type: "noun", level: "N5" },
    { kanji: "体育館", kana: "たいいくかん", romaji: "taiikukan", meaning: "gedung olah raga", type: "noun", level: "N5" },
    { kanji: "毎週", kana: "まいしゅう", romaji: "maishuu", meaning: "setiap minggu", type: "noun", level: "N5" },
    { kanji: "夕方", kana: "ゆうがた", romaji: "yuugata", meaning: "sore hari", type: "noun", level: "N5" },
    { kanji: "そのあと", kana: "そのあと", romaji: "sono ato", meaning: "setelah itu; kemudian", type: "expression", level: "N5" },
    { kanji: "本当に", kana: "ほんとうに", romaji: "hontouni", meaning: "sangat", type: "adverb", level: "N5" },
    { kanji: "出かける", kana: "でかける", romaji: "dekakeru", meaning: "pergi", type: "verb-ru", level: "N5" },
    { kanji: "特に", kana: "とくに", romaji: "tokuni", meaning: "terutama", type: "adverb", level: "N5" },
    { kanji: "キャッチボール", kana: "キャッチボール", romaji: "kyacchi booru", meaning: "permainan lempar - tangkap bola bisbol", type: "noun", level: "N5" },
    { kanji: "お子さん", kana: "おこさん", romaji: "okosan", meaning: "anak (orang lain)", type: "noun", level: "N5" },
    { kanji: "娘", kana: "むすめ", romaji: "musume", meaning: "anak perempuan", type: "noun", level: "N5" },
    { kanji: "犬", kana: "いぬ", romaji: "inu", meaning: "anjing", type: "noun", level: "N5" },
    { kanji: "キャンプ", kana: "キャンプ", romaji: "kyanpu", meaning: "berkemah", type: "noun", level: "N5" },
    { kanji: "釣り", kana: "つり", romaji: "tsuri", meaning: "memancing", type: "noun", level: "N5" },
    { kanji: "海", kana: "うみ", romaji: "umi", meaning: "laut", type: "noun", level: "N5" },
    { kanji: "山", kana: "やま", romaji: "yama", meaning: "gunung", type: "noun", level: "N5" },
    { kanji: "語", kana: "ご", romaji: "go", meaning: "bahasa ~", type: "suffix", level: "N5" },
    { kanji: "ことば", kana: "ことば", romaji: "kotoba", meaning: "bahasa", type: "noun", level: "N5" },
    { kanji: "アウトドア", kana: "アウトドア", romaji: "autodoa", meaning: "outdoor; aktivitas luar ruangan", type: "noun", level: "N5" },
    { kanji: "サイクリング", kana: "サイクリング", romaji: "saikuringu", meaning: "bersepeda", type: "noun", level: "N5" },
    { kanji: "教える", kana: "おしえる", romaji: "oshieru", meaning: "memberi tahu", type: "verb-ru", level: "N5" },
    { kanji: "人", kana: "じん", romaji: "jin", meaning: "orang ~", type: "suffix", level: "N5" },
    { kanji: "習う", kana: "ならう", romaji: "narau", meaning: "mempelajari", type: "verb-godan", level: "N5" },
    { kanji: "英語", kana: "えいご", romaji: "eigo", meaning: "bahasa Inggris", type: "noun", level: "N5" },
    { kanji: "できる", kana: "できる", romaji: "dekiru", meaning: "sesuatu yang bisa / dapat dilakukan", type: "verb-irregular", level: "N5" },
    { kanji: "いけばな", kana: "いけばな", romaji: "ikebana", meaning: "Ikebana (seni merangkai bunga)", type: "noun", level: "N5" },
    { kanji: "フィリピン語", kana: "フィリピンご", romaji: "firipin go", meaning: "bahasa Filipina", type: "noun", level: "N5" },
    { kanji: "スペイン語", kana: "スペインご", romaji: "supein go", meaning: "bahasa Spanyol", type: "noun", level: "N5" },
    { kanji: "季節", kana: "きせつ", romaji: "kisetsu", meaning: "musim", type: "noun", level: "N5" },
    { kanji: "暑い", kana: "あつい", romaji: "atsui", meaning: "panas", type: "adj-i", level: "N5" },
    { kanji: "涼しい", kana: "すずしい", romaji: "suzushii", meaning: "sejuk", type: "adj-i", level: "N5" },
    { kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "dingin", type: "adj-i", level: "N5" },
    { kanji: "暖かい", kana: "あたたかい", romaji: "atatakai", meaning: "hangat", type: "adj-i", level: "N5" },
    { kanji: "じめじめする", kana: "じめじめする", romaji: "jimejime suru", meaning: "panas dan lembab", type: "verb-irregular", level: "N5" },
    { kanji: "蒸し暑い", kana: "むしあつい", romaji: "mushiatsui", meaning: "panas dan pengap / gerah", type: "adj-i", level: "N5" },
    { kanji: "雨", kana: "あめ", romaji: "ame", meaning: "hujan", type: "noun", level: "N5" },
    { kanji: "降る", kana: "ふる", romaji: "furu", meaning: "turun (hujan, salju, dll.)", type: "verb-godan", level: "N5" },
    { kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "salju", type: "noun", level: "N5" },
    { kanji: "桜", kana: "さくら", romaji: "sakura", meaning: "bunga sakura", type: "noun", level: "N5" },
    { kanji: "花", kana: "はな", romaji: "hana", meaning: "bunga", type: "noun", level: "N5" },
    { kanji: "咲く", kana: "さく", romaji: "saku", meaning: "mekar", type: "verb-godan", level: "N5" },
    { kanji: "もみじ", kana: "もみじ", romaji: "momiji", meaning: "daun yang berubah warna pada musim gugur", type: "noun", level: "N5" },
    { kanji: "きれい", kana: "きれい", romaji: "kirei", meaning: "indah; cantik", type: "adj-na", level: "N5" },
    { kanji: "セミ", kana: "セミ", romaji: "semi", meaning: "tonggeret", type: "noun", level: "N5" },
    { kanji: "鳴く", kana: "なく", romaji: "naku", meaning: "bersuara (hewan; serangga)", type: "verb-godan", level: "N5" },
    { kanji: "春", kana: "はる", romaji: "haru", meaning: "musim semi", type: "noun", level: "N5" },
    { kanji: "梅雨", kana: "つゆ", romaji: "tsuyu", meaning: "musim hujan pada akhir Mei s.d. pertengahan Juli sebelum memasuki musim panas di Jepang", type: "noun", level: "N5" },
    { kanji: "夏", kana: "なつ", romaji: "natsu", meaning: "musim panas", type: "noun", level: "N5" },
    { kanji: "秋", kana: "あき", romaji: "aki", meaning: "musim gugur", type: "noun", level: "N5" },
    { kanji: "冬", kana: "ふゆ", romaji: "fuyu", meaning: "musim dingin", type: "noun", level: "N5" },
    { kanji: "たくさん", kana: "たくさん", romaji: "takusan", meaning: "banyak", type: "adverb", level: "N5" },
    { kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "sekolah", type: "noun", level: "N5" },
    { kanji: "なる", kana: "なる", romaji: "naru", meaning: "menjadi (cth: menjadi hari libur)", type: "verb-godan", level: "N5" },
    { kanji: "一年中", kana: "いちねんじゅう", romaji: "ichinenjuu", meaning: "sepanjang tahun", type: "noun", level: "N5" },
    { kanji: "長い", kana: "ながい", romaji: "nagai", meaning: "panjang", type: "adj-i", level: "N5" },
    { kanji: "ずっと", kana: "ずっと", romaji: "zutto", meaning: "sepanjang waktu; terus menerus", type: "adverb", level: "N5" },
    { kanji: "雨季", kana: "うき", romaji: "uki", meaning: "musim hujan", type: "noun", level: "N5" },
    { kanji: "乾季", kana: "かんき", romaji: "kanki", meaning: "musim kemarau", type: "noun", level: "N5" },
    { kanji: "四季", kana: "しき", romaji: "shiki", meaning: "empat musim", type: "noun", level: "N5" },
    { kanji: "同じ", kana: "おなじ", romaji: "onaji", meaning: "sama", type: "adj-na", level: "N5" },
    { kanji: "短い", kana: "みじかい", romaji: "mijikai", meaning: "pendek", type: "adj-i", level: "N5" },
    { kanji: "果物", kana: "くだもの", romaji: "kudamono", meaning: "buah-buahan", type: "noun", level: "N5" },
    { kanji: "おいしい", kana: "おいしい", romaji: "oishii", meaning: "enak; lezat", type: "adj-i", level: "N5" },
    { kanji: "景色", kana: "けしき", romaji: "keshiki", meaning: "pemandangan", type: "noun", level: "N5" },
    { kanji: "山", kana: "やま", romaji: "yama", meaning: "gunung", type: "noun", level: "N5" },
    { kanji: "遊ぶ", kana: "あそぶ", romaji: "asobu", meaning: "bermain", type: "verb-godan", level: "N5" },
    { kanji: "好き", kana: "すき", romaji: "suki", meaning: "favorit", type: "adj-na", level: "N5" },
    { kanji: "苦手", kana: "にがて", romaji: "nigate", meaning: "tidak suka", type: "adj-na", level: "N5" },
    { kanji: "一番", kana: "いちばん", romaji: "ichiban", meaning: "paling", type: "adverb", level: "N5" },
    { kanji: "どうして", kana: "どうして", romaji: "doushite", meaning: "mengapa", type: "adverb", level: "N5" },
    { kanji: "どの", kana: "どの", romaji: "dono", meaning: "yang mana~ (lebih dari tiga)", type: "noun", level: "N5" },
    { kanji: "ぶどう", kana: "ぶどう", romaji: "budou", meaning: "anggur", type: "noun", level: "N5" },
    { kanji: "梨", kana: "なし", romaji: "nashi", meaning: "pir", type: "noun", level: "N5" },
    { kanji: "昨日はすごい雨でしたね", kana: "きのうはすごいあめでしたね", romaji: "kinou wa sugoi ame deshita ne", meaning: "Kemarin hujannya deras sekali ya", type: "expression", level: "N5" },
    { kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "cuaca", type: "noun", level: "N5" },
    { kanji: "晴れ", kana: "はれ", romaji: "hare", meaning: "cerah; baik (cuaca)", type: "noun", level: "N5" },
    { kanji: "晴れる", kana: "はれる", romaji: "hareru", meaning: "cerah; menjadi cerah", type: "verb-ru", level: "N5" },
    { kanji: "いい天気", kana: "いいてんき", romaji: "ii tenki", meaning: "cuacanya cerah; cuacanya baik", type: "expression", level: "N5" },
    { kanji: "曇り", kana: "くもり", romaji: "kumori", meaning: "berawan", type: "noun", level: "N5" },
    { kanji: "曇る", kana: "くもる", romaji: "kumoru", meaning: "berawan; mendung", type: "verb-godan", level: "N5" },
    { kanji: "雨", kana: "あめ", romaji: "ame", meaning: "hujan", type: "noun", level: "N5" },
    { kanji: "降る", kana: "ふる", romaji: "furu", meaning: "turun (hujan; salju dll.)", type: "verb-godan", level: "N5" },
    { kanji: "風", kana: "かぜ", romaji: "kaze", meaning: "angin", type: "noun", level: "N5" },
    { kanji: "吹く", kana: "ふく", romaji: "fuku", meaning: "(angin) bertiup; meniup", type: "verb-godan", level: "N5" },
    { kanji: "雷", kana: "かみなり", romaji: "kaminari", meaning: "guntur", type: "noun", level: "N5" },
    { kanji: "鳴る", kana: "なる", romaji: "naru", meaning: "(guntur) bergemuruh", type: "verb-godan", level: "N5" },
    { kanji: "今", kana: "いま", romaji: "ima", meaning: "sekarang", type: "noun", level: "N5" },
    { kanji: "昨日", kana: "きのう", romaji: "kinou", meaning: "kemarin", type: "noun", level: "N5" },
    { kanji: "だいぶ", kana: "だいぶ", romaji: "daibu", meaning: "banyak; cukup", type: "adverb", level: "N5" },
    { kanji: "嫌になる", kana: "いやになる", romaji: "iya ni naru", meaning: "mengganggu; mengesalkan", type: "expression", level: "N5" },
    { kanji: "夕べ", kana: "ゆうべ", romaji: "yuube", meaning: "tadi malam", type: "noun", level: "N5" },
    { kanji: "すごい", kana: "すごい", romaji: "sugoi", meaning: "deras (hujan); hebat", type: "adj-i", level: "N5" },
    { kanji: "やむ", kana: "やむ", romaji: "yamu", meaning: "berhenti", type: "verb-godan", level: "N5" },
    { kanji: "ただ", kana: "ただ", romaji: "tada", meaning: "tapi", type: "conjunction", level: "N5" },
    { kanji: "強い", kana: "つよい", romaji: "tsuyoi", meaning: "kuat", type: "adj-i", level: "N5" },
    { kanji: "服装", kana: "ふくそう", romaji: "fukusou", meaning: "pakaian", type: "noun", level: "N5" },
    { kanji: "お出かけください", kana: "おでかけください", romaji: "odekake kudasai", meaning: "silakan bepergian", type: "expression", level: "N5" },
    { kanji: "台風", kana: "たいふう", romaji: "taifuu", meaning: "topan", type: "noun", level: "N5" },
    { kanji: "外", kana: "そと", romaji: "soto", meaning: "di luar", type: "noun", level: "N5" },
    { kanji: "死ぬ", kana: "しぬ", romaji: "shinu", meaning: "mati", type: "verb-godan", level: "N5" },
    { kanji: "気温", kana: "きおん", romaji: "kion", meaning: "suhu udara", type: "noun", level: "N5" },
    { kanji: "アイス", kana: "アイス", romaji: "aisu", meaning: "es krim", type: "noun", level: "N5" },
    { kanji: "町", kana: "まち", romaji: "machi", meaning: "kota", type: "noun", level: "N5" },
    { kanji: "触る", kana: "さわる", romaji: "sawaru", meaning: "menyentuh", type: "verb-godan", level: "N5" },
    { kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "dingin", type: "adj-i", level: "N5" },
    { kanji: "まっしろ", kana: "まっしろ", romaji: "masshiro", meaning: "putih bersih", type: "adj-na", level: "N5" },
    { kanji: "とっても", kana: "とっても", romaji: "tottemo", meaning: "sangat; banget (bentuk informal dari とても)", type: "adverb", level: "N5" },
    { kanji: "まだ", kana: "まだ", romaji: "mada", meaning: "belum", type: "adverb", level: "N5" },
    { kanji: "遅れる", kana: "おくれる", romaji: "okureru", meaning: "terlambat", type: "verb-ru", level: "N5" },
    { kanji: "とてもにぎやかで便利です", kana: "とてもにぎやかでべんりです", romaji: "totemo nigiyaka de benri desu", meaning: "sangat ramai dan praktis", type: "expression", level: "N5" },
    { kanji: "どんな", kana: "どんな", romaji: "donna", meaning: "bagaimana", type: "adverb", level: "N5" },
    { kanji: "町", kana: "まち", romaji: "machi", meaning: "kota", type: "noun", level: "N5" },
    { kanji: "便利", kana: "べんり", romaji: "benri", meaning: "praktis", type: "adj-na", level: "N5" },
    { kanji: "不便", kana: "ふべん", romaji: "fuben", meaning: "tidak praktis", type: "adj-na", level: "N5" },
    { kanji: "にぎやか", kana: "にぎやか", romaji: "nigiyaka", meaning: "ramai", type: "adj-na", level: "N5" },
    { kanji: "緑", kana: "みどり", romaji: "midori", meaning: "pepohonan; tanaman hijau", type: "noun", level: "N5" },
    { kanji: "多い", kana: "おおい", romaji: "ooi", meaning: "banyak", type: "adj-i", level: "N5" },
    { kanji: "少ない", kana: "すくない", romaji: "sukunai", meaning: "sedikit", type: "adj-i", level: "N5" },
    { kanji: "人", kana: "ひと", romaji: "hito", meaning: "orang", type: "noun", level: "N5" },
    { kanji: "やさしい", kana: "やさしい", romaji: "yasashii", meaning: "ramah", type: "adj-i", level: "N5" },
    { kanji: "親切", kana: "しんせつ", romaji: "shinsetsu", meaning: "baik hati", type: "adj-na", level: "N5" },
    { kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "dingin (sikap); tidak peduli", type: "adj-i", level: "N5" },
    { kanji: "田舎", kana: "いなか", romaji: "inaka", meaning: "desa; pedesaan", type: "noun", level: "N5" },
    { kanji: "都会", kana: "とかい", romaji: "tokai", meaning: "kota", type: "noun", level: "N5" },
    { kanji: "きれい", kana: "きれい", romaji: "kirei", meaning: "indah", type: "adj-na", level: "N5" },
    { kanji: "確かに", kana: "たしかに", romaji: "tashika ni", meaning: "pastinya", type: "adverb", level: "N5" },
    { kanji: "住みやすい", kana: "すみやすい", romaji: "sumiyasui", meaning: "nyaman", type: "adj-i", level: "N5" },
    { kanji: "店", kana: "みせ", romaji: "mise", meaning: "toko / restoran", type: "noun", level: "N5" },
    { kanji: "安い", kana: "やすい", romaji: "yasui", meaning: "murah", type: "adj-i", level: "N5" },
    { kanji: "面白い", kana: "おもしろい", romaji: "omoshiroi", meaning: "menarik", type: "adj-i", level: "N5" },
    { kanji: "遠い", kana: "とおい", romaji: "tooi", meaning: "jauh", type: "adj-i", level: "N5" },
    { kanji: "どこか", kana: "どこか", romaji: "dokoka", meaning: "suatu tempat", type: "noun", level: "N5" },
    { kanji: "ところ", kana: "ところ", romaji: "tokoro", meaning: "tempat", type: "noun", level: "N5" },
    { kanji: "スポーツセンター", kana: "スポーツセンター", romaji: "supootsu sentaa", meaning: "sports center; pusat olahraga", type: "noun", level: "N5" },
    { kanji: "建物", kana: "たてもの", romaji: "tatemono", meaning: "bangunan", type: "noun", level: "N5" },
    { kanji: "ショッピングモール", kana: "ショッピングモール", romaji: "shoppingu mooru", meaning: "pusat perbelanjaan", type: "noun", level: "N5" },
    { kanji: "一度", kana: "いちど", romaji: "ichido", meaning: "sekali; satu kali", type: "noun", level: "N5" },
    { kanji: "行ってみる", kana: "いってみる", romaji: "itte miru", meaning: "mencoba pergi", type: "verb-godan", level: "N5" },
    { kanji: "場所", kana: "ばしょ", romaji: "basho", meaning: "tempat", type: "noun", level: "N5" },
    { kanji: "ぜひ", kana: "ぜひ", romaji: "zehi", meaning: "pastikan; jangan sampai tidak", type: "adverb", level: "N5" },
    { kanji: "おすすめ", kana: "おすすめ", romaji: "osusume", meaning: "direkomendasikan", type: "noun", level: "N5" },
    { kanji: "知っている", kana: "しっている", romaji: "shitte iru", meaning: "mengetahui", type: "verb-irregular", level: "N5" },
    { kanji: "知る", kana: "しる", romaji: "shiru", meaning: "mengetahui", type: "verb-godan", level: "N5" },
    { kanji: "休憩所", kana: "きゅうけいじょ", romaji: "kyuukeijo", meaning: "tempat istirahat", type: "noun", level: "N5" },
    { kanji: "そうね……", kana: "そうね……", romaji: "sou ne......", meaning: "Hmm... (digunakan saat pembicara sedang berpikir)", type: "expression", level: "N5" },
    { kanji: "そうだなあ", kana: "そうだなあ", romaji: "sou da naa", meaning: "Hmm...apa ya.. (digunakan saat pembicara sedang berpikir)", type: "expression", level: "N5" },
    { kanji: "美しい", kana: "うつくしい", romaji: "utsukushii", meaning: "indah", type: "adj-i", level: "N5" },
    { kanji: "砂浜", kana: "すなはま", romaji: "sunahama", meaning: "pantai berpasir", type: "noun", level: "N5" },
    { kanji: "有名", kana: "ゆうめい", romaji: "yuumei", meaning: "terkenal", type: "adj-na", level: "N5" },
    { kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "berenang", type: "verb-godan", level: "N5" },
    { kanji: "丘", kana: "おか", romaji: "oka", meaning: "bukit", type: "noun", level: "N5" },
    { kanji: "見渡す", kana: "みわたす", romaji: "miwatasu", meaning: "memandang/melihat ke sekeliling", type: "verb-godan", level: "N5" },
    { kanji: "夕日", kana: "ゆうひ", romaji: "yuhi", meaning: "matahari terbenam", type: "noun", level: "N5" },
    { kanji: "タウンマップ", kana: "タウンマップ", romaji: "taun mappu", meaning: "peta kota", type: "noun", level: "N5" },
    { kanji: "名物", kana: "めいぶつ", romaji: "meibutsu", meaning: "makanan khas lokal", type: "noun", level: "N5" },
    { kanji: "評判", kana: "ひょうばん", romaji: "hyouban", meaning: "reputasi", type: "noun", level: "N5" },
    { kanji: "〜ha", kana: "〜ヘクタール", romaji: "~ hekutāru", meaning: "〜 ha (hektar, 1 ha = 10,000 m²)", type: "suffix", level: "N5" },
    { kanji: "バーベキュー場", kana: "バーベキューじょう", romaji: "bābekyū jou", meaning: "area barbeku (BBQ)", type: "noun", level: "N5" },
    { kanji: "サイクリングコース", kana: "サイクリングコース", romaji: "saikuringu kōsu", meaning: "jalur sepeda", type: "noun", level: "N5" },
    { kanji: "人気", kana: "にんき", romaji: "ninki", meaning: "populer", type: "noun", level: "N5" },
    { kanji: "ビーチ", kana: "ビーチ", romaji: "bīchi", meaning: "pantai", type: "noun", level: "N5" },
    { kanji: "展望台", kana: "てんぼうだい", romaji: "tenboudai", meaning: "observatorium", type: "noun", level: "N5" },
    { kanji: "郵便局はどう行ったらいいですか？", kana: "ゆうびんきょくはどういったらいいですか？", romaji: "yuubinkyoku wa dou ittara ii desu ka?", meaning: "Bagaimana cara pergi ke kantor pos?", type: "expression", level: "N5" },
    { kanji: "ある", kana: "ある", romaji: "aru", meaning: "ada (berbagai hal / sesuatu yang ada di kota)", type: "verb-godan", level: "N5" },
    { kanji: "もの", kana: "もの", romaji: "mono", meaning: "hal / sesuatu; benda", type: "noun", level: "N5" },
    { kanji: "信号", kana: "しんごう", romaji: "shingou", meaning: "lampu lalu lintas", type: "noun", level: "N5" },
    { kanji: "横断歩道", kana: "おうだんほどう", romaji: "oudan hodou", meaning: "penyeberangan pejalan kaki; zebra cross", type: "noun", level: "N5" },
    { kanji: "角", kana: "かど", romaji: "kado", meaning: "sudut", type: "noun", level: "N5" },
    { kanji: "交差点", kana: "こうさてん", romaji: "kousaten", meaning: "persimpangan", type: "noun", level: "N5" },
    { kanji: "道", kana: "みち", romaji: "michi", meaning: "jalan", type: "noun", level: "N5" },
    { kanji: "橋", kana: "はし", romaji: "hashi", meaning: "jembatan", type: "noun", level: "N5" },
    { kanji: "道案内", kana: "みちあんない", romaji: "michi annai", meaning: "petunjuk arah", type: "noun", level: "N5" },
    { kanji: "まっすぐ", kana: "まっすぐ", romaji: "massugu", meaning: "lurus", type: "adverb", level: "N5" },
    { kanji: "左", kana: "ひだり", romaji: "hidari", meaning: "kiri", type: "noun", level: "N5" },
    { kanji: "曲がる", kana: "まがる", romaji: "magaru", meaning: "belok; berbelok", type: "verb-godan", level: "N5" },
    { kanji: "右", kana: "みぎ", romaji: "migi", meaning: "kanan", type: "noun", level: "N5" },
    { kanji: "渡る", kana: "わたる", romaji: "wataru", meaning: "menyeberang", type: "verb-godan", level: "N5" },
    { kanji: "〜つ目", kana: "〜つめ", romaji: "~tsume", meaning: "yang~ (menyatakan urutan; angka)", type: "suffix", level: "N5" },
    { kanji: "1つ目", kana: "ひとつめ", romaji: "hitotsume", meaning: "pertama", type: "noun", level: "N5" },
    { kanji: "2つ目", kana: "ふたつめ", romaji: "futatsume", meaning: "kedua", type: "noun", level: "N5" },
    { kanji: "バス停", kana: "バスてい", romaji: "basutei", meaning: "pemberhentian bus; halte bus", type: "noun", level: "N5" },
    { kanji: "郵便局", kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "kantor pos", type: "noun", level: "N5" },
    { kanji: "デパート", kana: "デパート", romaji: "depaato", meaning: "toserba; pasaraya; department store", type: "noun", level: "N5" },
    { kanji: "科学", kana: "かがく", romaji: "kagaku", meaning: "ilmu pengetahuan", type: "noun", level: "N5" },
    { kanji: "博物館", kana: "はくぶつかん", romaji: "hakubutsukan", meaning: "museum", type: "noun", level: "N5" },
    { kanji: "ずっと", kana: "ずっと", romaji: "zutto", meaning: "(lurus) terus", type: "adverb", level: "N5" },
    { kanji: "市立", kana: "しりつ", romaji: "shiritsu", meaning: "(milik) kota", type: "noun", level: "N5" },
    { kanji: "すぐ", kana: "すぐ", romaji: "sugu", meaning: "langsung; tepat", type: "adverb", level: "N5" },
    { kanji: "曲がったところ", kana: "まがったところ", romaji: "magatta tokoro", meaning: "setelah berbelok", type: "expression", level: "N5" },
    { kanji: "銀行", kana: "ぎんこう", romaji: "ginkou", meaning: "bank", type: "noun", level: "N5" },
    { kanji: "神社", kana: "じんじゃ", romaji: "jinja", meaning: "kuil Shinto", type: "noun", level: "N5" },
    { kanji: "駐車場", kana: "ちゅうしゃじょう", romaji: "chuushajou", meaning: "tempat parkir", type: "noun", level: "N5" },
    { kanji: "交番", kana: "こうばん", romaji: "kouban", meaning: "pos polisi", type: "noun", level: "N5" },
    { kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "rumah sakit", type: "noun", level: "N5" },
    { kanji: "黒い", kana: "くろい", romaji: "kuroi", meaning: "hitam", type: "adj-i", level: "N5" },
    { kanji: "白い", kana: "しろい", romaji: "shiroi", meaning: "putih", type: "adj-i", level: "N5" },
    { kanji: "青い", kana: "あおい", romaji: "aoi", meaning: "biru", type: "adj-i", level: "N5" },
    { kanji: "ビル", kana: "ビル", romaji: "biru", meaning: "bangunan", type: "noun", level: "N5" },
    { kanji: "アジア食材", kana: "アジアしょくざい", romaji: "ajia shokuzai", meaning: "bahan makanan khas Asia", type: "noun", level: "N5" },
    { kanji: "そちら", kana: "そちら", romaji: "sochira", meaning: "di situ", type: "noun", level: "N5" },
    { kanji: "北口", kana: "きたぐち", romaji: "kitaguchi", meaning: "pintu utara", type: "noun", level: "N5" },
    { kanji: "間", kana: "あいだ", romaji: "aida", meaning: "di antara ~ dan ~", type: "noun", level: "N5" },
    { kanji: "そうすると", kana: "そうすると", romaji: "sou suru to", meaning: "setelah itu", type: "expression", level: "N5" },
    { kanji: "見える", kana: "みえる", romaji: "mieru", meaning: "terlihat", type: "verb-ru", level: "N5" },
    { kanji: "お待ちしております", kana: "おまちしております", romaji: "omachi shite orimasu", meaning: "kami menantikan kedatangan Anda", type: "expression", level: "N5" },
    { kanji: "帰る", kana: "かえる", romaji: "kaeru", meaning: "pulang", type: "verb-godan", level: "N5" },
    { kanji: "町", kana: "ちょう", romaji: "chou", meaning: "Kota~ (pembagian geografis dalam suatu distrik)", type: "suffix", level: "N5" },
    { kanji: "高校", kana: "こうこう", romaji: "koukou", meaning: "SMA", type: "noun", level: "N5" },
    { kanji: "送る", kana: "おくる", romaji: "okuru", meaning: "mengantar (orang)", type: "verb-godan", level: "N5" },
    { kanji: "大きな", kana: "おおきな", romaji: "ookina", meaning: "besar", type: "adj-na", level: "N5" },
    { kanji: "入る", kana: "はいる", romaji: "hairu", meaning: "masuk; berbelok", type: "verb-godan", level: "N5" },
    { kanji: "どの辺？", kana: "どのへん？", romaji: "dono hen?", meaning: "Di daerah mana?", type: "expression", level: "N5" },
    { kanji: "ここでいいです", kana: "ここでいいです", romaji: "koko de ii desu", meaning: "Di sini saja", type: "expression", level: "N5" },
    { kanji: "何時にどこですか？", kana: "なんじにどこですか？", romaji: "nanji ni doko desu ka?", meaning: "Pukul berapa dan di mana?", type: "expression", level: "N5" },
    { kanji: "駅", kana: "えき", romaji: "eki", meaning: "stasiun", type: "noun", level: "N5" },
    { kanji: "受付", kana: "うけつけ", romaji: "uketsuke", meaning: "resepsionis; meja informasi", type: "noun", level: "N5" },
    { kanji: "ホール", kana: "ホール", romaji: "hooru", meaning: "aula", type: "noun", level: "N5" },
    { kanji: "会社", kana: "かいしゃ", romaji: "kaisha", meaning: "perusahaan", type: "noun", level: "N5" },
    { kanji: "門", kana: "もん", romaji: "mon", meaning: "gerbang", type: "noun", level: "N5" },
    { kanji: "集合", kana: "しゅうごう", romaji: "shuugou", meaning: "berkumpul", type: "noun", level: "N5" },
    { kanji: "では", kana: "では", romaji: "dewa", meaning: "jadi", type: "conjunction", level: "N5" },
    { kanji: "案内する", kana: "あんないする", romaji: "annai suru", meaning: "memandu", type: "verb-irregular", level: "N5" },
    { kanji: "待ち合わせ", kana: "まちあわせ", romaji: "machiawase", meaning: "janjian bertemu", type: "noun", level: "N5" },
    { kanji: "イベント", kana: "イベント", romaji: "ibento", meaning: "acara", type: "noun", level: "N5" },
    { kanji: "始まる", kana: "はじまる", romaji: "hajimaru", meaning: "mulai", type: "verb-godan", level: "N5" },
    { kanji: "スタッフ", kana: "スタッフ", romaji: "sutaffu", meaning: "staf", type: "noun", level: "N5" },
    { kanji: "前", kana: "まえ", romaji: "mae", meaning: "sebelum (30 menit sebelum)", type: "suffix", level: "N5" },
    { kanji: "何時にしますか？", kana: "なんじにしますか？", romaji: "nanji ni shimasu ka?", meaning: "Pukul berapa?", type: "expression", level: "N5" },
    { kanji: "待ち合わせする", kana: "まちあわせする", romaji: "machiawase suru", meaning: "bertemu (satu sama lain)", type: "verb-irregular", level: "N5" },
    { kanji: "平和", kana: "へいわ", romaji: "heiwa", meaning: "perdamaian", type: "noun", level: "N5" },
    { kanji: "鳥", kana: "とり", romaji: "tori", meaning: "burung", type: "noun", level: "N5" },
    { kanji: "像", kana: "ぞう", romaji: "zou", meaning: "patung", type: "noun", level: "N5" },
    { kanji: "それ、何ですか？", kana: "それ、なんですか？", romaji: "sore, nan desu ka?", meaning: "Apa itu? (Ungkapan konfirmasi)", type: "expression", level: "N5" },
    { kanji: "電車が止まりました", kana: "でんしゃがとまりました", romaji: "densha ga tomari mashita", meaning: "Kereta berhenti", type: "expression", level: "N5" },
    { kanji: "事故", kana: "じこ", romaji: "jiko", meaning: "kecelakaan", type: "noun", level: "N5" },
    { kanji: "止まる", kana: "とまる", romaji: "tomaru", meaning: "berhenti", type: "verb-godan", level: "N5" },
    { kanji: "連絡する", kana: "れんらくする", romaji: "renraku suru", meaning: "menghubungi", type: "verb-irregular", level: "N5" },
    { kanji: "寝坊する", kana: "ねぼうする", romaji: "nebou suru", meaning: "terlambat bangun; kesiangan", type: "verb-irregular", level: "N5" },
    { kanji: "今から", kana: "いまから", romaji: "ima kara", meaning: "dari sekarang", type: "expression", level: "N5" },
    { kanji: "急ぐ", kana: "いそぐ", romaji: "isogu", meaning: "bergegas", type: "verb-godan", level: "N5" },
    { kanji: "先に", kana: "さきに", romaji: "saki ni", meaning: "lebih dulu", type: "adverb", level: "N5" },
    { kanji: "始める", kana: "はじめる", romaji: "hajimeru", meaning: "mulai; memulai", type: "verb-ru", level: "N5" },
    { kanji: "道に迷う", kana: "みちにまよう", romaji: "michi ni mayou", meaning: "tersesat di jalan; salah jalan", type: "expression", level: "N5" },
    { kanji: "遅れる", kana: "おくれる", romaji: "okureru", meaning: "terlambat", type: "verb-ru", level: "N5" },
    { kanji: "着く", kana: "つく", romaji: "tsuku", meaning: "tiba", type: "verb-godan", level: "N5" },
    { kanji: "大丈夫", kana: "だいじょうぶ", romaji: "daijoubu", meaning: "tidak apa-apa; tidak masalah", type: "adj-na", level: "N5" },
    { kanji: "時間", kana: "じかん", romaji: "jikan", meaning: "waktu", type: "noun", level: "N5" },
    { kanji: "間違える", kana: "まちがえる", romaji: "machigaeru", meaning: "salah (salah paham)", type: "verb-ru", level: "N5" },
    { kanji: "待つ", kana: "まつ", romaji: "matsu", meaning: "menunggu", type: "verb-godan", level: "N5" },
    { kanji: "カフェ", kana: "カフェ", romaji: "kafe", meaning: "kafe", type: "noun", level: "N5" },
    { kanji: "野球、したことありますか？", kana: "やきゅう、したことありますか？", romaji: "yakyuu, shita koto arimasu ka?", meaning: "Pernah main bisbol?", type: "expression", level: "N5" },
    { kanji: "動物園", kana: "どうぶつえん", romaji: "doubutsuen", meaning: "kebun binatang", type: "noun", level: "N5" },
    { kanji: "お城", kana: "おしろ", romaji: "oshiro", meaning: "istana", type: "noun", level: "N5" },
    { kanji: "レストラン", kana: "レストラン", romaji: "resutoran", meaning: "restoran", type: "noun", level: "N5" },
    { kanji: "博物館", kana: "はくぶつかん", romaji: "hakubutsukan", meaning: "museum", type: "noun", level: "N5" },
    { kanji: "アウトレットモール", kana: "アウトレットモール", romaji: "autoretto mooru", meaning: "outlet mall", type: "noun", level: "N5" },
    { kanji: "プロレス", kana: "プロレス", romaji: "puroresu", meaning: "gulat profesional", type: "noun", level: "N5" },
    { kanji: "タワー", kana: "タワー", romaji: "tawaa", meaning: "menara", type: "noun", level: "N5" },
    { kanji: "野球", kana: "やきゅう", romaji: "yakyuu", meaning: "bisbol", type: "noun", level: "N5" },
    { kanji: "もう", kana: "もう", romaji: "mou", meaning: "sudah", type: "adverb", level: "N5" },
    { kanji: "まだ", kana: "まだ", romaji: "mada", meaning: "belum", type: "adverb", level: "N5" },
    { kanji: "アジア", kana: "アジア", romaji: "ajia", meaning: "Asia", type: "noun", level: "N5" },
    { kanji: "すごい", kana: "すごい", romaji: "sugoi", meaning: "sangat", type: "adj-i", level: "N5" },
    { kanji: "市民体育館", kana: "しみんたいいくかん", romaji: "shimin taiikukan", meaning: "gimnasium / gedung olahraga publik", type: "noun", level: "N5" },
    { kanji: "試合", kana: "しあい", romaji: "shiai", meaning: "pertandingan", type: "noun", level: "N5" },
    { kanji: "やる", kana: "やる", romaji: "yaru", meaning: "melakukan", type: "verb-godan", level: "N5" },
    { kanji: "メンバー", kana: "メンバー", romaji: "menbaa", meaning: "anggota", type: "noun", level: "N5" },
    { kanji: "足りない", kana: "たりない", romaji: "tarinai", meaning: "tidak cukup; kurang", type: "adj-i", level: "N5" },
    { kanji: "無理", kana: "むり", romaji: "muri", meaning: "tidak mungkin", type: "adj-na", level: "N5" },
    { kanji: "わかる", kana: "わかる", romaji: "wakaru", meaning: "mengerti", type: "verb-godan", level: "N5" },
    { kanji: "このあと、どうしますか？", kana: "このあと、どうしますか？", romaji: "kono ato, dou shimasu ka?", meaning: "Setelah ini, mau bagaimana?", type: "expression", level: "N5" },
    { kanji: "お金", kana: "おかね", romaji: "okane", meaning: "uang", type: "noun", level: "N5" },
    { kanji: "下ろす", kana: "おろす", romaji: "orosu", meaning: "menarik / mengambil (uang)", type: "verb-godan", level: "N5" },
    { kanji: "食事", kana: "しょくじ", romaji: "shokuji", meaning: "makan", type: "noun", level: "N5" },
    { kanji: "ちょっと", kana: "ちょっと", romaji: "chotto", meaning: "sedikit", type: "adverb", level: "N5" },
    { kanji: "休む", kana: "やすむ", romaji: "yasumu", meaning: "istirahat", type: "verb-godan", level: "N5" },
    { kanji: "ジョギングシューズ", kana: "ジョギングシューズ", romaji: "jogingu shuuzu", meaning: "sepatu joging", type: "noun", level: "N5" },
    { kanji: "ATM", kana: "エーティーエム", romaji: "eetiiemu", meaning: "ATM (Anjungan Tunai Mandiri)", type: "noun", level: "N5" },
    { kanji: "ゲームコーナー", kana: "ゲームコーナー", romaji: "geemu koonaa", meaning: "game arcade; pusat permainan arkade", type: "noun", level: "N5" },
    { kanji: "フードコート", kana: "フードコート", romaji: "fuudo kooto", meaning: "food court; pujasera (pusat jajanan serbaada)", type: "noun", level: "N5" },
    { kanji: "カフェ", kana: "カフェ", romaji: "kafe", meaning: "kafe", type: "noun", level: "N5" },
    { kanji: "映画館", kana: "えいがかん", romaji: "eigakan", meaning: "bioskop", type: "noun", level: "N5" },
    { kanji: "スポーツ店", kana: "スポーツてん", romaji: "supootsu ten", meaning: "toko peralatan olahraga", type: "noun", level: "N5" },
    { kanji: "このあと", kana: "このあと", romaji: "kono ato", meaning: "setelah ini; kemudian", type: "expression", level: "N5" },
    { kanji: "お腹がすく", kana: "おなかがすく", romaji: "onaka ga suku", meaning: "merasa lapar", type: "expression", level: "N5" },
    { kanji: "何か", kana: "なにか", romaji: "nanika", meaning: "sesuatu", type: "noun", level: "N5" },
    { kanji: "そのまえに", kana: "そのまえに", romaji: "sono mae ni", meaning: "sebelum itu", type: "expression", level: "N5" },
    { kanji: "パンダがかわいかったです", kana: "パンダがかわいかったです", romaji: "panda ga kawaikatta desu", meaning: "Panda-nya lucu", type: "expression", level: "N5" },
    { kanji: "素晴らしい", kana: "すばらしい", romaji: "subarashii", meaning: "bagus", type: "adj-i", level: "N5" },
    { kanji: "難しい", kana: "むずかしい", romaji: "muzukashii", meaning: "sukar; sulit", type: "adj-i", level: "N5" },
    { kanji: "感動する", kana: "かんどうする", romaji: "kandou suru", meaning: "terkesan", type: "verb-irregular", level: "N5" },
    { kanji: "かわいい", kana: "かわいい", romaji: "kawaii", meaning: "lucu; manis", type: "adj-i", level: "N5" },
    { kanji: "展覧会", kana: "てんらんかい", romaji: "tenrankai", meaning: "pameran", type: "noun", level: "N5" },
    { kanji: "パンダ", kana: "パンダ", romaji: "panda", meaning: "panda", type: "noun", level: "N5" },
    { kanji: "サル", kana: "サル", romaji: "saru", meaning: "kera", type: "noun", level: "N5" },
    { kanji: "現代", kana: "げんだい", romaji: "gendai", meaning: "modern", type: "noun", level: "N5" },
    { kanji: "作品", kana: "さくひん", romaji: "sakuhin", meaning: "karya seni", type: "noun", level: "N5" },
    { kanji: "ホラー映画", kana: "ホラーえいが", romaji: "horaa eiga", meaning: "film horor", type: "noun", level: "N5" },
    { kanji: "つまらない", kana: "つまらない", romaji: "tsumaranai", meaning: "bosan; membosankan", type: "adj-i", level: "N5" },
    { kanji: "退屈", kana: "たいくつ", romaji: "taikutsu", meaning: "bosan; membosankan", type: "adj-na", level: "N5" },
    { kanji: "いまいち", kana: "いまいち", romaji: "imaichi", meaning: "tidak cukup bagus", type: "adj-na", level: "N5" },
    { kanji: "読み方を教えてもらえませんか？", kana: "よみかたをおしえてもらえませんか？", romaji: "yomikata o oshiete moraemasen ka?", meaning: "Bisa kah mengajari cara bacanya?", type: "expression", level: "N5" },
    { kanji: "日本語学校", kana: "にほんごがっこう", romaji: "nihongo gakkou", meaning: "Sekolah bahasa Jepang", type: "noun", level: "N5" },
    { kanji: "高校", kana: "こうこう", romaji: "koukou", meaning: "SMA", type: "noun", level: "N5" },
    { kanji: "どれぐらい", kana: "どれぐらい", romaji: "dore gurai", meaning: "berapa lama", type: "expression", level: "N5" },
    { kanji: "上手", kana: "じょうず", romaji: "jouzu", meaning: "pandai / terampil", type: "adj-na", level: "N5" },
    { kanji: "間", kana: "かん", romaji: "kan", meaning: "selama ~ (selama 2 tahun)", type: "suffix", level: "N5" },
    { kanji: "自分で", kana: "じぶんで", romaji: "jibun de", meaning: "melakukan sendiri", type: "expression", level: "N5" },
    { kanji: "まだまだです", kana: "まだまだです", romaji: "mada mada desu", meaning: "masih belum begitu mahir.", type: "expression", level: "N5" },
    { kanji: "そんなことないです", kana: "そんなことないです", romaji: "sonna koto nai desu", meaning: "tidak juga", type: "expression", level: "N5" },
    { kanji: "大学", kana: "だいがく", romaji: "daigaku", meaning: "universitas", type: "noun", level: "N5" },
    { kanji: "ラジオ", kana: "ラジオ", romaji: "rajio", meaning: "radio", type: "noun", level: "N5" },
    { kanji: "ネット", kana: "ネット", romaji: "netto", meaning: "internet", type: "noun", level: "N5" },
    { kanji: "アプリ", kana: "アプリ", romaji: "apuri", meaning: "aplikasi", type: "noun", level: "N5" },
    { kanji: "会話は得意です", kana: "かいわはとくいです", romaji: "kaiwa wa tokui desu", meaning: "Saya mahir dalam percakapan", type: "expression", level: "N5" },
    { kanji: "日本語", kana: "にほんご", romaji: "nihongo", meaning: "Bahasa Jepang", type: "noun", level: "N5" },
    { kanji: "勉強", kana: "べんきょう", romaji: "benkyou", meaning: "belajar", type: "noun", level: "N5" },
    { kanji: "簡単", kana: "かんたん", romaji: "kantan", meaning: "mudah; gampang", type: "adj-na", level: "N5" },
    { kanji: "難しい", kana: "むずかしい", romaji: "muzukashii", meaning: "susah; sulit", type: "adj-i", level: "N5" },
    { kanji: "似ている", kana: "にている", romaji: "nite iru", meaning: "serupa; mirip", type: "verb-irregular", level: "N5" },
    { kanji: "違う", kana: "ちがう", romaji: "chigau", meaning: "berbeda", type: "verb-godan", level: "N5" },
    { kanji: "得意", kana: "とくい", romaji: "tokui", meaning: "mahir; pandai", type: "adj-na", level: "N5" },
    { kanji: "苦手", kana: "にがて", romaji: "nigate", meaning: "tidak mahir; tidak pandai", type: "adj-na", level: "N5" },
    { kanji: "文法", kana: "ぶんぽう", romaji: "bunpou", meaning: "tata bahasa", type: "noun", level: "N5" },
    { kanji: "発音", kana: "はつおん", romaji: "hatsuon", meaning: "pelafalan; pengucapan", type: "noun", level: "N5" },
    { kanji: "文字", kana: "もじ", romaji: "moji", meaning: "huruf", type: "noun", level: "N5" },
    { kanji: "ひらがな", kana: "ひらがな", romaji: "hiragana", meaning: "hiragana", type: "noun", level: "N5" },
    { kanji: "カタカナ", kana: "カタカナ", romaji: "katakana", meaning: "katakana", type: "noun", level: "N5" },
    { kanji: "漢字", kana: "かんじ", romaji: "kanji", meaning: "kanji", type: "noun", level: "N5" },
    { kanji: "会話", kana: "かいわ", romaji: "kaiwa", meaning: "percakapan", type: "noun", level: "N5" },
    { kanji: "モンゴル語", kana: "モンゴルご", romaji: "mongoru go", meaning: "bahasa Mongolia", type: "noun", level: "N5" },
    { kanji: "ベトナム語", kana: "ベトナムご", romaji: "betonamu go", meaning: "bahasa Vietnam", type: "noun", level: "N5" },
    { kanji: "覚える", kana: "おぼえる", romaji: "oboeru", meaning: "menghafal", type: "verb-ru", level: "N5" },
    { kanji: "日本語をチェックしてもらえませんか？", kana: "にほんごをチェックしてもらえませんか？", romaji: "nihongo o chekku shite moraemasen ka?", meaning: "Bisa periksa bahasa Jepangnya?", type: "expression", level: "N5" },
    { kanji: "教える", kana: "おしえる", romaji: "oshieru", meaning: "mengajar; mengajarkan", type: "verb-ru", level: "N5" },
    { kanji: "辞書", kana: "じしょ", romaji: "jisho", meaning: "kamus", type: "noun", level: "N5" },
    { kanji: "貸す", kana: "かす", romaji: "kasu", meaning: "meminjamkan", type: "verb-godan", level: "N5" },
    { kanji: "見せる", kana: "みせる", romaji: "miseru", meaning: "memperlihatkan", type: "verb-ru", level: "N5" },
    { kanji: "チェックする", kana: "チェックする", romaji: "chekku suru", meaning: "memeriksa", type: "verb-irregular", level: "N5" },
    { kanji: "説明する", kana: "せつめいする", romaji: "setsumei suru", meaning: "menjelaskan", type: "verb-irregular", level: "N5" },
    { kanji: "紙", kana: "かみ", romaji: "kami", meaning: "kertas", type: "noun", level: "N5" },
    { kanji: "書く", kana: "かく", romaji: "kaku", meaning: "menulis", type: "verb-godan", level: "N5" },
    { kanji: "言う", kana: "いう", romaji: "iu", meaning: "mengatakan; mengucapkan", type: "verb-godan", level: "N5" },
    { kanji: "ゆっくり", kana: "ゆっくり", romaji: "yukkuri", meaning: "pelan-pelan", type: "adverb", level: "N5" },
    { kanji: "方", kana: "かた", romaji: "kata", meaning: "cara~ (cara membaca)", type: "suffix", level: "N5" },
    { kanji: "メール", kana: "メール", romaji: "meeru", meaning: "surel (surat elektronik)", type: "noun", level: "N5" },
    { kanji: "書類", kana: "しょるい", romaji: "shorui", meaning: "dokumen", type: "noun", level: "N5" },
    { kanji: "教科書", kana: "きょうかしょ", romaji: "kyoukasho", meaning: "buku pelajaran", type: "noun", level: "N5" },
    { kanji: "自信がありません", kana: "じしんがありません", romaji: "jishin ga arimasen", meaning: "tidak percaya diri", type: "expression", level: "N5" },
    { kanji: "練習", kana: "れんしゅう", romaji: "renshuu", meaning: "latihan", type: "noun", level: "N5" },
    { kanji: "探す", kana: "さがす", romaji: "sagasu", meaning: "mencari", type: "verb-godan", level: "N5" },
    { kanji: "買い物", kana: "かいもの", romaji: "kaimono", meaning: "belanja", type: "noun", level: "N5" },
    { kanji: "買う", kana: "かう", romaji: "kau", meaning: "membeli", type: "verb-godan", level: "N5" },
    { kanji: "売る", kana: "うる", romaji: "uru", meaning: "menjual", type: "verb-godan", level: "N5" },
    { kanji: "スーパー", kana: "スーパー", romaji: "suupaa", meaning: "supermarket", type: "noun", level: "N5" },
    { kanji: "コンビニ", kana: "コンビニ", romaji: "konbini", meaning: "toko serba ada; minimarket", type: "noun", level: "N5" },
    { kanji: "デパート", kana: "デパート", romaji: "depaato", meaning: "department store", type: "noun", level: "N5" },
    { kanji: "服", kana: "ふく", romaji: "fuku", meaning: "pakaian", type: "noun", level: "N5" },
    { kanji: "靴", kana: "くつ", romaji: "kutsu", meaning: "sepatu", type: "noun", level: "N5" },
    { kanji: "かばん", kana: "かばん", romaji: "kaban", meaning: "tas", type: "noun", level: "N5" },
    { kanji: "本屋", kana: "ほんや", romaji: "honya", meaning: "toko buku", type: "noun", level: "N5" },
    { kanji: "薬屋", kana: "くすりや", romaji: "kusuriya", meaning: "apotik", type: "noun", level: "N5" },
    { kanji: "値段", kana: "ねだん", romaji: "nedan", meaning: "harga", type: "noun", level: "N5" },
    { kanji: "安い", kana: "やすい", romaji: "yasui", meaning: "murah", type: "adj-i", level: "N5" },
    { kanji: "高い", kana: "たかい", romaji: "takai", meaning: "mahal", type: "adj-i", level: "N5" },
    { kanji: "いくら", kana: "いくら", romaji: "ikura", meaning: "berapa (harga)", type: "adverb", level: "N5" },
    { kanji: "円", kana: "えん", romaji: "en", meaning: "yen", type: "noun", level: "N5" },
    { kanji: "これ", kana: "これ", romaji: "kore", meaning: "ini", type: "noun", level: "N5" },
    { kanji: "それ", kana: "それ", romaji: "sore", meaning: "itu", type: "noun", level: "N5" },
    { kanji: "あれ", kana: "あれ", romaji: "are", meaning: "itu (jauh)", type: "noun", level: "N5" },
    { kanji: "どれ", kana: "どれ", romaji: "dore", meaning: "yang mana", type: "noun", level: "N5" },
    { kanji: "この", kana: "この", romaji: "kono", meaning: "ini (modifier)", type: "adjective", level: "N5" },
    { kanji: "その", kana: "その", romaji: "sono", meaning: "itu (modifier)", type: "adjective", level: "N5" },
    { kanji: "あの", kana: "あの", romaji: "ano", meaning: "itu (jauh, modifier)", type: "adjective", level: "N5" },
    { kanji: "どの", kana: "どの", romaji: "dono", meaning: "yang mana (modifier)", type: "adjective", level: "N5" },
    { kanji: "お願いします", kana: "おねがいします", romaji: "onegai shimasu", meaning: "tolong; saya minta", type: "expression", level: "N5" },
    { kanji: "ありがとうございます", kana: "ありがとうございます", romaji: "arigatou gozaimasu", meaning: "terima kasih", type: "expression", level: "N5" },
    { kanji: "どういたしまして", kana: "どういたしまして", romaji: "dou itashimashite", meaning: "sama-sama", type: "expression", level: "N5" },
    { kanji: "すみません", kana: "すみません", romaji: "sumimasen", meaning: "permisi; maaf", type: "expression", level: "N5" },
    { kanji: "ちょっと待ってください", kana: "ちょっとまってください", romaji: "chotto matte kudasai", meaning: "tunggu sebentar", type: "expression", level: "N5" },
    { kanji: "食べ物", kana: "たべもの", romaji: "tabemono", meaning: "makanan", type: "noun", level: "N5" },
    { kanji: "飲み物", kana: "のみもの", romaji: "nomimono", meaning: "minuman", type: "noun", level: "N5" },
    { kanji: "果物", kana: "くだもの", romaji: "kudamono", meaning: "buah-buahan", type: "noun", level: "N5" },
    { kanji: "野菜", kana: "やさい", romaji: "yasai", meaning: "sayur-sayuran", type: "noun", level: "N5" },
    { kanji: "肉", kana: "にく", romaji: "niku", meaning: "daging", type: "noun", level: "N5" },
    { kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "ikan", type: "noun", level: "N5" },
    { kanji: "卵", kana: "たまご", romaji: "tamago", meaning: "telur", type: "noun", level: "N5" },
    { kanji: "パン", kana: "パン", romaji: "pan", meaning: "roti", type: "noun", level: "N5" },
    { kanji: "ご飯", kana: "ごはん", romaji: "gohan", meaning: "nasi; makanan", type: "noun", level: "N5" },
    { kanji: "水", kana: "みず", romaji: "mizu", meaning: "air", type: "noun", level: "N5" },
    { kanji: "お茶", kana: "おちゃ", romaji: "ocha", meaning: "teh", type: "noun", level: "N5" },
    { kanji: "コーヒー", kana: "コーヒー", romaji: "koohii", meaning: "kopi", type: "noun", level: "N5" },
    { kanji: "ジュース", kana: "ジュース", romaji: "juusu", meaning: "jus", type: "noun", level: "N5" },
    { kanji: "牛乳", kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "susu", type: "noun", level: "N5" },
    { kanji: "ビール", kana: "ビール", romaji: "biiru", meaning: "bir", type: "noun", level: "N5" },
    { kanji: "お酒", kana: "おさけ", romaji: "osake", meaning: "minuman beralkohol", type: "noun", level: "N5" },
    { kanji: "りんご", kana: "りんご", romaji: "ringo", meaning: "apel", type: "noun", level: "N5" },
    { kanji: "バナナ", kana: "バナナ", romaji: "banana", meaning: "pisang", type: "noun", level: "N5" },
    { kanji: "みかん", kana: "みかん", romaji: "mikan", meaning: "jeruk mandarin", type: "noun", level: "N5" },
    { kanji: "いちご", kana: "いちご", romaji: "ichigo", meaning: "stroberi", type: "noun", level: "N5" },
    { kanji: "すいか", kana: "すいか", romaji: "suika", meaning: "semangka", type: "noun", level: "N5" },
    { kanji: "メロン", kana: "メロン", romaji: "meron", meaning: "melon", type: "noun", level: "N5" },
    { kanji: "にんじん", kana: "にんじん", romaji: "ninjin", meaning: "wortel", type: "noun", level: "N5" },
    { kanji: "玉ねぎ", kana: "たまねぎ", romaji: "tamanegi", meaning: "bawang bombay", type: "noun", level: "N5" },
    { kanji: "じゃがいも", kana: "じゃがいも", romaji: "jagaimo", meaning: "kentang", type: "noun", level: "N5" },
    { kanji: "トマト", kana: "トマト", romaji: "tomato", meaning: "tomat", type: "noun", level: "N5" },
    { kanji: "きゅうり", kana: "きゅうり", romaji: "kyuuri", meaning: "timun", type: "noun", level: "N5" },
    { kanji: "なす", kana: "なす", romaji: "nasu", meaning: "terong", type: "noun", level: "N5" },
    { kanji: "おいしい", kana: "おいしい", romaji: "oishii", meaning: "enak", type: "adj-i", level: "N5" },
    { kanji: "まずい", kana: "まずい", romaji: "mazui", meaning: "tidak enak", type: "adj-i", level: "N5" },
    { kanji: "甘い", kana: "あまい", romaji: "amai", meaning: "manis", type: "adj-i", level: "N5" },
    { kanji: "辛い", kana: "からい", romaji: "karai", meaning: "pedas", type: "adj-i", level: "N5" },
    { kanji: "すっぱい", kana: "すっぱい", romaji: "suppai", meaning: "asam", type: "adj-i", level: "N5" },
    { kanji: "にがい", kana: "にがい", romaji: "nigai", meaning: "pahit", type: "adj-i", level: "N5" },
    { kanji: "しょっぱい", kana: "しょっぱい", romaji: "shoppai", meaning: "asin", type: "adj-i", level: "N5" },
    { kanji: "新鮮", kana: "しんせん", romaji: "shinsen", meaning: "segar", type: "adj-na", level: "N5" },
    { kanji: "古い", kana: "ふるい", romaji: "furui", meaning: "lama; basi", type: "adj-i", level: "N5" },
    { kanji: "お腹がすく", kana: "おなかがすく", romaji: "onaka ga suku", meaning: "lapar", type: "expression", level: "N5" },
    { kanji: "のどが渇く", kana: "のどがかわく", romaji: "nodo ga kawaku", meaning: "haus", type: "expression", level: "N5" },
    { kanji: "食べる", kana: "たべる", romaji: "taberu", meaning: "makan", type: "verb-ru", level: "N5" },
    { kanji: "飲む", kana: "のむ", romaji: "nomu", meaning: "minum", type: "verb-godan", level: "N5" },
    { kanji: "朝", kana: "あさ", romaji: "asa", meaning: "pagi", type: "noun", level: "N5" },
    { kanji: "昼", kana: "ひる", romaji: "hiru", meaning: "siang", type: "noun", level: "N5" },
    { kanji: "夜", kana: "よる", romaji: "yoru", meaning: "malam", type: "noun", level: "N5" },
    { kanji: "朝ご飯", kana: "あさごはん", romaji: "asagohan", meaning: "sarapan", type: "noun", level: "N5" },
    { kanji: "昼ご飯", kana: "ひるごはん", romaji: "hirugohan", meaning: "makan siang", type: "noun", level: "N5" },
    { kanji: "晩ご飯", kana: "ばんごはん", romaji: "bangohan", meaning: "makan malam", type: "noun", level: "N5" },
    { kanji: "毎朝", kana: "まいあさ", romaji: "maiasa", meaning: "setiap pagi", type: "noun", level: "N5" },
    { kanji: "毎晩", kana: "まいばん", romaji: "maiban", meaning: "setiap malam", type: "noun", level: "N5" },
    { kanji: "毎日", kana: "まいにち", romaji: "mainichi", meaning: "setiap hari", type: "noun", level: "N5" },
    { kanji: "起きる", kana: "おきる", romaji: "okiru", meaning: "bangun tidur", type: "verb-ru", level: "N5" },
    { kanji: "寝る", kana: "ねる", romaji: "neru", meaning: "tidur", type: "verb-ru", level: "N5" },
    { kanji: "顔を洗う", kana: "かおをあらう", romaji: "kao o arau", meaning: "mencuci muka", type: "expression", level: "N5" },
    { kanji: "歯を磨く", kana: "はをみがく", romaji: "ha o migaku", meaning: "menggosok gigi", type: "expression", level: "N5" },
    { kanji: "シャワー", kana: "シャワー", romaji: "shawaa", meaning: "mandi (shower)", type: "noun", level: "N5" },
    { kanji: "風呂に入る", kana: "ふろにはいる", romaji: "furo ni hairu", meaning: "mandi (berendam)", type: "expression", level: "N5" },
    { kanji: "新聞を読む", kana: "しんぶんをよむ", romaji: "shinbun o yomu", meaning: "membaca koran", type: "expression", level: "N5" },
    { kanji: "ラジオを聞く", kana: "ラジオをきく", romaji: "rajio o kiku", meaning: "mendengar radio", type: "expression", level: "N5" },
    { kanji: "テレビを見る", kana: "テレビをみる", romaji: "terebi o miru", meaning: "menonton TV", type: "expression", level: "N5" },
    { kanji: "学校に行く", kana: "がっこうにいく", romaji: "gakkou ni iku", meaning: "pergi ke sekolah", type: "expression", level: "N5" },
    { kanji: "仕事に行く", kana: "しごとに行く", romaji: "shigoto ni iku", meaning: "pergi bekerja", type: "expression", level: "N5" },
    { kanji: "家に帰る", kana: "いえにかえる", romaji: "ie ni kaeru", meaning: "pulang ke rumah", type: "expression", level: "N5" },
    { kanji: "宿題をする", kana: "しゅくだいをする", romaji: "shukudai o suru", meaning: "mengerjakan PR", type: "expression", level: "N5" },
    { kanji: "買い物をする", kana: "かいものををする", romaji: "kaimono o suru", meaning: "belanja", type: "expression", level: "N5" },
    { kanji: "掃除をする", kana: "そうじをする", romaji: "souji o suru", meaning: "membersihkan", type: "expression", level: "N5" },
    { kanji: "洗濯をする", kana: "せんたくをする", romaji: "sentaku o suru", meaning: "mencuci pakaian", type: "expression", level: "N5" },
    { kanji: "料理をする", kana: "りょうりをする", romaji: "ryouri o suru", meaning: "memasak", type: "expression", level: "N5" },
    { kanji: "友達に電話する", kana: "ともだちにでんわする", romaji: "tomodachi ni denwa suru", meaning: "menelpon teman", type: "expression", level: "N5" },
    { kanji: "スポーツをする", kana: "スポーツをする", romaji: "supootsu o suru", meaning: "berolahraga", type: "expression", level: "N5" },
    { kanji: "散歩をする", kana: "さんぽをする", romaji: "sanpo o suru", meaning: "berjalan-jalan", type: "expression", level: "N5" },
    { kanji: "電気", kana: "でんき", romaji: "denki", meaning: "lampu; listrik", type: "noun", level: "N5" },
    { kanji: "つく", kana: "つく", romaji: "tsuku", meaning: "menyala (lampu menyala)", type: "verb-godan", level: "N5" },
    { kanji: "変", kana: "へん", romaji: "hen", meaning: "aneh", type: "adj-na", level: "N5" },
    { kanji: "音", kana: "おと", romaji: "oto", meaning: "bunyi", type: "noun", level: "N5" },
    { kanji: "音がする", kana: "おとがする", romaji: "oto ga suru", meaning: "berbunyi", type: "verb-irregular", level: "N5" },
    { kanji: "動く", kana: "うごく", romaji: "ugoku", meaning: "bergerak; beroperasi", type: "verb-godan", level: "N5" },
    { kanji: "トイレットペーパー", kana: "トイレットペーパー", romaji: "toiretto peepaa", meaning: "tisu toilet", type: "noun", level: "N5" },
    { kanji: "なくなる", kana: "なくなる", romaji: "nakunaru", meaning: "habis", type: "verb-godan", level: "N5" },
    { kanji: "業者", kana: "ぎょうしゃ", romaji: "gyousha", meaning: "dealer; vendor", type: "noun", level: "N5" },
    { kanji: "電話する", kana: "でんわする", romaji: "denwa suru", meaning: "menelpon", type: "verb-irregular", level: "N5" },
    { kanji: "再起動する", kana: "さいきどうする", romaji: "saikidou suru", meaning: "to restart; memulai ulang", type: "verb-irregular", level: "N5" },
    { kanji: "管理室", kana: "かんりしつ", romaji: "kanrishitsu", meaning: "ruang manajemen; ruang kontrol", type: "noun", level: "N5" },
    { kanji: "連絡する", kana: "れんらくする", romaji: "renraku suru", meaning: "menghubungi", type: "verb-irregular", level: "N5" },
    { kanji: "倉庫", kana: "そうこ", romaji: "souko", meaning: "gudang", type: "noun", level: "N5" },
    { kanji: "取ってくる", kana: "とってくる", romaji: "totte kuru", meaning: "mengambil (lalu kembali ke tempat semula)", type: "verb-godan", level: "N5" },
    { kanji: "コーヒーマシーン", kana: "コーヒーマシーン", romaji: "koohii mashiin", meaning: "mesin pembuat kopi", type: "noun", level: "N5" },
    { kanji: "パソコン", kana: "パソコン", romaji: "pasokon", meaning: "PC; komputer", type: "noun", level: "N5" },
    { kanji: "とりあえず", kana: "とりあえず", romaji: "toriaezu", meaning: "untuk saat ini; sementara ini", type: "adverb", level: "N5" },
    { kanji: "やり方", kana: "やりかた", romaji: "yarikata", meaning: "cara melakukan (sesuatu)", type: "noun", level: "N5" },
    { kanji: "終わる", kana: "おわる", romaji: "owaru", meaning: "selesai", type: "verb-godan", level: "N5" },
    { kanji: "もうすぐ", kana: "もうすぐ", romaji: "mousugu", meaning: "segera; sebentar lagi; hampir", type: "adverb", level: "N5" },
    { kanji: "できる", kana: "できる", romaji: "dekiru", meaning: "selesai; rampung", type: "verb-irregular", level: "N5" },
    { kanji: "コピー機", kana: "コピーき", romaji: "kopiiki", meaning: "mesin fotokopi", type: "noun", level: "N5" },
    { kanji: "原稿", kana: "げんこう", romaji: "genkou", meaning: "naskah; dokumen", type: "noun", level: "N5" },
    { kanji: "セットする", kana: "セットする", romaji: "setto suru", meaning: "mengeset", type: "verb-irregular", level: "N5" },
    { kanji: "枚数", kana: "まいすう", romaji: "maisuu", meaning: "jumlah lembar", type: "noun", level: "N5" },
    { kanji: "数字", kana: "すうじ", romaji: "suuji", meaning: "bilangan; angka", type: "noun", level: "N5" },
    { kanji: "入れる", kana: "いれる", romaji: "ireru", meaning: "memasukkan", type: "verb-ru", level: "N5" },
    { kanji: "スタート", kana: "スタート", romaji: "sutaato", meaning: "mulai", type: "noun", level: "N5" },
    { kanji: "ボタン", kana: "ボタン", romaji: "botan", meaning: "tombol", type: "noun", level: "N5" },
    { kanji: "押す", kana: "おす", romaji: "osu", meaning: "menekan", type: "verb-godan", level: "N5" },
    { kanji: "両面", kana: "りょうめん", romaji: "ryoumen", meaning: "dua sisi", type: "noun", level: "N5" },
    { kanji: "片面", kana: "かためん", romaji: "katamen", meaning: "satu sisi", type: "noun", level: "N5" },
    { kanji: "カラー", kana: "カラー", romaji: "karaa", meaning: "berwarna", type: "noun", level: "N5" },
    { kanji: "できるだけ", kana: "できるだけ", romaji: "dekirudake", meaning: "sedapat mungkin", type: "adverb", level: "N5" },
    { kanji: "白黒", kana: "しろくろ", romaji: "shirokuro", meaning: "hitam putih", type: "noun", level: "N5" },
    { kanji: "スキャナ", kana: "スキャナ", romaji: "sukyana", meaning: "pemindai", type: "noun", level: "N5" },
    { kanji: "ファックス", kana: "ファックス", romaji: "fakkusu", meaning: "faks; faksimile", type: "noun", level: "N5" },
    { kanji: "自動選択", kana: "じどうせんたく", romaji: "jidousentaku", meaning: "pemilihan otomatis", type: "noun", level: "N5" },
    { kanji: "フルカラー", kana: "フルカラー", romaji: "furukaraa", meaning: "full color; penuh warna", type: "noun", level: "N5" },
    { kanji: "2色", kana: "にしょく", romaji: "nishoku", meaning: "dua warna", type: "noun", level: "N5" },
    { kanji: "単色", kana: "たんしょく", romaji: "tanshoku", meaning: "monokrom; warna tunggal", type: "noun", level: "N5" },
    { kanji: "自動濃度", kana: "じどうのうど", romaji: "jidounoudo", meaning: "tingkat saturasi warna otomatis", type: "noun", level: "N5" },
    { kanji: "用紙", kana: "ようし", romaji: "youshi", meaning: "kertas", type: "noun", level: "N5" },
    { kanji: "手差し", kana: "てざし", romaji: "tezashi", meaning: "memasukkan (kertas) secara manual", type: "noun", level: "N5" },
    { kanji: "倍率", kana: "ばいりつ", romaji: "bairitsu", meaning: "pengaturan skala (ukuran dokumen)", type: "noun", level: "N5" },
    { kanji: "等倍", kana: "とうばい", romaji: "toubai", meaning: "ukuran sama", type: "noun", level: "N5" },
    { kanji: "変倍", kana: "へんばい", romaji: "henbai", meaning: "ukuran berbeda", type: "noun", level: "N5" },
    { kanji: "拡大", kana: "かくだい", romaji: "kakudai", meaning: "pembesaran", type: "noun", level: "N5" },
    { kanji: "縮小", kana: "しゅくしょう", romaji: "shukushou", meaning: "pengecilan", type: "noun", level: "N5" },
    { kanji: "ソート", kana: "ソート", romaji: "sooto", meaning: "susunan, urutan", type: "noun", level: "N5" },
    { kanji: "ホチキス止め", kana: "ホチキスどめ", romaji: "hochikisu dome", meaning: "staples", type: "noun", level: "N5" },
    { kanji: "資料", kana: "しりょう", romaji: "shiryou", meaning: "dokumen", type: "noun", level: "N5" },
    { kanji: "キャビネット", kana: "キャビネット", romaji: "kyabinetto", meaning: "lemari (dengan rak / laci untuk menyimpan dokumen)", type: "noun", level: "N5" },
    { kanji: "戻す", kana: "もどす", romaji: "modosu", meaning: "mengembalikan", type: "verb-godan", level: "N5" },
    { kanji: "扉", kana: "とびら", romaji: "tobira", meaning: "pintu", type: "noun", level: "N5" },
    { kanji: "開ける", kana: "あける", romaji: "akeru", meaning: "membuka", type: "verb-ru", level: "N5" },
    { kanji: "棚", kana: "たな", romaji: "tana", meaning: "rak", type: "noun", level: "N5" },
    { kanji: "並べる", kana: "ならべる", romaji: "naraberu", meaning: "menata; menyusun", type: "verb-ru", level: "N5" },
    { kanji: "丸い", kana: "まるい", romaji: "marui", meaning: "bundar", type: "adj-i", level: "N5" },
    { kanji: "出す", kana: "だす", romaji: "dasu", meaning: "mengeluarkan", type: "verb-godan", level: "N5" },
    { kanji: "～列", kana: "～れつ", romaji: "~retsu", meaning: "～baris", type: "suffix", level: "N5" },
    { kanji: "後ろ", kana: "うしろ", romaji: "ushiro", meaning: "belakang", type: "noun", level: "N5" },
    { kanji: "スペース", kana: "スペース", romaji: "supeesu", meaning: "ruang; jarak", type: "noun", level: "N5" },
    { kanji: "あける", kana: "あける", romaji: "akeru", meaning: "menyediakan (ruang; jarak)", type: "verb-ru", level: "N5" },
    { kanji: "入り口", kana: "いりぐち", romaji: "iriguchi", meaning: "pintu masuk", type: "noun", level: "N5" },
    { kanji: "四角い", kana: "しかくい", romaji: "shikakui", meaning: "persegi empat", type: "adj-i", level: "N5" },
    { kanji: "置く", kana: "おく", romaji: "oku", meaning: "meletakkan; menaruh", type: "verb-godan", level: "N5" },
    { kanji: "会議", kana: "かいぎ", romaji: "kaigi", meaning: "rapat", type: "noun", level: "N5" },
    { kanji: "セッティング", kana: "セッティング", romaji: "settingu", meaning: "penataan", type: "noun", level: "N5" },
    { kanji: "コの字", kana: "コのじ", romaji: "ko no ji", meaning: "berbentuk huruf-U", type: "noun", level: "N5" },
    { kanji: "準備する", kana: "じゅんびする", romaji: "junbi suru", meaning: "mempersiapkan; menyiapkan", type: "verb-irregular", level: "N5" },
    { kanji: "人数分", kana: "にんずうぶん", romaji: "ninzuu bun", meaning: "sebanyak jumlah orang", type: "noun", level: "N5" },
    { kanji: "～ぶ", kana: "～ぶ", romaji: "~bu", meaning: "～bundel fotokopi", type: "suffix", level: "N5" },
    { kanji: "頼む", kana: "たのむ", romaji: "tanomu", meaning: "meminta; memesan", type: "verb-godan", level: "N5" },
    { kanji: "いいです", kana: "いいです", romaji: "ii desu", meaning: "tidak usah; tidak perlu", type: "expression", level: "N5" },
    { kanji: "件名", kana: "けんめい", romaji: "kenmei", meaning: "perihal", type: "noun", level: "N5" },
    { kanji: "変更", kana: "へんこう", romaji: "henkou", meaning: "perubahan", type: "noun", level: "N5" },
    { kanji: "お知らせ", kana: "おしらせ", romaji: "oshirase", meaning: "pemberitahuan; notifikasi", type: "noun", level: "N5" },
    { kanji: "都合が悪い", kana: "つごうがわるい", romaji: "tsugou ga warui", meaning: "berhalangan", type: "expression", level: "N5" },
    { kanji: "注意", kana: "ちゅうい", romaji: "chuui", meaning: "memperhatikan", type: "noun", level: "N5" },
    { kanji: "社内メール", kana: "しゃないメール", romaji: "shanai meeru", meaning: "surel internal perusahaan", type: "noun", level: "N5" },
    { kanji: "打ち合わせ", kana: "うちあわせ", romaji: "uchiawase", meaning: "pertemuan; rapat", type: "noun", level: "N5" },
    { kanji: "日程", kana: "にってい", romaji: "nittei", meaning: "jadwal", type: "noun", level: "N5" },
    { kanji: "差出人", kana: "さしだしにん", romaji: "sashidashinin", meaning: "pengirim", type: "noun", level: "N5" },
    { kanji: "日付", kana: "ひづけ", romaji: "hizuke", meaning: "tanggal", type: "noun", level: "N5" },
    { kanji: "皆様", kana: "みなさま", romaji: "minasama", meaning: "(salam sejahtera untuk) Anda sekalian", type: "noun", level: "N5" },
    { kanji: "なお", kana: "なお", romaji: "nao", meaning: "untuk itu; oleh karena itu", type: "adverb", level: "N5" },
    { kanji: "お知らせします", kana: "おしらせします", romaji: "oshirase shimasu", meaning: "menyampaikan pemberitahuan", type: "expression", level: "N5" },
    { kanji: "ご連絡ください", kana: "ごれんらくください", romaji: "gorenraku kudasai", meaning: "Mohon hubungi~", type: "expression", level: "N5" },
    { kanji: "ご注意ください", kana: "ごちゅういください", romaji: "gochuui kudasai", meaning: "Mohon perhatikan~", type: "expression", level: "N5" },
    { kanji: "総務", kana: "そうむ", romaji: "soumu", meaning: "bagian umum", type: "noun", level: "N5" },
    { kanji: "氏名", kana: "しめい", romaji: "shimei", meaning: "nama lengkap", type: "noun", level: "N5" },
    { kanji: "ハンコ", kana: "ハンコ", romaji: "hanko", meaning: "stempel", type: "noun", level: "N5" },
    { kanji: "持っている", kana: "もっている", romaji: "motte iru", meaning: "memiliki", type: "verb-irregular", level: "N5" },
    { kanji: "持つ", kana: "もつ", romaji: "motsu", meaning: "memiliki", type: "verb-godan", level: "N5" },
    { kanji: "で", kana: "で", romaji: "de", meaning: "maka; jadi; oleh karena itu (bentuk informal untuk mengatakan それで)", type: "particle", level: "N5" },
    { kanji: "期間", kana: "きかん", romaji: "kikan", meaning: "durasi waktu", type: "noun", level: "N5" },
    { kanji: "理由", kana: "りゆう", romaji: "riyuu", meaning: "alasan", type: "noun", level: "N5" },
    { kanji: "普通", kana: "ふつう", romaji: "futsuu", meaning: "biasa", type: "adj-na", level: "N5" },
    { kanji: "私用", kana: "しゅう", romaji: "shiyou", meaning: "urusan pribadi", type: "noun", level: "N5" },
    { kanji: "～中", kana: "～ちゅう", romaji: "~chuu", meaning: "sedang ～", type: "suffix", level: "N5" },
    { kanji: "連絡先", kana: "れんらくさき", romaji: "renrakusaki", meaning: "alamat yang dapat dihubungi", type: "noun", level: "N5" },
    { kanji: "備考", kana: "びこう", romaji: "bikou", meaning: "catatan", type: "noun", level: "N5" },
    { kanji: "いる", kana: "いる", romaji: "iru", meaning: "perlu", type: "verb-ru", level: "N5" },
    { kanji: "承認印", kana: "しょうにんいん", romaji: "shounin in", meaning: "stempel konfirmasi", type: "noun", level: "N5" },
    { kanji: "事前に", kana: "じぜんに", romaji: "jizen ni", meaning: "sebelumnya", type: "adverb", level: "N5" },
    { kanji: "提出する", kana: "ていしゅつする", romaji: "teishutsu suru", meaning: "menyerahkan", type: "verb-irregular", level: "N5" },
    { kanji: "混んでいる", kana: "こんでいる", romaji: "konde iru", meaning: "macet", type: "verb-irregular", level: "N5" },
    { kanji: "咳", kana: "せき", romaji: "seki", meaning: "batuk", type: "noun", level: "N5" },
    { kanji: "ひどい", kana: "ひどい", romaji: "hidoi", meaning: "parah", type: "adj-i", level: "N5" },
    { kanji: "熱", kana: "ねつ", romaji: "netsu", meaning: "demam", type: "noun", level: "N5" },
    { kanji: "熱がある", kana: "ねつがある", romaji: "netsu ga aru", meaning: "demam", type: "expression", level: "N5" },
    { kanji: "財布", kana: "さいふ", romaji: "saifu", meaning: "dompet", type: "noun", level: "N5" },
    { kanji: "忘れる", kana: "わすれる", romaji: "wasureru", meaning: "lupa", type: "verb-ru", level: "N5" },
    { kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "rumah sakit", type: "noun", level: "N5" },
    { kanji: "家", kana: "いえ", romaji: "ie", meaning: "rumah", type: "noun", level: "N5" },
    { kanji: "帰る", kana: "かえる", romaji: "kaeru", meaning: "pulang", type: "verb-godan", level: "N5" },
    { kanji: "これから", kana: "これから", romaji: "kore kara", meaning: "sekarang; setelah ini", type: "expression", level: "N5" },
    { kanji: "取る", kana: "とる", romaji: "toru", meaning: "mengambil", type: "verb-godan", level: "N5" },
    { kanji: "それで", kana: "それで", romaji: "sore de", meaning: "oleh karena itu", type: "conjunction", level: "N5" },
    { kanji: "遅くなる", kana: "おそくなる", romaji: "osoku naru", meaning: "terlambat", type: "verb-godan", level: "N5" },
    { kanji: "皆さん", kana: "みなさん", romaji: "minasan", meaning: "semua orang", type: "noun", level: "N5" },
    { kanji: "伝える", kana: "つたえる", romaji: "tsutaeru", meaning: "menyampaikan", type: "verb-ru", level: "N5" },
    { kanji: "遅刻する", kana: "ちこくする", romaji: "chikoku suru", meaning: "terlambat", type: "verb-irregular", level: "N5" },
    { kanji: "あとで", kana: "あとで", romaji: "ato de", meaning: "nanti", type: "adverb", level: "N5" },
    { kanji: "休む", kana: "やすむ", romaji: "yasumu", meaning: "cuti; tidak masuk kerja; libur", type: "verb-godan", level: "N5" },
    { kanji: "申し訳ありません", kana: "もうしわけありません", romaji: "moushiwake arimasen", meaning: "Saya mohon maaf.", type: "expression", level: "N5" },
    { kanji: "具合が悪い", kana: "ぐあいがわるい", romaji: "guai ga warui", meaning: "(kondisi tubuh) kurang fit; tidak enak badan", type: "expression", level: "N5" },
    { kanji: "お祈り", kana: "おいのり", romaji: "oinori", meaning: "sembahyang; doa", type: "noun", level: "N5" },
    { kanji: "たばこ", kana: "たばこ", romaji: "tabako", meaning: "rokok", type: "noun", level: "N5" },
    { kanji: "吸う", kana: "すう", romaji: "suu", meaning: "merokok; mengisap (rokok)", type: "verb-godan", level: "N5" },
    { kanji: "行って来る", kana: "いってくる", romaji: "itte kuru", meaning: "pergi (dan kembali lagi ke tempat tersebut setelahnya)", type: "verb-godan", level: "N5" },
    { kanji: "休憩", kana: "きゅうけい", romaji: "kyuukei", meaning: "rehat; istirahat sejenak", type: "noun", level: "N5" },
    { kanji: "戻る", kana: "もどる", romaji: "modoru", meaning: "kembali", type: "verb-godan", level: "N5" },
    { kanji: "早退する", kana: "そうたいする", romaji: "soutai suru", meaning: "pulang lebih awal", type: "verb-irregular", level: "N5" },
    { kanji: "休みを取る", kana: "やすみを とる", romaji: "yasumi o toru", meaning: "mengambil cuti", type: "expression", level: "N5" },
    { kanji: "社長", kana: "しゃちょう", romaji: "shachou", meaning: "direktur utama", type: "noun", level: "N5" },
    { kanji: "役所", kana: "やくしょ", romaji: "yakusho", meaning: "balai kota", type: "noun", level: "N5" },
    { kanji: "早く", kana: "はやく", romaji: "hayaku", meaning: "lebih awal", type: "adverb", level: "N5" },
    { kanji: "用事", kana: "ようじ", romaji: "youji", meaning: "urusan", type: "noun", level: "N5" },
    { kanji: "済む", kana: "すむ", romaji: "sumu", meaning: "selesai", type: "verb-godan", level: "N5" },
    { kanji: "主任", kana: "しゅにん", romaji: "shunin", meaning: "kepala; ketua (staf)", type: "noun", level: "N5" },
    { kanji: "来月", kana: "らいげつ", romaji: "raigetsu", meaning: "bulan depan", type: "noun", level: "N5" },
    { kanji: "できたら", kana: "できたら", romaji: "dekitara", meaning: "kalau memungkinkan; kalau bisa", type: "expression", level: "N5" },
    { kanji: "ちょっと、いいでしょうか?", kana: "ちょっと、いいでしょうか?", romaji: "chotto, ii deshou ka?", meaning: "Maaf, bisa minta waktunya sebentar?", type: "expression", level: "N5" },
    { kanji: "別にかまいません", kana: "べつにかまいません", romaji: "betsu ni kamaimasen", meaning: "Tidak masalah.", type: "expression", level: "N5" },
    { kanji: "休暇届", kana: "きゅうかとどけ", romaji: "kyuuka todoke", meaning: "formulir cuti", type: "noun", level: "N5" },
    { kanji: "出す", kana: "だす", romaji: "dasu", meaning: "mengumpulkan; menyerahkan", type: "verb-godan", level: "N5" },
    { kanji: "フォーム", kana: "フォーム", romaji: "foomu", meaning: "formulir", type: "noun", level: "N5" },
    { kanji: "所属", kana: "しょぞく", romaji: "shozoku", meaning: "tempat kerja; bagian; divisi", type: "noun", level: "N5" },
    { kanji: "チーム", kana: "チーム", romaji: "chiimu", meaning: "tim", type: "noun", level: "N5" },
    { kanji: "症状", kana: "しょうじょう", romaji: "shoujou", meaning: "gejala penyakit", type: "noun", level: "N5" },
    { kanji: "のど", kana: "のど", romaji: "nodo", meaning: "tenggorokan", type: "noun", level: "N5" },
    { kanji: "痛い", kana: "いたい", romaji: "itai", meaning: "sakit", type: "adj-i", level: "N5" },
    { kanji: "お腹", kana: "おなか", romaji: "onaka", meaning: "perut", type: "noun", level: "N5" },
    { kanji: "熱", kana: "ねつ", romaji: "netsu", meaning: "demam", type: "noun", level: "N5" },
    { kanji: "咳", kana: "せき", romaji: "seki", meaning: "batuk", type: "noun", level: "N5" },
    { kanji: "出る", kana: "でる", romaji: "deru", meaning: "keluar; sedang mengalami (batuk / pilek)", type: "verb-ru", level: "N5" },
    { kanji: "鼻水", kana: "はなみず", romaji: "hanamizu", meaning: "ingus (pada saat pilek)", type: "noun", level: "N5" },
    { kanji: "吐き気", kana: "はきけ", romaji: "hakike", meaning: "mual; rasa ingin muntah", type: "noun", level: "N5" },
    { kanji: "吐き気がする", kana: "はきけがする", romaji: "hakike ga suru", meaning: "merasa mual", type: "expression", level: "N5" },
    { kanji: "食欲", kana: "しょくよく", romaji: "shokuyoku", meaning: "nafsu makan", type: "noun", level: "N5" },
    { kanji: "目", kana: "め", romaji: "me", meaning: "mata", type: "noun", level: "N5" },
    { kanji: "かゆい", kana: "かゆい", romaji: "kayui", meaning: "gatal", type: "adj-i", level: "N5" },
    { kanji: "足", kana: "あし", romaji: "ashi", meaning: "kaki", type: "noun", level: "N5" },
    { kanji: "くじく", kana: "くじく", romaji: "kujiku", meaning: "keseleo", type: "verb-godan", level: "N5" },
    { kanji: "頭", kana: "あたま", romaji: "atama", meaning: "kepala", type: "noun", level: "N5" },
    { kanji: "ぶつける", kana: "ぶつける", romaji: "butsukeru", meaning: "terantuk; terbentur; menabrak", type: "verb-ru", level: "N5" },
    { kanji: "おととい", kana: "おととい", romaji: "ototoi", meaning: "kemarin lusa; 2 hari lalu", type: "noun", level: "N5" },
    { kanji: "転ぶ", kana: "ころぶ", romaji: "korobu", meaning: "jatuh", type: "verb-godan", level: "N5" },
    { kanji: "こう", kana: "こう", romaji: "kou", meaning: "begini; seperti ini", type: "adverb", level: "N5" },
    { kanji: "レントゲン", kana: "レントゲン", romaji: "rentogen", meaning: "rontgen", type: "noun", level: "N5" },
    { kanji: "～週間", kana: "～しゅうかん", romaji: "~shuukan", meaning: "～ minggu / pekan", type: "suffix", level: "N5" },
    { kanji: "花粉症", kana: "かふんしょう", romaji: "kafunshou", meaning: "alergi polen (serbuk sari)", type: "noun", level: "N5" },
    { kanji: "どうしましたか?", kana: "どうしましたか?", romaji: "dou shimashita ka?", meaning: "Kenapa?; Ada masalah apa?", type: "expression", level: "N5" },
    { kanji: "どうされましたか?", kana: "どうされましたか?", romaji: "dou saremashita ka?", meaning: "Kenapa?; Ada masalah apa? (ungkapan bentuk sopan)", type: "expression", level: "N5" },
    { kanji: "保険証", kana: "ほけんしょう", romaji: "hokenshou", meaning: "kartu asuransi kesehatan", type: "noun", level: "N5" },
    { kanji: "問診票", kana: "もんしんひょう", romaji: "monshinhyou", meaning: "kuesioner; daftar pertanyaan (seputar pemeriksaan)", type: "noun", level: "N5" },
    { kanji: "薬", kana: "くすり", romaji: "kusuri", meaning: "obat", type: "noun", level: "N5" },
    { kanji: "飲む", kana: "のむ", romaji: "nomu", meaning: "minum (minum obat)", type: "verb-godan", level: "N5" },
    { kanji: "会う", kana: "あう", romaji: "au", meaning: "bertemu", type: "verb-godan", level: "N5" },
    { kanji: "柔らかい", kana: "やわらかい", romaji: "yawarakai", meaning: "empuk; lunak", type: "adj-i", level: "N5" },
    { kanji: "辛い", kana: "からい", romaji: "karai", meaning: "pedas", type: "adj-i", level: "N5" },
    { kanji: "診察券", kana: "しんさつげん", romaji: "shinsatsugen", meaning: "kartu registrasi pasien (pada klinik / rumah sakit)", type: "noun", level: "N5" },
    { kanji: "処方せん", kana: "しょほうせん", romaji: "shohousen", meaning: "resep obat", type: "noun", level: "N5" },
    { kanji: "記入する", kana: "きにゅうする", romaji: "kinyuu suru", meaning: "mengisi", type: "verb-irregular", level: "N5" },
    { kanji: "医者", kana: "いしゃ", romaji: "isha", meaning: "dokter", type: "noun", level: "N5" },
    { kanji: "～度～分", kana: "～ど～ぶ", romaji: "~do ~bu", meaning: "～ derajat", type: "suffix", level: "N5" },
    { kanji: "口", kana: "くち", romaji: "kuchi", meaning: "mulut", type: "noun", level: "N5" },
    { kanji: "インフルエンザ", kana: "インフルエンザ", romaji: "infuruenza", meaning: "influenza", type: "noun", level: "N5" },
    { kanji: "検査する", kana: "けんさする", romaji: "kensa suru", meaning: "memeriksa", type: "verb-irregular", level: "N5" },
    { kanji: "A型", kana: "エーがた", romaji: "ee gata", meaning: "tipe A", type: "noun", level: "N5" },
    { kanji: "下がる", kana: "さがる", romaji: "sagaru", meaning: "turun (demam turun)", type: "verb-godan", level: "N5" },
    { kanji: "おかゆ", kana: "おかゆ", romaji: "okayu", meaning: "bubur nasi", type: "noun", level: "N5" },
    { kanji: "薬局", kana: "やっきょく", romaji: "yakkyoku", meaning: "apotek", type: "noun", level: "N5" },
    { kanji: "もらう", kana: "もらう", romaji: "morau", meaning: "menerima", type: "verb-godan", level: "N5" },
    { kanji: "お大事に", kana: "おだいじに", romaji: "odaiji ni", meaning: "Semoga lekas sembuh.", type: "expression", level: "N5" },
    { kanji: "お持ちですか?", kana: "おもちですか?", romaji: "omochi desu ka?", meaning: "Apakah Anda membawa; mempunyai; memiliki~?", type: "expression", level: "N5" },
    { kanji: "フリガナ", kana: "フリガナ", romaji: "furigana", meaning: "cara baca dalam huruf Hiragana / Katakana", type: "noun", level: "N5" },
    { kanji: "性別", kana: "せいべつ", romaji: "seibetsu", meaning: "jenis kelamin", type: "noun", level: "N5" },
    { kanji: "病気にかかる", kana: "びょうきにかかる", romaji: "byouki ni kakaru", meaning: "menderita penyakit", type: "expression", level: "N5" },
    { kanji: "現在", kana: "げんざい", romaji: "genzai", meaning: "saat ini", type: "noun", level: "N5" },
    { kanji: "女性", kana: "じょせい", romaji: "josei", meaning: "wanita", type: "noun", level: "N5" },
    { kanji: "妊娠する", kana: "にんしんする", romaji: "ninshin suru", meaning: "hamil", type: "verb-irregular", level: "N5" },
    { kanji: "記入例", kana: "きにゅうれい", romaji: "kinyuu rei", meaning: "contoh pengisian", type: "noun", level: "N5" },
    { kanji: "記入日", kana: "きにゅうび", romaji: "kinyuu bi", meaning: "tanggal pengisian", type: "noun", level: "N5" },
    { kanji: "大正", kana: "たいしょう", romaji: "taishou", meaning: "Taisho / T (nama era di Jepang)", type: "noun", level: "N5" },
    { kanji: "昭和", kana: "しょうわ", romaji: "shouwa", meaning: "Showa / S (nama era di Jepang)", type: "noun", level: "N5" },
    { kanji: "平成", kana: "へいせい", romaji: "heisei", meaning: "Heisei / H (nama era di Jepang)", type: "noun", level: "N5" },
    { kanji: "令和", kana: "れいわ", romaji: "reiwa", meaning: "Reiwa / R (nama era di Jepang)", type: "noun", level: "N5" },
    { kanji: "～才", kana: "～さい", romaji: "~sai", meaning: "～ tahun (umur)", type: "suffix", level: "N5" },
    { kanji: "今までに", kana: "いままでに", romaji: "ima made ni", meaning: "sejauh ini; sampai saat ini", type: "adverb", level: "N5" },
    { kanji: "病気", kana: "びょうき", romaji: "byouki", meaning: "sakit; penyakit", type: "noun", level: "N5" },
    { kanji: "病名", kana: "びょうめい", romaji: "byoumei", meaning: "nama penyakit", type: "noun", level: "N5" },
    { kanji: "～本", kana: "～ほん", romaji: "~hon", meaning: "～ botol", type: "suffix", level: "N5" },
    { kanji: "～の方", kana: "～のかた", romaji: "~no kata", meaning: "orang (imbuhan untuk menyatakan orang dalam bentuk sopan)", type: "suffix", level: "N5" },
    { kanji: "答える", kana: "こたえる", romaji: "kotaeru", meaning: "menjawab", type: "verb-ru", level: "N5" },
    { kanji: "～週目", kana: "～しゅうめ", romaji: "~shuu me", meaning: "minggu ke~", type: "suffix", level: "N5" },
    { kanji: "お答えください", kana: "おこたえください", romaji: "okotae kudasai", meaning: "Mohon dijawab.", type: "expression", level: "N5" },
    { kanji: "下げる", kana: "さげる", romaji: "sageru", meaning: "menurunkan (contoh : menurunkan demam)", type: "verb-ru", level: "N5" },
    { kanji: "抑える", kana: "おさえる", romaji: "osaeru", meaning: "meredakan", type: "verb-ru", level: "N5" },
    { kanji: "痛み止め", kana: "いたみどめ", romaji: "itami dome", meaning: "obat penghilang rasa sakit", type: "noun", level: "N5" },
    { kanji: "くしゃみ", kana: "くしゃみ", romaji: "kushami", meaning: "bersin", type: "noun", level: "N5" },
    { kanji: "つらい", kana: "つらい", romaji: "tsurai", meaning: "merasa berat; payah", type: "adj-i", level: "N5" },
    { kanji: "我慢する", kana: "がまんする", romaji: "gaman suru", meaning: "bertahan; menahan diri", type: "verb-irregular", level: "N5" },
    { kanji: "我慢できない", kana: "がまんできない", romaji: "gaman dekinai", meaning: "tidak mampu bertahan; menahan diri", type: "expression", level: "N5" },
    { kanji: "間をあける", kana: "あいだをあける", romaji: "aida o akeru", meaning: "berselang; memberi jarak antar waktu", type: "expression", level: "N5" },
    { kanji: "～以上", kana: "～いじょう", romaji: "~ijou", meaning: "～ atau lebih", type: "suffix", level: "N5" },
    { kanji: "胃", kana: "い", romaji: "i", meaning: "lambung", type: "noun", level: "N5" },
    { kanji: "守る", kana: "まもる", romaji: "mamoru", meaning: "melindungi", type: "verb-godan", level: "N5" },
    { kanji: "運転する", kana: "うんてんする", romaji: "unten suru", meaning: "berkendara; mengemudi", type: "verb-irregular", level: "N5" },
    { kanji: "食後", kana: "しょくご", romaji: "shokugo", meaning: "sesudah makan", type: "noun", level: "N5" },
    { kanji: "眠い", kana: "ねむい", romaji: "nemui", meaning: "mengantuk", type: "adj-i", level: "N5" },
    { kanji: "解熱剤", kana: "げねつざい", romaji: "genetsuzai", meaning: "obat penurun panas / demam", type: "noun", level: "N5" },
    { kanji: "熱が高い", kana: "ねつがたかい", romaji: "netsu ga takai", meaning: "demam tinggi", type: "expression", level: "N5" },
    { kanji: "それと", kana: "それと", romaji: "sore to", meaning: "dan", type: "conjunction", level: "N5" },
    { kanji: "こっち", kana: "こっち", romaji: "kocchi", meaning: "ini; yang ini", type: "noun", level: "N5" },
    { kanji: "夕方", kana: "ゆうがた", romaji: "yuugata", meaning: "sore; sore hari", type: "noun", level: "N5" },
    { kanji: "寝る前", kana: "ねるまえ", romaji: "neru mae", meaning: "sebelum tidur", type: "expression", level: "N5" },
    { kanji: "用法", kana: "ようほう", romaji: "youhou", meaning: "cara penggunaan", type: "noun", level: "N5" },
    { kanji: "用量", kana: "ようりょう", romaji: "youryou", meaning: "dosis", type: "noun", level: "N5" },
    { kanji: "説明書", kana: "せつめいしょ", romaji: "setsumeisho", meaning: "instruksi; deskripsi", type: "noun", level: "N5" },
    { kanji: "効能", kana: "こうのう", romaji: "kounou", meaning: "efek", type: "noun", level: "N5" },
    { kanji: "注意事項", kana: "ちゅういじこう", romaji: "chuui jikou", meaning: "peringatan; catatan", type: "noun", level: "N5" },
    { kanji: "夕食後", kana: "ゆうしょくご", romaji: "yuushokugo", meaning: "sesudah makan malam", type: "noun", level: "N5" },
    { kanji: "～錠", kana: "～じょう", romaji: "~jou", meaning: "～ butir", type: "suffix", level: "N5" },
    { kanji: "～日分", kana: "～にちぶん", romaji: "~nichibun", meaning: "untuk ~ hari", type: "suffix", level: "N5" },
    { kanji: "毎食後", kana: "まいしょくご", romaji: "maishokugo", meaning: "setiap sehabis makan", type: "noun", level: "N5" },
    { kanji: "将来", kana: "しょうらい", romaji: "shourai", meaning: "masa depan", type: "noun", level: "N5" },
    { kanji: "夢", kana: "ゆめ", romaji: "yume", meaning: "mimpi; impian", type: "noun", level: "N5" },
    { kanji: "どんな", kana: "どんな", romaji: "donna", meaning: "seperti apa", type: "adverb", level: "N5" },
    { kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "pekerjaan", type: "noun", level: "N5" },
    { kanji: "したい", kana: "したい", romaji: "shitai", meaning: "ingin melakukan", type: "verb-irregular", level: "N5" },
    { kanji: "会社員", kana: "かいしゃいん", romaji: "kaishain", meaning: "pegawai perusahaan", type: "noun", level: "N5" },
    { kanji: "先生", kana: "せんせい", romaji: "sensei", meaning: "guru", type: "noun", level: "N5" },
    { kanji: "医者", kana: "いしゃ", romaji: "isha", meaning: "dokter", type: "noun", level: "N5" },
    { kanji: "看護師", kana: "かんごし", romaji: "kangoshi", meaning: "perawat", type: "noun", level: "N5" },
    { kanji: "プログラマー", kana: "プログラマー", romaji: "puroguramaa", meaning: "programmer", type: "noun", level: "N5" },
    { kanji: "デザイナー", kana: "デザイナー", romaji: "dezainaa", meaning: "desainer", type: "noun", level: "N5" },
    { kanji: "通訳", kana: "つうやく", romaji: "tsuuyaku", meaning: "penerjemah lisan", type: "noun", level: "N5" },
    { kanji: "翻訳者", kana: "ほんやくしゃ", romaji: "honyakusha", meaning: "penerjemah tulisan", type: "noun", level: "N5" },
    { kanji: "料理人", kana: "りょうりにん", romaji: "ryourinin", meaning: "koki; juru masak", type: "noun", level: "N5" },
    { kanji: "美容師", kana: "びようし", romaji: "biyoushi", meaning: "penata rambut", type: "noun", level: "N5" },
    { kanji: "弁護士", kana: "べんごし", romaji: "bengoshi", meaning: "pengacara", type: "noun", level: "N5" },
    { kanji: "警察官", kana: "けいさつかん", romaji: "keisatsukan", meaning: "polisi", type: "noun", level: "N5" },
    { kanji: "消防士", kana: "しょうぼうし", romaji: "shouboushi", meaning: "pemadam kebakaran", type: "noun", level: "N5" },
    { kanji: "考え中", kana: "かんがえちゅう", romaji: "kangaechuu", meaning: "sedang memikirkan", type: "noun", level: "N5" },
    { kanji: "決まる", kana: "きまる", romaji: "kimaru", meaning: "diputuskan", type: "verb-godan", level: "N5" },
    { kanji: "将来の夢", kana: "しょうらいのゆめ", romaji: "shourai no yume", meaning: "impian masa depan", type: "expression", level: "N5" },
    { kanji: "子ども", kana: "こども", romaji: "kodomo", meaning: "anak", type: "noun", level: "N5" },
    { kanji: "助ける", kana: "たすける", romaji: "tasukeru", meaning: "menolong", type: "verb-ru", level: "N5" },
    { kanji: "人", kana: "ひと", romaji: "hito", meaning: "orang", type: "noun", level: "N5" },
    { kanji: "役に立つ", kana: "やくにたつ", romaji: "yaku ni tatsu", meaning: "berguna", type: "expression", level: "N5" },
    { kanji: "お客様", kana: "おきゃくさま", romaji: "okyakusama", meaning: "pelanggan", type: "noun", level: "N5" },
    { kanji: "喜ぶ", kana: "よろこぶ", romaji: "yorokobu", meaning: "senang; bahagia", type: "verb-godan", level: "N5" },
    { kanji: "嬉しい", kana: "うれしい", romaji: "ureshii", meaning: "senang", type: "adj-i", level: "N5" },
    { kanji: "仕事が好き", kana: "しごとがすき", romaji: "shigoto ga suki", meaning: "suka pekerjaan", type: "expression", level: "N5" },
    { kanji: "国際", kana: "こくさい", romaji: "kokusai", meaning: "internasional", type: "noun", level: "N5" },
    { kanji: "交流", kana: "こうりゅう", romaji: "kouryuu", meaning: "pertukaran", type: "noun", level: "N5" },
    { kanji: "外国語", kana: "がいこくご", romaji: "gaikokugo", meaning: "bahasa asing", type: "noun", level: "N5" },
    { kanji: "話せる", kana: "はなせる", romaji: "hanaseru", meaning: "bisa berbicara", type: "verb-ru", level: "N5" },
    { kanji: "資格", kana: "しかく", romaji: "shikaku", meaning: "kualifikasi", type: "noun", level: "N5" },
    { kanji: "取る", kana: "とる", romaji: "toru", meaning: "mengambil (kualifikasi)", type: "verb-godan", level: "N5" },
    { kanji: "勉強", kana: "べんきょう", romaji: "benkyou", meaning: "belajar", type: "noun", level: "N5" },
    { kanji: "がんばる", kana: "がんばる", romaji: "ganbaru", meaning: "berusaha semaksimal mungkin", type: "verb-godan", level: "N5" },
    { kanji: "交通事故", kana: "こうつうじこ", romaji: "koutsuu jiko", meaning: "kecelakaan lalu lintas", type: "noun", level: "N5" },
    { kanji: "怪我", kana: "けが", romaji: "kega", meaning: "luka; cedera", type: "noun", level: "N5" },
    { kanji: "する", kana: "する", romaji: "suru", meaning: "melakukan", type: "verb-irregular", level: "N5" },
    { kanji: "出血", kana: "しゅっけつ", romaji: "shukketsu", meaning: "berdarah", type: "noun", level: "N5" },
    { kanji: "救急車", kana: "きゅうきゅうしゃ", romaji: "kyuukyuusha", meaning: "ambulans", type: "noun", level: "N5" },
    { kanji: "呼ぶ", kana: "よぶ", romaji: "yobu", meaning: "memanggil", type: "verb-godan", level: "N5" },
    { kanji: "意識", kana: "いしき", romaji: "ishiki", meaning: "kesadaran", type: "noun", level: "N5" },
    { kanji: "ない", kana: "ない", romaji: "nai", meaning: "tidak ada", type: "adj-i", level: "N5" },
    { kanji: "止まる", kana: "とまる", romaji: "tomaru", meaning: "berhenti", type: "verb-godan", level: "N5" },
    { kanji: "息", kana: "いき", romaji: "iki", meaning: "napas", type: "noun", level: "N5" },
    { kanji: "する", kana: "する", romaji: "suru", meaning: "melakukan (pernapasan buatan)", type: "verb-irregular", level: "N5" },
    { kanji: "胸", kana: "むね", romaji: "mune", meaning: "dada", type: "noun", level: "N5" },
    { kanji: "押す", kana: "おす", romaji: "osu", meaning: "menekan (pijat jantung)", type: "verb-godan", level: "N5" },
    { kanji: "出血", kana: "しゅっけつ", romaji: "shukketsu", meaning: "pendarahan", type: "noun", level: "N5" },
    { kanji: "止める", kana: "とめる", romaji: "tomeru", meaning: "menghentikan", type: "verb-ru", level: "N5" },
    { kanji: "消毒", kana: "しょうどく", romaji: "shoudoku", meaning: "membersihkan luka", type: "noun", level: "N5" },
    { kanji: "包帯", kana: "ほうたい", romaji: "houtai", meaning: "perban", type: "noun", level: "N5" },
    { kanji: "巻く", kana: "まく", romaji: "maku", meaning: "melilitkan (perban)", type: "verb-godan", level: "N5" },
    { kanji: "固定する", kana: "こていする", romaji: "kotei suru", meaning: "memperbaiki posisi; memfiksasi", type: "verb-irregular", level: "N5" },
    { kanji: "担架", kana: "たんか", romaji: "tanka", meaning: "tandu", type: "noun", level: "N5" },
    { kanji: "運ぶ", kana: "はこぶ", romaji: "hakobu", meaning: "mengangkut", type: "verb-godan", level: "N5" },
    { kanji: "AED", kana: "エーイーディー", romaji: "ee ii dii", meaning: "alat kejut jantung otomatis", type: "noun", level: "N5" },
    { kanji: "使う", kana: "つかう", romaji: "tsukau", meaning: "menggunakan", type: "verb-godan", level: "N5" },
    { kanji: "意識がない", kana: "いしきがない", romaji: "ishiki ga nai", meaning: "tidak sadarkan diri", type: "expression", level: "N5" },
    { kanji: "出血", kana: "しゅっけつ", romaji: "shukketsu", meaning: "pendarahan", type: "noun", level: "N5" },
    { kanji: "怪我", kana: "けが", romaji: "kega", meaning: "cedera", type: "noun", level: "N5" },
    { kanji: "骨折", kana: "こっせつ", romaji: "kossetsu", meaning: "patah tulang", type: "noun", level: "N5" },
    { kanji: "やけど", kana: "やけど", romaji: "yakedo", meaning: "luka bakar", type: "noun", level: "N5" },
    { kanji: "119番", kana: "ひゃくじゅうきゅうばん", romaji: "hyakujuukyuuban", meaning: "nomor darurat 119 (untuk pemadam kebakaran dan ambulans di Jepang)", type: "noun", level: "N5" },
    { kanji: "110番", kana: "ひゃくとうばん", romaji: "hyakutouban", meaning: "nomor darurat 110 (untuk polisi di Jepang)", type: "noun", level: "N5" },
    { kanji: "救急車", kana: "きゅうきゅうしゃ", romaji: "kyuukyuusha", meaning: "ambulans", type: "noun", level: "N5" },
    { kanji: "火事", kana: "かじ", romaji: "kaji", meaning: "kebakaran", type: "noun", level: "N5" },
    { kanji: "急病", kana: "きゅうびょう", romaji: "kyuubyou", meaning: "penyakit mendadak", type: "noun", level: "N5" },
    { kanji: "意識を失う", kana: "いしきをうしなう", romaji: "ishiki o ushinau", meaning: "hilang kesadaran", type: "expression", level: "N5" },
    { kanji: "心臓マッサージ", kana: "しんぞうマッサージ", romaji: "shinzou massaaji", meaning: "pijat jantung", type: "noun", level: "N5" },
    { kanji: "人工呼吸", kana: "じんこうこきゅう", romaji: "jinkou kokyuu", meaning: "pernapasan buatan", type: "noun", level: "N5" },
    { kanji: "傷口", kana: "きずぐち", romaji: "kizuguchi", meaning: "luka", type: "noun", level: "N5" },
    { kanji: "冷やす", kana: "ひやす", romaji: "hiyasu", meaning: "mendinginkan", type: "verb-godan", level: "N5" },
    { kanji: "止血", kana: "しけつ", romaji: "shiketsu", meaning: "menghentikan pendarahan", type: "noun", level: "N5" },
    { kanji: "三角巾", kana: "さんかくいん", romaji: "sankakuin", meaning: "perban segitiga", type: "noun", level: "N5" },
    { kanji: "旅行", kana: "りょこう", romaji: "ryokou", meaning: "perjalanan; wisata", type: "noun", level: "N5" },
    { kanji: "どこか", kana: "どこか", romaji: "dokoka", meaning: "suatu tempat", type: "noun", level: "N5" },
    { kanji: "行きたい", kana: "いきたい", romaji: "ikitai", meaning: "ingin pergi", type: "verb-irregular", level: "N5" },
    { kanji: "温泉", kana: "おんせん", romaji: "onsen", meaning: "pemandian air panas", type: "noun", level: "N5" },
    { kanji: "沖縄", kana: "おきなわ", romaji: "okinawa", meaning: "Okinawa", type: "noun", level: "N5" },
    { kanji: "北海道", kana: "ほっかいどう", romaji: "hokkaidou", meaning: "Hokkaido", type: "noun", level: "N5" },
    { kanji: "京都", kana: "きょうと", romaji: "kyouto", meaning: "Kyoto", type: "noun", level: "N5" },
    { kanji: "富士山", kana: "ふじさん", romaji: "fujisan", meaning: "Gunung Fuji", type: "noun", level: "N5" },
    { kanji: "海外", kana: "かいがい", romaji: "kaigai", meaning: "luar negeri", type: "noun", level: "N5" },
    { kanji: "行ったことがある", kana: "いったことがある", romaji: "itta koto ga aru", meaning: "pernah pergi", type: "expression", level: "N5" },
    { kanji: "気持ちいい", kana: "きもちいい", romaji: "kimochiii", meaning: "enak; nyaman", type: "adj-i", level: "N5" },
    { kanji: "リラックスする", kana: "リラックスする", romaji: "rirakkusu suru", meaning: "rileks; santai", type: "verb-irregular", level: "N5" },
    { kanji: "きれい", kana: "きれい", romaji: "kirei", meaning: "indah", type: "adj-na", level: "N5" },
    { kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "berenang", type: "verb-godan", level: "N5" },
    { kanji: "スキー", kana: "スキー", romaji: "sukii", meaning: "ski", type: "noun", level: "N5" },
    { kanji: "する", kana: "する", romaji: "suru", meaning: "melakukan", type: "verb-irregular", level: "N5" },
    { kanji: "お寺", kana: "おてら", romaji: "otera", meaning: "kuil Buddha", type: "noun", level: "N5" },
    { kanji: "神社", kana: "じんじゃ", romaji: "jinja", meaning: "kuil Shinto", type: "noun", level: "N5" },
    { kanji: "見る", kana: "みる", romaji: "miru", meaning: "melihat", type: "verb-ru", level: "N5" },
    { kanji: "登山する", kana: "とざんする", romaji: "tozan suru", meaning: "mendaki gunung", type: "verb-irregular", level: "N5" },
    { kanji: "気持ちいい", kana: "きもちいい", romaji: "kimochiii", meaning: "menyegarkan", type: "adj-i", level: "N5" },
    { kanji: "世界遺産", kana: "せかいいさん", romaji: "sekai isan", meaning: "warisan dunia", type: "noun", level: "N5" },
    { kanji: "行ってみる", kana: "いってみる", romaji: "itte miru", meaning: "mencoba pergi", type: "verb-godan", level: "N5" },
    { kanji: "おすすめ", kana: "おすすめ", romaji: "osusume", meaning: "rekomendasi", type: "noun", level: "N5" },
    { kanji: "海外旅行", kana: "かいがいりょこう", romaji: "kaigai ryokou", meaning: "perjalanan luar negeri", type: "noun", level: "N5" },
    { kanji: "初めて", kana: "はじめて", romaji: "hajimete", meaning: "pertama kali", type: "adverb", level: "N5" },
    { kanji: "楽しみ", kana: "たのしみ", romaji: "tanoshimi", meaning: "kesenangan; dinanti-nanti", type: "noun", level: "N5" },
    { kanji: "旅行する", kana: "りょこうする", romaji: "ryokou suru", meaning: "berwisata", type: "verb-irregular", level: "N5" },
    { kanji: "飛行機", kana: "ひこうき", romaji: "hikouki", meaning: "pesawat terbang", type: "noun", level: "N5" },
    { kanji: "新幹線", kana: "しんかんせん", romaji: "shinkansen", meaning: "kereta cepat", type: "noun", level: "N5" },
    { kanji: "船", kana: "ふね", romaji: "fune", meaning: "kapal", type: "noun", level: "N5" },
    { kanji: "バス", kana: "バス", romaji: "basu", meaning: "bus", type: "noun", level: "N5" },
    { kanji: "電車", kana: "でんしゃ", romaji: "densha", meaning: "kereta listrik", type: "noun", level: "N5" },
    { kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "mobil", type: "noun", level: "N5" },
    { kanji: "自転車", kana: "じてんしゃ", romaji: "jitensha", meaning: "sepeda", type: "noun", level: "N5" },
    { kanji: "歩いて", kana: "あるいて", romaji: "aruite", meaning: "dengan berjalan kaki", type: "adverb", level: "N5" },
    { kanji: "観光", kana: "かんこう", romaji: "kankou", meaning: "wisata", type: "noun", level: "N5" },
    { kanji: "目的", kana: "もくてき", romaji: "mokuteki", meaning: "tujuan", type: "noun", level: "N5" },
    { kanji: "のんびりする", kana: "のんびりする", romaji: "nonbiri suru", meaning: "bersantai", type: "verb-irregular", level: "N5" },
    { kanji: "冒険", kana: "ぼうけん", romaji: "bouken", meaning: "petualangan", type: "noun", level: "N5" },
    { kanji: "自然", kana: "しぜん", romaji: "shizen", meaning: "alam", type: "noun", level: "N5" },
    { kanji: "楽しむ", kana: "たのしむ", romaji: "tanoshimu", meaning: "menikmati", type: "verb-godan", level: "N5" },
    { kanji: "文化", kana: "ぶんか", romaji: "bunka", meaning: "budaya", type: "noun", level: "N5" },
    { kanji: "体験する", kana: "たいけんする", romaji: "taiken suru", meaning: "mengalami", type: "verb-irregular", level: "N5" },
    { kanji: "食べ物", kana: "たべもの", romaji: "tabemono", meaning: "makanan", type: "noun", level: "N5" },
    { kanji: "試す", kana: "ためす", romaji: "tamesu", meaning: "mencoba", type: "verb-godan", level: "N5" },
    { kanji: "お土産", kana: "おみやげ", romaji: "omiyage", meaning: "oleh-oleh", type: "noun", level: "N5" },
    { kanji: "買う", kana: "かう", romaji: "kau", meaning: "membeli", type: "verb-godan", level: "N5" }
  ]
