const vocabularyData = [
  // === Godan Verbs (u-ending) ===
  { kanji: "歩く", kana: "あるく", romaji: "aruku", meaning: "berjalan", type: "verb-godan", level: "N5" },
  { kanji: "洗う", kana: "あらう", romaji: "arau", meaning: "mencuci", type: "verb-godan", level: "N5" },
  { kanji: "ある", kana: "ある", romaji: "aru", meaning: "ada (benda)", type: "verb-godan", level: "N5" },
  { kanji: "遊ぶ", kana: "あそぶ", romaji: "asobu", meaning: "bermain", type: "verb-godan", level: "N5" },
  { kanji: "会う", kana: "あう", romaji: "au", meaning: "bertemu", type: "verb-godan", level: "N5" },
  { kanji: "買う", kana: "かう", romaji: "kau", meaning: "membeli", type: "verb-godan", level: "N5" },
  { kanji: "書く", kana: "かく", romaji: "kaku", meaning: "menulis", type: "verb-godan", level: "N5" },
  { kanji: "帰る", kana: "かえる", romaji: "kaeru", meaning: "pulang", type: "verb-godan", level: "N5" },
  { kanji: "掛かる", kana: "かかる", romaji: "kakaru", meaning: "memakan waktu/biaya", type: "verb-godan", level: "N5" },
  { kanji: "借りる", kana: "かりる", romaji: "kariru", meaning: "meminjam", type: "verb-godan", level: "N5" },
  { kanji: "貸す", kana: "かす", romaji: "kasu", meaning: "meminjamkan", type: "verb-godan", level: "N5" },
  { kanji: "話す", kana: "はなす", romaji: "hanasu", meaning: "berbicara", type: "verb-godan", level: "N5" },
  { kanji: "待つ", kana: "まつ", romaji: "matsu", meaning: "menunggu", type: "verb-godan", level: "N5" },
  { kanji: "分かる", kana: "わかる", romaji: "wakaru", meaning: "mengerti", type: "verb-godan", level: "N5" },
  { kanji: "違う", kana: "ちがう", romaji: "chigau", meaning: "berbeda", type: "verb-godan", level: "N5" },
  { kanji: "切る", kana: "きる", romaji: "kiru", meaning: "memotong", type: "verb-godan", level: "N5" },
  { kanji: "作る", kana: "つくる", romaji: "tsukuru", meaning: "membuat", type: "verb-godan", level: "N5" },
  { kanji: "持つ", kana: "もつ", romaji: "motsu", meaning: "memegang", type: "verb-godan", level: "N5" },
  { kanji: "取る", kana: "とる", romaji: "toru", meaning: "mengambil", type: "verb-godan", level: "N5" },
  { kanji: "入る", kana: "はいる", romaji: "hairu", meaning: "masuk", type: "verb-godan", level: "N5" },
  { kanji: "始まる", kana: "はじまる", romaji: "hajimaru", meaning: "dimulai", type: "verb-godan", level: "N5" },
  { kanji: "走る", kana: "はしる", romaji: "hashiru", meaning: "berlari", type: "verb-godan", level: "N5" },
  { kanji: "働く", kana: "はたらく", romaji: "hataraku", meaning: "bekerja", type: "verb-godan", level: "N5" },
  { kanji: "使う", kana: "つかう", romaji: "tsukau", meaning: "menggunakan", type: "verb-godan", level: "N5" },
  { kanji: "言う", kana: "いう", romaji: "iu", meaning: "mengatakan", type: "verb-godan", level: "N5" },

  // === Ichidan Verbs (eru/iru-ending) ===
  { kanji: "食べる", kana: "たべる", romaji: "taberu", meaning: "makan", type: "verb-ru", level: "N5" },
  { kanji: "寝る", kana: "ねる", romaji: "neru", meaning: "tidur", type: "verb-ru", level: "N5" },
  { kanji: "見る", kana: "みる", romaji: "miru", meaning: "melihat/menonton", type: "verb-ru", level: "N5" },
  { kanji: "開ける", kana: "あける", romaji: "akeru", meaning: "membuka", type: "verb-ru", level: "N5" },
  { kanji: "教える", kana: "おしえる", romaji: "oshieru", meaning: "mengajar", type: "verb-ru", level: "N5" },
  { kanji: "忘れる", kana: "わすれる", romaji: "wasureru", meaning: "lupa", type: "verb-ru", level: "N5" },
  { kanji: "出る", kana: "でる", romaji: "deru", meaning: "keluar", type: "verb-ru", level: "N5" },
  { kanji: "着る", kana: "きる", romaji: "kiru", meaning: "memakai (pakaian)", type: "verb-ru", level: "N5" },
  { kanji: "起きる", kana: "おきる", romaji: "okiru", meaning: "bangun", type: "verb-ru", level: "N5" },
  { kanji: "降りる", kana: "おりる", romaji: "oriru", meaning: "turun", type: "verb-ru", level: "N5" },

  // === Irregular Verbs ===
  { kanji: "する", kana: "する", romaji: "suru", meaning: "melakukan", type: "verb-irregular", level: "N5" },
  { kanji: "勉強する", kana: "べんきょうする", romaji: "benkyou suru", meaning: "belajar", type: "verb-irregular", level: "N5" },
  { kanji: "来る", kana: "くる", romaji: "kuru", meaning: "datang", type: "verb-irregular", level: "N5" },

  // === Adj-i ===
  { kanji: "大きい", kana: "おおきい", romaji: "ookii", meaning: "besar", type: "adj-i", level: "N5" },
  { kanji: "小さい", kana: "ちいさい", romaji: "chiisai", meaning: "kecil", type: "adj-i", level: "N5" },
  { kanji: "新しい", kana: "あたらしい", romaji: "atarashii", meaning: "baru", type: "adj-i", level: "N5" },
  { kanji: "古い", kana: "ふるい", romaji: "furui", meaning: "lama/tua", type: "adj-i", level: "N5" },
  { kanji: "いい", kana: "いい", romaji: "ii", meaning: "baik", type: "adj-i", level: "N5" },
  { kanji: "悪い", kana: "わるい", romaji: "warui", meaning: "buruk", type: "adj-i", level: "N5" },
  { kanji: "熱い", kana: "あつい", romaji: "atsui", meaning: "panas (sentuh)", type: "adj-i", level: "N5" },
  { kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "dingin (cuaca)", type: "adj-i", level: "N5" },
  { kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "dingin (sentuh)", type: "adj-i", level: "N5" },
  { kanji: "難しい", kana: "むずかしい", romaji: "muzukashii", meaning: "sulit", type: "adj-i", level: "N5" },
  { kanji: "易しい", kana: "やさしい", romaji: "yasashii", meaning: "mudah/ramah", type: "adj-i", level: "N5" },
  { kanji: "高い", kana: "たかい", romaji: "takai", meaning: "tinggi/mahal", type: "adj-i", level: "N5" },
  { kanji: "安い", kana: "やすい", romaji: "yasui", meaning: "murah", type: "adj-i", level: "N5" },
  { kanji: "低い", kana: "ひくい", romaji: "hikui", meaning: "rendah", type: "adj-i", level: "N5" },
  { kanji: "面白い", kana: "おもしろい", romaji: "omoshiroi", meaning: "menarik", type: "adj-i", level: "N5" },
  { kanji: "美味しい", kana: "おいしい", romaji: "oishii", meaning: "enak", type: "adj-i", level: "N5" },
  { kanji: "忙しい", kana: "いそがしい", romaji: "isogashii", meaning: "sibuk", type: "adj-i", level: "N5" },
  { kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "senang", type: "adj-i", level: "N5" },

  // === Adj-na ===
  { kanji: "好き", kana: "すき", romaji: "suki", meaning: "suka", type: "adj-na", level: "N5" },
  { kanji: "嫌い", kana: "きらい", romaji: "kirai", meaning: "tidak suka", type: "adj-na", level: "N5" },
  { kanji: "上手", kana: "じょうず", romaji: "jouzu", meaning: "pandai", type: "adj-na", level: "N5" },
  { kanji: "下手", kana: "へた", romaji: "heta", meaning: "tidak pandai", type: "adj-na", level: "N5" },
  { kanji: "有名", kana: "ゆうめい", romaji: "yuumei", meaning: "terkenal", type: "adj-na", level: "N5" },
  { kanji: "大切", kana: "たいせつ", romaji: "taisetsu", meaning: "penting", type: "adj-na", level: "N5" },
  { kanji: "静か", kana: "しずか", romaji: "shizuka", meaning: "tenang", type: "adj-na", level: "N5" },
  { kanji: "きれい", kana: "きれい", romaji: "kirei", meaning: "cantik/bersih", type: "adj-na", level: "N5" },
  { kanji: "親切", kana: "しんせつ", romaji: "shinsetsu", meaning: "ramah", type: "adj-na", level: "N5" },

  // === Noun (contoh saja, tambah sesuai kebutuhan) ===
  { kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "ikan", type: "noun", level: "N5" },
  { kanji: "肉", kana: "にく", romaji: "niku", meaning: "daging", type: "noun", level: "N5" },
  { kanji: "卵", kana: "たまご", romaji: "tamago", meaning: "telur", type: "noun", level: "N5" },
  { kanji: "水", kana: "みず", romaji: "mizu", meaning: "air", type: "noun", level: "N5" },
  { kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "sekolah", type: "noun", level: "N5" },
  { kanji: "先生", kana: "せんせい", romaji: "sensei", meaning: "guru", type: "noun", level: "N5" },
  { kanji: "友達", kana: "ともだち", romaji: "tomodachi", meaning: "teman", type: "noun", level: "N5" },
  { kanji: "本", kana: "ほん", romaji: "hon", meaning: "buku", type: "noun", level: "N5" },

  // === Counter ===
  { kanji: "一つ", kana: "ひとつ", romaji: "hitotsu", meaning: "satu (benda umum)", type: "counter", level: "N5" },
  { kanji: "二人", kana: "ふたり", romaji: "futari", meaning: "dua orang", type: "counter", level: "N5" },
  { kanji: "何人", kana: "なんにん", romaji: "nannin", meaning: "berapa orang", type: "counter", level: "N5" },
  { kanji: "何時", kana: "なんじ", romaji: "nanji", meaning: "jam berapa", type: "counter", level: "N5" },
  { kanji: "一本", kana: "いっぽん", romaji: "ippon", meaning: "satu (benda panjang)", type: "counter", level: "N5" },
  { kanji: "一枚", kana: "いちまい", romaji: "ichimai", meaning: "satu (benda datar)", type: "counter", level: "N5" }
];

const patternData = {
  N5: [
    { pattern: "です", example: "私は学生です。", meaning: "Adalah." },
    { pattern: "ます", example: "私は毎日勉強します。", meaning: "Bentuk sopan." },
    { pattern: "ません", example: "私はコーヒーを飲みません。", meaning: "Bentuk negatif sopan." },
    { pattern: "でした", example: "昨日は暑かったです。", meaning: "Bentuk lampau." },
    { pattern: "ではありません", example: "これは本ではありません。", meaning: "Bukan." },
    { pattern: "か", example: "これは何ですか？", meaning: "Pertanyaan." },
    { pattern: "も", example: "私も学生です。", meaning: "Juga." },
    { pattern: "～の", example: "これは日本の車です。", meaning: "Kepemilikan/keterangan noun." },
    { pattern: "～を", example: "私はパンを食べます。", meaning: "Penanda objek langsung." },
    { pattern: "～に", example: "7時に起きます。", meaning: "Penanda waktu/tujuan keberadaan." },
    { pattern: "～で", example: "図書館で勉強します。", meaning: "Penanda tempat kegiatan/alat." },
    { pattern: "～へ", example: "日本へ行きます。", meaning: "Arah/tujuan." },
    { pattern: "～から～まで", example: "9時から5時まで働きます。", meaning: "Dari sampai." },
    { pattern: "～と", example: "友達と映画を見ます。", meaning: "Bersama/dengan." },
    { pattern: "～や～など", example: "机の上に本やノートなどがあります。", meaning: "Daftar tidak lengkap." },
    { pattern: "～がほしい", example: "新しい辞書がほしいです。", meaning: "Ingin benda." },
    { pattern: "～たい", example: "日本へ行きたいです。", meaning: "Ingin melakukan sesuatu." },
    { pattern: "～ませんか", example: "いっしょに昼ご飯を食べませんか。", meaning: "Ajakan halus." },
    { pattern: "～ましょう", example: "少し休みましょう。", meaning: "Mari kita..." },
    { pattern: "～てください", example: "ここに名前を書いてください。", meaning: "Permintaan sopan." },
    { pattern: "～てもいいです", example: "ここで写真を撮ってもいいです。", meaning: "Izin melakukan sesuatu." },
    { pattern: "～てはいけません", example: "ここでタバコを吸ってはいけません。", meaning: "Larangan." },
    { pattern: "～ています", example: "今、雨が降っています。", meaning: "Sedang berlangsung/keadaan." },
    { pattern: "～に行きます", example: "友達と買い物に行きます。", meaning: "Pergi untuk melakukan V-masu stem." },
    { pattern: "～たことがあります", example: "富士山に登ったことがあります。", meaning: "Pernah mengalami." },
    { pattern: "～たり～たりします", example: "日曜日は掃除をしたり、音楽を聞いたりします。", meaning: "Contoh aktivitas yang dilakukan." },
    { pattern: "～くて / ～で", example: "この店は安くておいしいです。", meaning: "Menggabung sifat/kalimat." },
    { pattern: "～から", example: "今日は寒いですから、コートを着ます。", meaning: "Alasan/sebab." },
    { pattern: "～ので", example: "用事があるので、先に帰ります。", meaning: "Alasan lebih lembut." },
    { pattern: "～と思います", example: "明日は晴れると思います。", meaning: "Menyatakan pendapat." },
    { pattern: "～つもりです", example: "来年、日本へ留学するつもりです。", meaning: "Rencana/niat." },
    { pattern: "～前に", example: "寝る前に歯を磨きます。", meaning: "Sebelum." },
    { pattern: "～後で", example: "仕事の後で買い物します。", meaning: "Sesudah." }
  ],
  N4: [
    { pattern: "～ながら", example: "彼はテレビを見ながらコーヒーを飲みます。", meaning: "Melakukan dua aktivitas bersamaan." },
    { pattern: "～てしまう", example: "宿題を忘れてしまいました。", meaning: "Selesai sepenuhnya/penyesalan." },
    { pattern: "～ておく", example: "旅行の前にホテルを予約しておきます。", meaning: "Persiapan sebelumnya." },
    { pattern: "～てみる", example: "この漢字を使ってみてください。", meaning: "Mencoba melakukan sesuatu." },
    { pattern: "～てくる", example: "ちょっと水を買ってきます。", meaning: "Pergi lalu kembali/muncul perubahan." },
    { pattern: "～ていく", example: "これから日本語をもっと勉強していきます。", meaning: "Perubahan berlanjut ke depan." },
    { pattern: "～ようになる", example: "日本語のニュースが少し分かるようになりました。", meaning: "Menjadi bisa/terjadi perubahan kemampuan." },
    { pattern: "～ことになる", example: "来月大阪へ転勤することになりました。", meaning: "Keputusan yang ditetapkan." },
    { pattern: "～ことにする", example: "健康のために毎日歩くことにします。", meaning: "Memutuskan sendiri." },
    { pattern: "～なければならない", example: "明日までにレポートを出さなければなりません。", meaning: "Harus." },
    { pattern: "～なくてもいい", example: "今日は残業しなくてもいいです。", meaning: "Tidak perlu." },
    { pattern: "～ば", example: "時間があれば、映画を見に行きます。", meaning: "Pengandaian jika." },
    { pattern: "～たら", example: "駅に着いたら、電話してください。", meaning: "Jika/ketika kondisi tercapai." },
    { pattern: "～なら", example: "日本へ行くなら、春がいいですよ。", meaning: "Kalau mengenai..., maka..." },
    { pattern: "～のに", example: "薬を飲んだのに、まだ痛いです。", meaning: "Berlawanan dengan harapan." },
    { pattern: "～ので", example: "電車が遅れたので、会議に遅れました。", meaning: "Sebab/alasan." },
    { pattern: "～ために", example: "日本で働くために、日本語を勉強しています。", meaning: "Untuk tujuan/karena." },
    { pattern: "～ように", example: "忘れないように、メモしてください。", meaning: "Agar/supaya." },
    { pattern: "～しか～ない", example: "財布に千円しかありません。", meaning: "Hanya ... saja." },
    { pattern: "～ばかり", example: "この店は外国人ばかりですね。", meaning: "Kebanyakan/baru saja." },
    { pattern: "～そうです（様態）", example: "このケーキはおいしそうです。", meaning: "Terlihat seperti." },
    { pattern: "～そうです（伝聞）", example: "天気予報によると、明日は雨だそうです。", meaning: "Katanya/menurut informasi." },
    { pattern: "～らしい", example: "彼は日本語が上手らしいです。", meaning: "Sepertinya (berdasar informasi)." },
    { pattern: "～ようだ", example: "外は静かなようです。", meaning: "Tampaknya/seperti." },
    { pattern: "～だろう / ～でしょう", example: "明日はたぶん暑いでしょう。", meaning: "Dugaan." },
    { pattern: "～てあげる", example: "私は友達に日本語を教えてあげます。", meaning: "Memberi manfaat ke orang lain." },
    { pattern: "～てもらう", example: "私は先生に作文を直してもらいました。", meaning: "Menerima bantuan." },
    { pattern: "～てくれる", example: "友達が駅まで迎えに来てくれました。", meaning: "Orang lain memberi manfaat ke saya." },
    { pattern: "～間に", example: "子どもが寝ている間に、掃除をします。", meaning: "Selama rentang waktu." },
    { pattern: "～ところです", example: "今から食事するところです。", meaning: "Tepat sebelum/saat/sesudah melakukan." }
  ]
};
