const vocabularyData = [
  { level: "N5", type: "verb-godan", kanji: "有る", kana: "ある", romaji: "aru", meaning: "ada" },
  { level: "N4", type: "verb-godan", kanji: "居る", kana: "おる", romaji: "oru", meaning: "ada" },
  { level: "N3", type: "verb-godan", kanji: "学ぶ", kana: "まなぶ", romaji: "manabu", meaning: "belajar" },
  { level: "N4", type: "verb-godan", kanji: "話し合う", kana: "はなしあう", romaji: "hanashiau", meaning: "berbincang-bincang" },
  { level: "N4", type: "verb-godan", kanji: "組む", kana: "くむ", romaji: "kumu", meaning: "berpasangan" },
  { level: "N5", type: "verb-godan", kanji: "思う", kana: "おもう", romaji: "omou", meaning: "berpikir" },
  { level: "N4", type: "verb-godan", kanji: "悲しむ", kana: "かなしむ", romaji: "kanashimu", meaning: "bersedih" },
  { level: "N3", type: "verb-godan", kanji: "輝く", kana: "かがやく", romaji: "kagayaku", meaning: "bersinar" },
  { level: "N3", type: "verb-godan", kanji: "悩む", kana: "なやむ", romaji: "nayamu", meaning: "bersusah hati" },
  { level: "N4", type: "verb-godan", kanji: "伺う", kana: "うかがう", romaji: "ukagau", meaning: "bertanya" },
  { level: "N3", type: "verb-godan", kanji: "戦う", kana: "たたかう", romaji: "tatakau", meaning: "bertarung" },
  { level: "N4", type: "verb-godan", kanji: "出会う", kana: "であう", romaji: "bertemu", meaning: "bertemu" },
  { level: "N4", type: "verb-godan", kanji: "叫ぶ", kana: "さけぶ", romaji: "sakebu", meaning: "berteriak" },
  { level: "N3", type: "verb-godan", kanji: "適する", kana: "てきする", romaji: "tekisuru", meaning: "cocok" },
  { level: "N4", type: "verb-godan", kanji: "似合う", kana: "にあう", romaji: "niau", meaning: "cocok, sesuai" },
  { level: "N3", type: "verb-godan", kanji: "効く", kana: "きく", romaji: "kiku", meaning: "efektif" },
  { level: "N3", type: "verb-godan", kanji: "好む", kana: "このむ", romaji: "konomu", meaning: "gemar, menyukai" },
  { level: "N4", type: "verb-godan", kanji: "騒ぐ", kana: "さわぐ", romaji: "sawagu", meaning: "gempar" },
  { level: "N4", type: "verb-godan", kanji: "暮らす", kana: "くらす", romaji: "kurasu", meaning: "hidup" },
  { level: "N3", type: "verb-godan", kanji: "劣る", kana: "おとる", romaji: "otoru", meaning: "kalah" },
  { level: "N5", type: "verb-godan", kanji: "失う", kana: "うしなう", romaji: "ushinau", meaning: "kehilangan" },
  { level: "N4", type: "verb-godan", kanji: "当たる", kana: "あたる", romaji: "ataru", meaning: "kena" },
  { level: "N5", type: "verb-godan", kanji: "食う", kana: "くう", romaji: "kuu", meaning: "makan" },
  { level: "N4", type: "verb-godan", kanji: "抜く", kana: "ぬく", romaji: "nuku", meaning: "melepas" },
  { level: "N4", type: "verb-godan", kanji: "放す", kana: "はなす", romaji: "hanasu", meaning: "melepas" },
  { level: "N4", type: "verb-godan", kanji: "外す", kana: "はずす", romaji: "hazusu", meaning: "melepaskan, menghilangkan" },
  { level: "N4", type: "verb-godan", kanji: "守る", kana: "まもる", romaji: "mamoru", meaning: "melindungi" },
  { level: "N3", type: "verb-godan", kanji: "横切る", kana: "よこぎる", romaji: "yokogiru", meaning: "melintasi" },
  { level: "N3", type: "verb-godan", kanji: "含む", kana: "ふくむ", romaji: "fukumu", meaning: "meliputi, mengandung" },
  { level: "N4", type: "verb-godan", kanji: "飛び出す", kana: "とびだす", romaji: "tobidasu", meaning: "melompat" },
  { level: "N3", type: "verb-godan", kanji: "広がる", kana: "ひろがる", romaji: "hirogaru", meaning: "meluas, melebar, menjalar" },
  { level: "N5", type: "verb-godan", kanji: "描く", kana: "かく", romaji: "kaku", meaning: "melukis/menggambar" },
  { level: "N4", type: "verb-godan", kanji: "許す", kana: "ゆるす", romaji: "yurusu", meaning: "memaafkan" },
  { level: "N5", type: "verb-godan", kanji: "被る", kana: "かぶる", romaji: "kaburu", meaning: "memakai (untuk dikepala)" },
  { level: "N3", type: "verb-godan", kanji: "刈る", kana: "かる", romaji: "karu", meaning: "memangkas" },
  { level: "N4", type: "verb-godan", kanji: "割る", kana: "わる", romaji: "waru", meaning: "membagi" },
  { level: "N4", type: "verb-godan", kanji: "限る", kana: "かぎる", romaji: "kagiru", meaning: "membatasi" },
  { level: "N5", type: "verb-godan", kanji: "支払う", kana: "しはらう", romaji: "shiharau", meaning: "membayar" },
  { level: "N3", type: "verb-godan", kanji: "凍る", kana: "こごえる", romaji: "kogoeru", meaning: "membeku" },
  { level: "N3", type: "verb-godan", kanji: "嫌う", kana: "きらう", romaji: "kirau", meaning: "membenci" },
  { level: "N4", type: "verb-godan", kanji: "伸ばす", kana: "のばす", romaji: "nobasu", meaning: "membentangkan" },
  { level: "N4", type: "verb-godan", kanji: "飼う", kana: "かう", romaji: "kau", meaning: "memberi makan" },
  { level: "N4", type: "verb-godan", kanji: "殺す", kana: "ころす", romaji: "korosu", meaning: "membunuh" },
  { level: "N3", type: "verb-godan", kanji: "腐る", kana: "くさる", romaji: "kusaru", meaning: "membusuk" },
  { level: "N4", type: "verb-godan", kanji: "解く", kana: "とく", romaji: "toku", meaning: "memecahkan" },
  { level: "N4", type: "verb-godan", kanji: "掴む", kana: "つかむ", romaji: "tsukamu", meaning: "memegang" },
  { level: "N3", type: "verb-godan", kanji: "抱く", kana: "いだく", romaji: "idaku", meaning: "memeluk" },
  { level: "N4", type: "verb-godan", kanji: "移す", kana: "うつす", romaji: "utsusu", meaning: "memindah" },
  { level: "N3", type: "verb-godan", kanji: "省く", kana: "はぶく", romaji: "habuku", meaning: "memotong, mengesampingkan" },
  { level: "N4", type: "verb-godan", kanji: "構う", kana: "かまう", romaji: "kamau", meaning: "mempedulikan, menghiraukan" },
  { level: "N4", type: "verb-godan", kanji: "防ぐ", kana: "ふせぐ", romaji: "fusegu", meaning: "menangkal" },
  { level: "N4", type: "verb-godan", kanji: "捕まる", kana: "つかまる", romaji: "tsukamaru", meaning: "menangkap" },
  { level: "N4", type: "verb-godan", kanji: "届く", kana: "とどく", romaji: "todoku", meaning: "mencapai, sampai" },
  { level: "N4", type: "verb-godan", kanji: "語る", kana: "かたる", romaji: "kataru", meaning: "bercerita" },
  { level: "N3", type: "verb-godan", kanji: "基づく", kana: "もとづく", romaji: "motodzuku", meaning: "berdasarkan" },
  { level: "N4", type: "verb-godan", kanji: "黙る", kana: "だまる", romaji: "damaru", meaning: "berdiam" },
  { level: "N5", type: "verb-godan", kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "berenang" },
  { level: "N4", type: "verb-godan", kanji: "願う", kana: "ねがう", romaji: "berharap", meaning: "berharap" },
  { level: "N5", type: "verb-godan", kanji: "言う", kana: "いう", romaji: "iu", meaning: "berkata" },
  { level: "N3", type: "verb-godan", kanji: "裏切る", kana: "うらぎる", romaji: "uragiru", meaning: "berkhianat" },
  { level: "N4", type: "verb-godan", kanji: "減る", kana: "へる", romaji: "heru", meaning: "berkurang" },
  { level: "N3", type: "verb-godan", kanji: "異なる", kana: "ことなる", romaji: "kotonaru", meaning: "berlainan" },
  { level: "N3", type: "verb-godan", kanji: "試す", kana: "ためす", romaji: "tamesu", meaning: "mencoba" },
  { level: "N3", type: "verb-godan", kanji: "注ぐ", kana: "つぐ", romaji: "tsugu", meaning: "mencurahi" },
  { level: "N4", type: "verb-godan", kanji: "苦しむ", kana: "くるしむ", romaji: "kurushimu", meaning: "menderita" },
  { level: "N4", type: "verb-godan", kanji: "通す", kana: "とおす", romaji: "toosu", meaning: "menembus" },
  { level: "N4", type: "verb-godan", kanji: "張る", kana: "はる", romaji: "haru", meaning: "menepuk" },
  { level: "N4", type: "verb-godan", kanji: "飛ばす", kana: "とばす", romaji: "tobasu", meaning: "menerbangkan" },
  { level: "N5", type: "verb-godan", kanji: "頂く", kana: "いただく", romaji: "itadaku", meaning: "menerima" },
  { level: "N4", type: "verb-godan", kanji: "受け取る", kana: "うけとる", romaji: "uketoru", meaning: "menerima" },
  { level: "N5", type: "verb-godan", kanji: "貰う", kana: "もらう", romaji: "morau", meaning: "menerima" },
  { level: "N4", type: "verb-godan", kanji: "誘う", kana: "さそう", romaji: "sasou", meaning: "mengajak, mengundang" },
  { level: "N4", type: "verb-godan", kanji: "流す", kana: "ながす", romaji: "nagasu", meaning: "mengalirkan" },
  { level: "N4", type: "verb-godan", kanji: "頼る", kana: "たよる", romaji: "tayoru", meaning: "mengandalkan" },
  { level: "N4", type: "verb-godan", kanji: "振る", kana: "ふる", romaji: "furu", meaning: "mengayunkan" },
  { level: "N4", type: "verb-godan", kanji: "追う", kana: "おう", romaji: "ou", meaning: "mengejar" },
  { level: "N4", type: "verb-godan", kanji: "表す", kana: "あらわす", romaji: "arawasu", meaning: "mengekspresikan" },
  { level: "N4", type: "verb-godan", kanji: "回す", kana: "まわす", romaji: "mawasu", meaning: "mengelilingi" },
  { level: "N5", type: "verb-godan", kanji: "戻す", kana: "もどす", romaji: "modosu", meaning: "mengembalikan" },
  { level: "N5", type: "verb-godan", kanji: "履く", kana: "はく", romaji: "haku", meaning: "mengenakan, memakai (kaki)" },
  { level: "N3", type: "verb-godan", kanji: "握る", kana: "にぎる", romaji: "nigiru", meaning: "mengepal" },
  { level: "N4", type: "verb-godan", kanji: "囲む", kana: "かこむ", romaji: "kakomu", meaning: "mengepung" },
  { level: "N3", type: "verb-godan", kanji: "唸る", kana: "うなる", romaji: "unaru", meaning: "mengerang, merintih" },
  { level: "N3", type: "verb-godan", kanji: "除く", kana: "のぞく", romaji: "nozoku", meaning: "mengesampingkan" },
  { level: "N4", type: "verb-godan", kanji: "雇う", kana: "やとう", romaji: "yatou", meaning: "menggaji, mempekerjakan" },
  { level: "N4", type: "verb-godan", kanji: "描く", kana: "えがく", romaji: "egaku", meaning: "menggambar" },
  { level: "N5", type: "verb-godan", kanji: "動かす", kana: "うごかす", romaji: "ugokasu", meaning: "menggerakan" },
  { level: "N4", type: "verb-godan", kanji: "狂う", kana: "くるう", romaji: "kuruu", meaning: "menggila" },
  { level: "N4", type: "verb-godan", kanji: "転ぶ", kana: "ころぶ", romaji: "korobu", meaning: "mengguling, berguling" },
  { level: "N3", type: "verb-godan", kanji: "及ぼす", kana: "およぼす", romaji: "oyobosu", meaning: "menggunakan" },
  { level: "N4", type: "verb-godan", kanji: "過ごす", kana: "すごす", romaji: "sugosu", meaning: "menghabiskan" },
  { level: "N4", type: "verb-godan", kanji: "望む", kana: "のぞむ", romaji: "nozomu", meaning: "mengharapkan, berkeinginan" },
  { level: "N4", type: "verb-godan", kanji: "結ぶ", kana: "むすぶ", romaji: "musubu", meaning: "mengikat" },
  { level: "N4", type: "verb-godan", kanji: "従う", kana: "したがう", romaji: "shitagau", meaning: "mengikuti" },
  { level: "N3", type: "verb-godan", kanji: "現す", kana: "あらわす", romaji: "arawasu", meaning: "mengindikasikan" },
  { level: "N5", type: "verb-godan", kanji: "思い出す", kana: "おもいだす", romaji: "omoidasu", meaning: "mengingat" },
  { level: "N4", type: "verb-godan", kanji: "贈る", kana: "おくる", romaji: "okuru", meaning: "mengirim hadiah" },
  { level: "N4", type: "verb-godan", kanji: "喋る", kana: "おしゃべる", romaji: "oshaberu", meaning: "mengobrol" },
  { level: "N4", type: "verb-godan", kanji: "叱る", kana: "しかる", romaji: "shikaru", meaning: "mengomeli, memarahi" },
  { level: "N4", type: "verb-godan", kanji: "計る", kana: "はかる", romaji: "hakaru", meaning: "mengukur" },
  { level: "N4", type: "verb-godan", kanji: "繰り返す", kana: "くりかえす", romaji: "kurikaesu", meaning: "mengulang" },
  { level: "N3", type: "verb-godan", kanji: "積もる", kana: "つもる", romaji: "tsumoru", meaning: "mengumpulkan" },
  { level: "N4", type: "verb-godan", kanji: "減らす", kana: "へらす", romaji: "herasu", meaning: "mengurangi" },
  { level: "N4", type: "verb-godan", kanji: "就く", kana: "つく", romaji: "tsuku", meaning: "menjabat" },
  { level: "N5", type: "verb-godan", kanji: "成る", kana: "なる", romaji: "naru", meaning: "menjadi" },
  { level: "N5", type: "verb-godan", kanji: "空く", kana: "すく", romaji: "suku", meaning: "menjadi kosong" },
  { level: "N4", type: "verb-godan", kanji: "離す", kana: "はなす", romaji: "hanasu", meaning: "menjauhkan" },
  { level: "N4", type: "verb-godan", kanji: "断る", kana: "ことわる", romaji: "kotowaru", meaning: "menolak" },
  { level: "N4", type: "verb-godan", kanji: "振り向く", kana: "ふりむく", romaji: "furimuku", meaning: "menoleh" },
  { level: "N5", type: "verb-godan", kanji: "向く", kana: "むく", romaji: "muku", meaning: "menoleh, berpaling" },
  { level: "N4", type: "verb-godan", kanji: "指す", kana: "さす", romaji: "sasu", meaning: "menunjuk" },
  { level: "N4", type: "verb-godan", kanji: "示す", kana: "しめす", romaji: "shimesu", meaning: "menunjukan" },
  { level: "N5", type: "verb-godan", kanji: "下ろす", kana: "おろす", romaji: "orosu", meaning: "menurunkan" },
  { level: "N4", type: "verb-godan", kanji: "刺す", kana: "さす", romaji: "sasu", meaning: "menusuk, menikam" },
  { level: "N5", type: "verb-godan", kanji: "覆う", kana: "おおう", romaji: "oou", meaning: "menutupi" },
  { level: "N4", type: "verb-godan", kanji: "気付く", kana: "きづく", romaji: "kidzuku", meaning: "menyadari" },
  { level: "N4", type: "verb-godan", kanji: "注ぐ", kana: "そそぐ", romaji: "sosogu", meaning: "menyeduh, melimpahkan" },
  { level: "N4", type: "verb-godan", kanji: "救う", kana: "すくう", romaji: "sukuu", meaning: "menyelamatkan" },
  { level: "N5", type: "verb-godan", kanji: "隠す", kana: "かくす", romaji: "kakusu", meaning: "menyembunyikan" },
  { level: "N4", type: "verb-godan", kanji: "撃つ", kana: "うつ", romaji: "utsu", meaning: "menyerang" },
  { level: "N5", type: "verb-godan", kanji: "残す", kana: "のこす", romaji: "nokosu", meaning: "menyisakan" },
  { level: "N4", type: "verb-godan", kanji: "繋ぐ", kana: "つなぐ", romaji: "tsunagu", meaning: "menghubungkan" },
  { level: "N4", type: "verb-godan", kanji: "起こる", kana: "おこる", romaji: "okoru", meaning: "terjadi" },
  { level: "N4", type: "verb-godan", kanji: "稼ぐ", kana: "かせぐ", romaji: "kasegu", meaning: "memperoleh pendapatan" },
  { level: "N4", type: "verb-godan", kanji: "叩く", kana: "たたく", romaji: "tataku", meaning: "menepuk, memukul" },
  { level: "N3", type: "verb-godan", kanji: "増す", kana: "ます", romaji: "masu", meaning: "menambah" },
  { level: "N4", type: "verb-godan", kanji: "微笑む", kana: "ほほえむ", romaji: "hohoemu", meaning: "tersenyum" },
  { level: "N4", type: "verb-godan", kanji: "残る", kana: "のこる", romaji: "nokoru", meaning: "tertinggal, tersisa" },
  { level: "N4", type: "verb-godan", kanji: "奪う", kana: "うばう", romaji: "ubau", meaning: "merenggut" },
  { level: "N4", type: "verb-godan", kanji: "破る", kana: "やぶる", romaji: "yaburu", meaning: "merobek" },
  { level: "N4", type: "verb-godan", kanji: "倒す", kana: "たおす", romaji: "taosu", meaning: "merobohkan" },
  { level: "N3", type: "verb-godan", kanji: "譲る", kana: "ゆずる", romaji: "yuzuru", meaning: "mewariskan" },
  { level: "N4", type: "verb-godan", kanji: "吐く", kana: "はく", romaji: "haku", meaning: "muntah" },
  { level: "N4", type: "verb-godan", kanji: "昇る", kana: "のぼる", romaji: "noboru", meaning: "naik, terbit" },
  { level: "N5", type: "verb-godan", kanji: "行く", kana: "いく", romaji: "iku", meaning: "pergi" },
  { level: "N4", type: "verb-godan", kanji: "去る", kana: "さる", romaji: "saru", meaning: "pergi, meninggalkan" },
  { level: "N4", type: "verb-godan", kanji: "沈む", kana: "しずむ", romaji: "shizumu", meaning: "tenggelam" },
  { level: "N4", type: "verb-godan", kanji: "育つ", kana: "そだつ", romaji: "sodatsu", meaning: "Tumbuh" },

  { level: "N5", type: "verb-ru", kanji: "居る", kana: "いる", romaji: "iru", meaning: "ada" },
  { level: "N4", type: "verb-ru", kanji: "離れる", kana: "はなれる", romaji: "hanareru", meaning: "berpisah" },
  { level: "N4", type: "verb-ru", kanji: "隠れる", kana: "かくれる", romaji: "bersembunyi", meaning: "bersembunyi" },
  { level: "N5", type: "verb-ru", kanji: "出来る", kana: "できる", romaji: "dekiru", meaning: "bisa" },
  { level: "N4", type: "verb-ru", kanji: "飽きる", kana: "あきる", romaji: "akiru", meaning: "jenuh" },
  { level: "N3", type: "verb-ru", kanji: "欠ける", kana: "かける", romaji: "kakeru", meaning: "kekurangan" },
  { level: "N4", type: "verb-ru", kanji: "怠ける", kana: "なまける", romaji: "namakeru", meaning: "malas" },
  { level: "N5", type: "verb-ru", kanji: "浴びる", kana: "あびる", romaji: "abiru", meaning: "mandi" },
  { level: "N4", type: "verb-ru", kanji: "越える", kana: "こえる", romaji: "koeru", meaning: "melampaui" },
  { level: "N3", type: "verb-ru", kanji: "優れる", kana: "すぐれる", romaji: "sugureru", meaning: "melampaui" },
  { level: "N5", type: "verb-ru", kanji: "見る", kana: "みる", romaji: "miru", meaning: "melihat" },
  { level: "N3", type: "verb-ru", kanji: "奏でる", kana: "かなでる", romaji: "kanaderu", meaning: "memainkan (musik)" },
  { level: "N4", type: "verb-ru", kanji: "進める", kana: "すすめる", romaji: "susumeru", meaning: "memajukan" },
  { level: "N3", type: "verb-ru", kanji: "用いる", kana: "もちいる", romaji: "mochiiru", meaning: "memakai, mempergunakan" },
  { level: "N4", type: "verb-ru", kanji: "眺める", kana: "ながめる", romaji: "nagameru", meaning: "memandang" },
  { level: "N5", type: "verb-ru", kanji: "付ける", kana: "つける", romaji: "tsukeru", meaning: "memasang, menempelkan" },
  { level: "N4", type: "verb-ru", kanji: "確かめる", kana: "たしかめる", romaji: "tashikameru", meaning: "memastikan" },
  { level: "N3", type: "verb-ru", kanji: "応じる", kana: "おうじる", romaji: "oujiru", meaning: "membalas, memenuhi" },
  { level: "N4", type: "verb-ru", kanji: "分ける", kana: "わける", romaji: "wakeru", meaning: "membelah" },
  { level: "N4", type: "verb-ru", kanji: "与える", kana: "あたえる", romaji: "ataeru", meaning: "memberikan, mempersembahkan" },
  { level: "N4", type: "verb-ru", kanji: "伸びる", kana: "のびる", romaji: "nobiru", meaning: "membujur, memanjang" },
  { level: "N3", type: "verb-ru", kanji: "命じる", kana: "めいじる", romaji: "meijiru", meaning: "memerintah" },
  { level: "N4", type: "verb-ru", kanji: "求める", kana: "もとめる", romaji: "motomeru", meaning: "meminta" },
  { level: "N3", type: "verb-ru", kanji: "論じる", kana: "ろんじる", romaji: "ronjiru", meaning: "memperbincangkan, membahas" },
  { level: "N4", type: "verb-ru", kanji: "立ち上げる", kana: "たちあげる", romaji: "tachiageru", meaning: "berdiri" },
  { level: "N5", type: "verb-ru", kanji: "辞める", kana: "やめる", romaji: "yameru", meaning: "berhenti" },
  { level: "N4", type: "verb-ru", kanji: "留める", kana: "とめる", romaji: "tomeru", meaning: "berhenti, bermalam" },
  { level: "N4", type: "verb-ru", kanji: "占める", kana: "しめる", romaji: "shimeru", meaning: "menempel" },
  { level: "N4", type: "verb-ru", kanji: "終える", kana: "おえる", romaji: "oeru", meaning: "mengakhiri" },
  { level: "N3", type: "verb-ru", kanji: "通じる", kana: "つうじる", romaji: "tsuujiru", meaning: "mengalirkan" },
  { level: "N4", type: "verb-ru", kanji: "取り上げる", kana: "とりあげる", romaji: "toriageru", meaning: "mengambil" },
  { level: "N4", type: "verb-ru", kanji: "持ち上げる", kana: "もちあげる", romaji: "mochiageru", meaning: "mengangkat" },
  { level: "N4", type: "verb-ru", kanji: "述べる", kana: "のべる", romaji: "noberu", meaning: "mengemukakan, menceritakan" },
  { level: "N4", type: "verb-ru", kanji: "換える", kana: "かえる", romaji: "kaeru", meaning: "mengganti" },
  { level: "N5", type: "verb-ru", kanji: "掛ける", kana: "かける", romaji: "kakeru", meaning: "menggantung" },
  { level: "N4", type: "verb-ru", kanji: "震える", kana: "ふるえる", romaji: "furueru", meaning: "menggigil, gemetaran" },
  { level: "N4", type: "verb-ru", kanji: "向ける", kana: "むける", romaji: "mukeru", meaning: "menghadapkan, mengarahkan" },
  { level: "N3", type: "verb-ru", kanji: "避ける", kana: "さける", romaji: "sakeru", meaning: "menghindar" },
  { level: "N4", type: "verb-ru", kanji: "数える", kana: "かぞえる", romaji: "kazoeru", meaning: "menghitung" },
  { level: "N4", type: "verb-ru", kanji: "預ける", kana: "あずける", romaji: "azukeru", meaning: "menitipkan" },
  { level: "N5", type: "verb-ru", kanji: "濡れる", kana: "ぬれる", romaji: "nureru", meaning: "menjadi basah" },
  { level: "N5", type: "verb-ru", kanji: "明ける", kana: "あける", romaji: "akeru", meaning: "menjadi terang" },
  { level: "N4", type: "verb-ru", kanji: "詰める", kana: "つめる", romaji: "tsumeru", meaning: "menjejalkan" },
  { level: "N5", type: "verb-ru", kanji: "助ける", kana: "たすける", romaji: "tasukeru", meaning: "menolong" },
  { level: "N4", type: "verb-ru", kanji: "収める", kana: "おさめる", romaji: "osameru", meaning: "menuai" },
  { level: "N5", type: "verb-ru", kanji: "替える", kana: "かえる", romaji: "kaeru", meaning: "menukar" },
  { level: "N4", type: "verb-ru", kanji: "閉じる", kana: "とじる", romaji: "tojiru", meaning: "menutup" },
  { level: "N3", type: "verb-ru", kanji: "責める", kana: "せめる", romaji: "semeru", meaning: "menyalahkan" },
  { level: "N4", type: "verb-ru", kanji: "吠える", kana: "ほえる", romaji: "hoeru", meaning: "menyalak, menggonggong, meraung" },
  { level: "N4", type: "verb-ru", kanji: "合わせる", kana: "あわせる", romaji: "awaseru", meaning: "menyatukan" },
  { level: "N4", type: "verb-ru", kanji: "触れる", kana: "ふれる", romaji: "fureru", meaning: "menyentuh" },
  { level: "N4", type: "verb-ru", kanji: "諦める", kana: "あきらめる", romaji: "akirameru", meaning: "menyerah" },
  { level: "N4", type: "verb-ru", kanji: "任せる", kana: "まかせる", romaji: "makaseru", meaning: "menyerahkan" },
  { level: "N4", type: "verb-ru", kanji: "支える", kana: "ささえる", romaji: "sasaeru", meaning: "menyokong, menopang" },
  { level: "N4", type: "verb-ru", kanji: "覚める", kana: "さめる", romaji: "sameru", meaning: "terjaga, bangun" },
  { level: "N4", type: "verb-ru", kanji: "売れる", kana: "うれる", romaji: "ureru", meaning: "terjual" },
  { level: "N4", type: "verb-ru", kanji: "得る", kana: "える", romaji: "eru", meaning: "memperoleh" },
  { level: "N4", type: "verb-ru", kanji: "備える", kana: "そなえる", romaji: "sonaeru", meaning: "mempersiapkan" },
  { level: "N4", type: "verb-ru", kanji: "褒める", kana: "ほめる", romaji: "homeru", meaning: "memuji" },
  { level: "N4", type: "verb-ru", kanji: "当てる", kana: "あてる", romaji: "ateru", meaning: "memukul, menebak, mengenai" },
  { level: "N4", type: "verb-ru", kanji: "加える", kana: "くわえる", romaji: "kuwaeru", meaning: "menambah, menambahkan" },
  { level: "N4", type: "verb-ru", kanji: "抜ける", kana: "ぬける", romaji: "nukeru", meaning: "terlepas" },
  { level: "N4", type: "verb-ru", kanji: "切れる", kana: "きれる", romaji: "kireru", meaning: "terpotong, cakap, habis" },
  { level: "N4", type: "verb-ru", kanji: "現れる", kana: "あらわれる", romaji: "arawareru", meaning: "muncul" },
  { level: "N4", type: "verb-ru", kanji: "解ける", kana: "とける", romaji: "tokeru", meaning: "pecah, terurai" },
  { level: "N4", type: "verb-ru", kanji: "満ちる", kana: "みちる", romaji: "michiru", meaning: "penuh" },
  { level: "N5", type: "verb-ru", kanji: "信じる", kana: "しんじる", romaji: "shinjiru", meaning: "percaya" },
  { level: "N4", type: "verb-ru", kanji: "訴える", kana: "うったえる", romaji: "uttaeru", meaning: "sue person, resort" },
  { level: "N4", type: "verb-ru", kanji: "恐れる", kana: "おそれる", romaji: "osoreru", meaning: "takut" },
  { level: "N4", type: "verb-ru", kanji: "溺れる", kana: "おぼれる", romaji: "oboreru", meaning: "tenggelam" },
  { level: "N4", type: "verb-ru", kanji: "燃える", kana: "もえる", romaji: "moeru", meaning: "terbakar" },

  { level: "N3", type: "verb-suru", kanji: "作業する", kana: "さぎょうする", romaji: "sagyou suru", meaning: "bekerja" },
  { level: "N3", type: "verb-suru", kanji: "協力する", kana: "きょうりょくする", romaji: "kyouryoku suru", meaning: "bekerja sama" },
  { level: "N5", type: "verb-suru", kanji: "勉強する", kana: "べんきょうする", romaji: "benkyou suru", meaning: "belajar" },
  { level: "N4", type: "verb-suru", kanji: "出発する", kana: "しゅっぱつする", romaji: "shuppatsu suru", meaning: "berangkat" },
  { level: "N3", type: "verb-suru", kanji: "呼吸する", kana: "こきゅうする", romaji: "kokyuu suru", meaning: "bernafas" },
  { level: "N4", type: "verb-suru", kanji: "運動する", kana: "うんどうする", romaji: "undou suru", meaning: "berolahraga" },
  { level: "N3", type: "verb-suru", kanji: "経験する", kana: "けいけんする", romaji: "keiken suru", meaning: "berpengalaman" },
  { level: "N5", type: "verb-suru", kanji: "掃除する", kana: "そうじする", romaji: "souji suru", meaning: "bersih-bersih" },
  { level: "N4", type: "verb-suru", kanji: "喧嘩する", kana: "けんかする", romaji: "kenka suru", meaning: "bertengkar" },
  { level: "N4", type: "verb-suru", kanji: "感謝する", kana: "かんしゃする", romaji: "berterima kasih", meaning: "berterima kasih" },
  { level: "N3", type: "verb-suru", kanji: "婚約する", kana: "こんやくする", romaji: "konyaku suru", meaning: "bertunangan" },
  { level: "N3", type: "verb-suru", kanji: "努力する", kana: "どりょくする", romaji: "doryoku suru", meaning: "berusaha keras" },
  { level: "N4", type: "verb-suru", kanji: "観光する", kana: "かんこうする", romaji: "kankou suru", meaning: "berwisata" },
  { level: "N2", type: "verb-suru", kanji: "自殺する", kana: "じさつする", romaji: "jisatsu suru", meaning: "bunuh diri" },
  { level: "N3", type: "verb-suru", kanji: "緊張する", kana: "きんちょうする", romaji: "kinchou suru", meaning: "gugup" },
  { level: "N3", type: "verb-suru", kanji: "希望する", kana: "きぼうする", romaji: "kibou suru", meaning: "hendak" },
  { level: "N5", type: "verb-suru", kanji: "散歩する", kana: "さんぽする", romaji: "sanpo suru", meaning: "jalan jalan" },
  { level: "N3", type: "verb-suru", kanji: "混乱する", kana: "こんらんする", romaji: "konran suru", meaning: "kalut, melakukan kekacauan" },
  { level: "N4", type: "verb-suru", kanji: "がっかりする", kana: "がっかりする", romaji: "gakkari suru", meaning: "kecewa" },
  { level: "N3", type: "verb-suru", kanji: "失望する", kana: "しつぼうする", romaji: "shitsubou suru", meaning: "kecewa" },
  { level: "N4", type: "verb-suru", kanji: "外出する", kana: "がいしゅつする", romaji: "gaishutsu suru", meaning: "keluar" },
  { level: "N4", type: "verb-suru", kanji: "相談する", kana: "そうだんする", romaji: "soudan suru", meaning: "konsultasi" },
  { level: "N4", type: "verb-suru", kanji: "合格する", kana: "ごうかくする", romaji: "goukaku suru", meaning: "lulus" },
  { level: "N4", type: "verb-suru", kanji: "入院する", kana: "にゅういんする", romaji: "nyuuin suru", meaning: "masuk rumah sakit" },
  { level: "N4", type: "verb-suru", kanji: "入学する", kana: "にゅうがくする", romaji: "nyuugaku suru", meaning: "masuk sekolah" },
  { level: "N3", type: "verb-suru", kanji: "解釈する", kana: "かいしゃくする", romaji: "kaishaku suru", meaning: "mejelaskan, menginterpretasikan" },
  { level: "N3", type: "verb-suru", kanji: "進学する", kana: "しんがくする", romaji: "shingaku suru", meaning: "melanjutkan sekolah" },
  { level: "N3", type: "verb-suru", kanji: "報告する", kana: "ほうこくする", romaji: "houkoku suru", meaning: "melaporkan" },
  { level: "N3", type: "verb-suru", kanji: "禁止する", kana: "きんしする", romaji: "kinshi suru", meaning: "melarang" },
  { level: "N2", type: "verb-suru", kanji: "爆発する", kana: "ばくはつする", romaji: "bakuhatsu suru", meaning: "meledakkan" },
  { level: "N3", type: "verb-suru", kanji: "横断する", kana: "おうだんする", romaji: "oudan suru", meaning: "melintasi" },
  { level: "N4", type: "verb-suru", kanji: "発車する", kana: "はっしゃする", romaji: "hassha suru", meaning: "meluncur" },
  { level: "N4", type: "verb-suru", kanji: "理解する", kana: "りかいする", romaji: "rikai suru", meaning: "memahami" },
  { level: "N4", type: "verb-suru", kanji: "無理する", kana: "むりする", romaji: "muri suru", meaning: "memaksakan diri" },
  { level: "N3", type: "verb-suru", kanji: "収穫する", kana: "しゅうかくする", romaji: "shuukaku suru", meaning: "memanen" },
  { level: "N3", type: "verb-suru", kanji: "比較する", kana: "ひかくりする", romaji: "hikaku suru", meaning: "membandingkan" },
  { level: "N3", type: "verb-suru", kanji: "援助する", kana: "えんじょする", romaji: "enjo suru", meaning: "membantu, mendukung" },
  { level: "N3", type: "verb-suru", kanji: "制限する", kana: "せいげんする", romaji: "seigen suru", meaning: "membatasi" },
  { level: "N3", type: "verb-suru", kanji: "建設する", kana: "けんせつする", romaji: "kensetsu suru", meaning: "membina" },
  { level: "N3", type: "verb-suru", kanji: "証明する", kana: "しょうめいする", romaji: "shoumei suru", meaning: "membuktikan" },
  { level: "N3", type: "verb-suru", kanji: "検査する", kana: "けんさする", romaji: "kensa suru", meaning: "memeriksa" },
  { level: "N4", type: "verb-suru", kanji: "注文する", kana: "ちゅうもんする", romaji: "chuumon suru", meaning: "memesan" },
  { level: "N4", type: "verb-suru", kanji: "選択する", kana: "せんたくする", romaji: "sentaku suru", meaning: "memilih" },
  { level: "N4", type: "verb-suru", kanji: "修理する", kana: "しゅうりする", romaji: "shuuri suru", meaning: "memperbaiki" },
  { level: "N3", type: "verb-suru", kanji: "議論する", kana: "ぎろんする", romaji: "giron suru", meaning: "memperbincangkan" },
  { level: "N3", type: "verb-suru", kanji: "警告する", kana: "けいこくする", romaji: "keikoku suru", meaning: "memperingati" },
  { level: "N2", type: "verb-suru", kanji: "逮捕する", kana: "たいほする", romaji: "taiho suru", meaning: "menangkap" },
  { level: "N3", type: "verb-suru", kanji: "供給する", kana: "きょうきゅうする", romaji: "kyoukyuu suru", meaning: "menawarkan, memberikan" },
  { level: "N4", type: "verb-suru", kanji: "就職する", kana: "しゅうしょくする", romaji: "shuushoku suru", meaning: "mencari pekerjaan" },
  { level: "N3", type: "verb-suru", kanji: "予防する", kana: "よぼうする", romaji: "yobou suru", meaning: "mencegah" },
  { level: "N3", type: "verb-suru", kanji: "営業する", kana: "えいぎょうする", romaji: "eigyou suru", meaning: "berbisnis" },
  { level: "N3", type: "verb-suru", kanji: "商売する", kana: "しょうばいする", romaji: "shoubai suru", meaning: "berdagang" },
  { level: "N4", type: "verb-suru", kanji: "参加する", kana: "さんかする", romaji: "sanka suru", meaning: "bergabung" },
  { level: "N4", type: "verb-suru", kanji: "期待する", kana: "きたいする", romaji: "kitai suru", meaning: "berharap" },
  { level: "N5", type: "verb-suru", kanji: "約束する", kana: "やくそくする", romaji: "yakosoku suru", meaning: "berjanji" },
  { level: "N3", type: "verb-suru", kanji: "関連する", kana: "かんれんする", romaji: "kanren suru", meaning: "berkaitan" },
  { level: "N3", type: "verb-suru", kanji: "集中する", kana: "しゅうちゅうする", romaji: "shuuchuu suru", meaning: "berkonsentrasi" },
  { level: "N3", type: "verb-suru", kanji: "貢献する", kana: "こうけんする", romaji: "kouken suru", meaning: "berkonstribusi" },
  { level: "N2", type: "verb-suru", kanji: "会合する", kana: "かいごうする", romaji: "kaigou suru", meaning: "berkumpull" },
  { level: "N3", type: "verb-suru", kanji: "訓練する", kana: "くんれんする", romaji: "kunren suru", meaning: "berlatih" },
  { level: "N5", type: "verb-suru", kanji: "練習する", kana: "れんしゅうする", romaji: "renshuu suru", meaning: "berlatih" },
  { level: "N3", type: "verb-suru", kanji: "発見する", kana: "はっけんする", romaji: "hakken suru", meaning: "mendeteksi, mendapati" },
  { level: "N3", type: "verb-suru", kanji: "建築する", kana: "けんちくする", romaji: "kenchiku suru", meaning: "mendirikan" },
  { level: "N3", type: "verb-suru", kanji: "強調する", kana: "きょうちょうする", romaji: "kyouchou suru", meaning: "menekankan, menonjolkan" },
  { level: "N3", type: "verb-suru", kanji: "検討する", kana: "けんとうする", romaji: "kentou suru", meaning: "meneliti" },
  { level: "N3", type: "verb-suru", kanji: "出版する", kana: "しゅっぱんする", romaji: "shuppan suru", meaning: "menerbitkan" },
  { level: "N4", type: "verb-suru", kanji: "決定する", kana: "けっていする", romaji: "kettei suru", meaning: "menetapkan" },
  { level: "N3", type: "verb-suru", kanji: "記録する", kana: "きろくする", romaji: "kiroku suru", meaning: "mengabadikan, mencatat" },
  { level: "N2", type: "verb-suru", kanji: "適用する", kana: "てきようする", romaji: "tekiyou suru", meaning: "mengadopsi, menggunakan (mesin)" },
  { level: "N4", type: "verb-suru", kanji: "観察する", kana: "かんさつする", romaji: "kansatsu suru", meaning: "mengamati" },
  { level: "N3", type: "verb-suru", kanji: "分析する", kana: "ぶんせきする", romaji: "bunseki suru", meaning: "menganalisa" },
  { level: "N3", type: "verb-suru", kanji: "失業する", kana: "しつぎょうする", romaji: "shitsugyou suru", meaning: "menganggur" },
  { level: "N4", type: "verb-suru", kanji: "配達する", kana: "はいたつする", romaji: "haitatsu suru", meaning: "mengantarkan" },
  { level: "N3", type: "verb-suru", kanji: "批評する", kana: "ひひょうする", romaji: "hihyou suru", meaning: "mengecam, mengkritik" },
  { level: "N3", type: "verb-suru", kanji: "変更する", kana: "へんこうする", romaji: "henkou suru", meaning: "mengedit" },
  { level: "N3", type: "verb-suru", kanji: "輸出する", kana: "ゆしゅつする", romaji: "yushutsu suru", meaning: "mengekspor" },
  { level: "N3", type: "verb-suru", kanji: "経営する", kana: "けいえいする", romaji: "keiei suru", meaning: "mengelola" },
  { level: "N3", type: "verb-suru", kanji: "発展する", kana: "はってんする", romaji: "hatten suru", meaning: "mengembangkan" },
  { level: "N4", type: "verb-suru", kanji: "邪魔する", kana: "じゃまする", romaji: "jama suru", meaning: "mengganggu" },
  { level: "N4", type: "verb-suru", kanji: "迷惑する", kana: "めいわくする", romaji: "meiwaku suru", meaning: "mengganggu" },
  { level: "N4", type: "verb-suru", kanji: "交換する", kana: "こうかんする", romaji: "koukan suru", meaning: "mengganti, menukar" },
  { level: "N4", type: "verb-suru", kanji: "使用する", kana: "しようする", romaji: "shiyou suru", meaning: "menggunakan" },
  { level: "N4", type: "verb-suru", kanji: "出席する", kana: "しゅっせきする", romaji: "shusseki suru", meaning: "menghadiri" },
  { level: "N4", type: "verb-suru", kanji: "計算する", kana: "けいさんする", romaji: "keisan suru", meaning: "menghitung" },
  { level: "N3", type: "verb-suru", kanji: "尊敬する", kana: "そんけいする", romaji: "sonkei suru", meaning: "menghormati" },
  { level: "N3", type: "verb-suru", kanji: "輸入する", kana: "ゆにゅうする", romaji: "yunyuu suru", meaning: "mengimpor" },
  { level: "N4", type: "verb-suru", kanji: "記入する", kana: "きにゅうする", romaji: "kinyuu suru", meaning: "mengisi, menginput" },
  { level: "N4", type: "verb-suru", kanji: "許可する", kana: "きょかする", romaji: "kyoka suru", meaning: "mengizinkan" },
  { level: "N4", type: "verb-suru", kanji: "心配する", kana: "しんぱいする", romaji: "shinpai suru", meaning: "mengkhawatirkan" },
  { level: "N4", type: "verb-suru", kanji: "確認する", kana: "かくにんする", romaji: "kakunin suru", meaning: "mengkomfirmasi" },
  { level: "N3", type: "verb-suru", kanji: "承認する", kana: "しょうにんする", romaji: "shounin suru", meaning: "mengkomfirmasi" },
  { level: "N3", type: "verb-suru", kanji: "消費する", kana: "しょうひする", romaji: "shouhi suru", meaning: "mengkonsumsi" },
  { level: "N3", type: "verb-suru", kanji: "契約する", kana: "けいやくする", romaji: "keiyaku suru", meaning: "mengontrak" },
  { level: "N3", type: "verb-suru", kanji: "左右する", kana: "さゆうする", romaji: "sayuu suru", meaning: "menguasai, mengendalikan" },
  { level: "N3", type: "verb-suru", kanji: "変化する", kana: "へんかする", romaji: "henka suru", meaning: "mengubah" },
  { level: "N3", type: "verb-suru", kanji: "発表する", kana: "はっぴょうする", romaji: "happyou suru", meaning: "mengumumkan" },
  { level: "N4", type: "verb-suru", kanji: "招待する", kana: "しょうたいする", romaji: "shoutai suru", meaning: "mengundang" },
  { level: "N4", type: "verb-suru", kanji: "訪問する", kana: "ほうもんする", romaji: "houmon suru", meaning: "mengunjungi" },
  { level: "N3", type: "verb-suru", kanji: "管理する", kana: "かんりする", romaji: "kanri suru", meaning: "mengurus" },
  { level: "N3", type: "verb-suru", kanji: "処理する", kana: "しょりする", romaji: "shori suru", meaning: "mengurus, mengolah" },
  { level: "N3", type: "verb-suru", kanji: "評価する", kana: "ひょうかする", romaji: "hyouka suru", meaning: "menilai" },
  { level: "N3", type: "verb-suru", kanji: "修正する", kana: "しゅうせいする", romaji: "shuusei suru", meaning: "meninjau kembali" },
  { level: "N2", type: "verb-suru", kanji: "支配する", kana: "しはいする", romaji: "shihai suru", meaning: "menjajah" },
  { level: "N3", type: "verb-suru", kanji: "保障する", kana: "ほしょうする", romaji: "hoshou suru", meaning: "menjamin" },
  { level: "N3", type: "verb-suru", kanji: "混雑する", kana: "こんざつする", romaji: "konzatsu suru", meaning: "menjejal" },
  { level: "N3", type: "verb-suru", kanji: "優勝する", kana: "ゆうしょうする", romaji: "yuushou suru", meaning: "menjuarai, memenangi" },
  { level: "N3", type: "verb-suru", kanji: "批判する", kana: "ひはんする", romaji: "hihan suru", meaning: "menkritik" },
  { level: "N4", type: "verb-suru", kanji: "歓迎する", kana: "かんげいする", romaji: "kangei suru", meaning: "menyambut" },
  { level: "N3", type: "verb-suru", kanji: "調査する", kana: "ちょうさする", romaji: "chousa suru", meaning: "menyelidiki" },
  { level: "N3", type: "verb-suru", kanji: "完成する", kana: "かんせいする", romaji: "kansei suru", meaning: "menyempurnakan, rampung" },
  { level: "N3", type: "verb-suru", kanji: "攻撃する", kana: "こうげきする", romaji: "kougeki suru", meaning: "menyerang" },
  { level: "N4", type: "verb-suru", kanji: "運転する", kana: "うんてんする", romaji: "unten suru", meaning: "menyetir" },
  { level: "N4", type: "verb-suru", kanji: "放送する", kana: "ほうそうする", romaji: "housou suru", meaning: "menyiarkan" },
  { level: "N3", type: "verb-suru", kanji: "結論する", kana: "けつろんする", romaji: "ketsuron suru", meaning: "menyimpulkan" },
  { level: "N3", type: "verb-suru", kanji: "刺激する", kana: "しげきする", romaji: "shigeki suru", meaning: "merangsang" },
  { level: "N3", type: "verb-suru", kanji: "推薦する", kana: "すいせんする", romaji: "suisen suru", meaning: "merekomendasikan" },
  { level: "N3", type: "verb-suru", kanji: "感動する", kana: "かんどうする", romaji: "kandou suru", meaning: "terharu, tersentuh" },
  { level: "N5", type: "verb-suru", kanji: "びっくりする", kana: "びっくりする", romaji: "bikkuri suru", meaning: "terkejut" },
  { level: "N3", type: "verb-suru", kanji: "感心する", kana: "かんしんする", romaji: "kanshin suru", meaning: "terkesan, mengagumi" },
  { level: "N3", type: "verb-suru", kanji: "生産する", kana: "せいさんする", romaji: "seisan suru", meaning: "memproduksi" },
  { level: "N4", type: "verb-suru", kanji: "開始する", kana: "かいしする", romaji: "kaishi suru", meaning: "memulai" },
  { level: "N3", type: "verb-suru", kanji: "回復する", kana: "かいふくする", romaji: "kaifuku suru", meaning: "memulihkan" },
  { level: "N3", type: "verb-suru", kanji: "決心する", kana: "けっしんする", romaji: "kesshin suru", meaning: "memutuskan dengan tekad kuat" },
  { level: "N4", type: "verb-suru", kanji: "貯金する", kana: "ちょきんする", romaji: "chokin suru", meaning: "menabung" },
  { level: "N3", type: "verb-suru", kanji: "請求する", kana: "せいきゅうする", romaji: "seiyuu suru", meaning: "menagih" },
  { level: "N4", type: "verb-suru", kanji: "我慢する", kana: "がまんする", romaji: "gaman suru", meaning: "menahan diri, bersabar" },
  { level: "N4", type: "verb-suru", kanji: "遅刻する", kana: "ちこくする", romaji: "chikoku suru", meaning: "terlambat" },
  { level: "N4", type: "verb-suru", kanji: "計画する", kana: "けいかくする", romaji: "keikaku suru", meaning: "merencanakan" },
  { level: "N2", type: "verb-suru", kanji: "掲示する", kana: "けいじする", romaji: "keiji suru", meaning: "mewahyukan" },
  { level: "N4", type: "verb-suru", kanji: "承知する", kana: "しょうちする", romaji: "shouchi suru", meaning: "paham, mengerti" },
  { level: "N4", type: "verb-suru", kanji: "出張する", kana: "しゅっちょうする", romaji: "shucchou suru", meaning: "perjalanan bisnis" },
  { level: "N4", type: "verb-suru", kanji: "帰宅する", kana: "きたくする", romaji: "kitaku suru", meaning: "pulang ke rumah" },
  { level: "N4", type: "verb-suru", kanji: "留学する", kana: "りゅうがくする", romaji: "ryuugaku suru", meaning: "sekolah di luar negeri" },
  { level: "N3", type: "verb-suru", kanji: "完了する", kana: "かんりょうする", romaji: "kanryou suru", meaning: "selesai, rampung" },
  { level: "N4", type: "verb-suru", kanji: "成功する", kana: "せいこうする", romaji: "seikou suru", meaning: "sukses" },

  
  { level: "N5", type: "adj-i", kanji: "大きい", kana: "おおきい", romaji: "ookii", meaning: "besar" },
  { level: "N5", type: "adj-i", kanji: "小さい", kana: "ちいさい", romaji: "chiisai", meaning: "kecil" },
  { level: "N5", type: "adj-i", kanji: "長い", kana: "ながい", romaji: "nagai", meaning: "panjang" },
  { level: "N5", type: "adj-i", kanji: "短い", kana: "みじかい", romaji: "mijikai", meaning: "pendek" },
  { level: "N5", type: "adj-i", kanji: "多い", kana: "おおい", romaji: "ooi", meaning: "banyak" },
  { level: "N5", type: "adj-i", kanji: "少ない", kana: "すくない", romaji: "sukunai", meaning: "sedikit" },
  { level: "N5", type: "adj-i", kanji: "太い", kana: "ふとい", romaji: "futoi", meaning: "gemuk, tebal" },
  { level: "N5", type: "adj-i", kanji: "新しい", kana: "あたらしい", romaji: "atarashii", meaning: "baru" },
  { level: "N5", type: "adj-i", kanji: "古い", kana: "ふるい", romaji: "furui", meaning: "lama, tua" },
  { level: "N5", type: "adj-i", kanji: "高い", kana: "たかい", romaji: "takai", meaning: "tinggi, mahal" },
  { level: "N5", type: "adj-i", kanji: "安い", kana: "やすい", romaji: "yasui", meaning: "murah" },
  { level: "N5", type: "adj-i", kanji: "低い", kana: "ひくい", romaji: "hikui", meaning: "rendah" },
  { level: "N5", type: "adj-i", kanji: "早い", kana: "はやい", romaji: "hayai", meaning: "cepat (waktu)" },
  { level: "N5", type: "adj-i", kanji: "速い", kana: "はやい", romaji: "hayai", meaning: "cepat (kelajuan)" },
  { level: "N5", type: "adj-i", kanji: "遅い", kana: "おそい", romaji: "osoi", meaning: "lambat" },
  { level: "N5", type: "adj-i", kanji: "遠い", kana: "とおい", romaji: "tooi", meaning: "jauh" },
  { level: "N5", type: "adj-i", kanji: "近い", kana: "ちかい", romaji: "chikai", meaning: "dekat" },
  
  { level: "N5", type: "adj-i", kanji: "暑い", kana: "あつい", romaji: "atsui", meaning: "panas (suhu cuaca)" },
  { level: "N5", type: "adj-i", kanji: "熱い", kana: "あつい", romaji: "atsui", meaning: "panas (untuk benda/suhu)" },
  { level: "N5", type: "adj-i", kanji: "厚い", kana: "あつい", romaji: "atsui", meaning: "tebal (untuk benda pipih)" },
  { level: "N5", type: "adj-i", kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "dingin (suhu cuaca)" },
  { level: "N5", type: "adj-i", kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "dingin (untuk benda)" },
  { level: "N5", type: "adj-i", kanji: "暖かい", kana: "あたたかい", romaji: "atatakai", meaning: "hangat (suhu cuaca)" },
  { level: "N5", type: "adj-i", kanji: "温かい", kana: "あたたかい", romaji: "atatakai", meaning: "hangat (untuk benda)" },
  { level: "N5", type: "adj-i", kanji: "涼しい", kana: "すずしい", romaji: "suzushii", meaning: "sejuk (suhu cuaca)" },

  { level: "N5", type: "adj-i", kanji: "甘い", kana: "あまい", romaji: "amai", meaning: "manis" },
  { level: "N5", type: "adj-i", kanji: "辛い", kana: "からい", romaji: "karai", meaning: "pedas" },
  { level: "N5", type: "adj-i", kanji: "美味しい", kana: "おいしい", romaji: "oishii", meaning: "enak" },
  { level: "N5", type: "adj-i", kanji: "不味い", kana: "まずい", romaji: "mazui", meaning: "tidak enak" },
  { level: "N5", type: "adj-i", kanji: "明るい", kana: "あかるい", romaji: "akarui", meaning: "terang, riang" },
  { level: "N5", type: "adj-i", kanji: "暗い", kana: "くらい", romaji: "kurai", meaning: "gelap, suram" },
  { level: "N5", type: "adj-i", kanji: "汚い", kana: "きたない", romaji: "kitanai", meaning: "kotor" },
  { level: "N5", type: "adj-i", kanji: "重い", kana: "おもい", romaji: "omoi", meaning: "berat" },
  { level: "N5", type: "adj-i", kanji: "軽い", kana: "かるい", romaji: "karui", meaning: "ringan" },
  { level: "N5", type: "adj-i", kanji: "難しい", kana: "むずかしい", romaji: "muzukashii", meaning: "sulit" },
  { level: "N5", type: "adj-i", kanji: "易しい", kana: "やさしい", romaji: "yasashii", meaning: "mudah" },
  { level: "N5", type: "adj-i", kanji: "危ない", kana: "あぶない", romaji: "abunai", meaning: "berbahaya" },
  { level: "N5", type: "adj-i", kanji: "いい", kana: "いい", romaji: "ii", meaning: "bagus, baik" },
  { level: "N5", type: "adj-i", kanji: "悪い", kana: "わるい", romaji: "warui", meaning: "jelek, buruk" },
  { level: "N5", type: "adj-i", kanji: "忙しい", kana: "いそがしい", romaji: "isogashii", meaning: "sibuk" },
  { level: "N5", type: "adj-i", kanji: "優しい", kana: "やさしい", romaji: "yasashii", meaning: "baik hati, ramah" },
  { level: "N5", type: "adj-i", kanji: "可愛い", kana: "かわいい", romaji: "kawaii", meaning: "cantik, lucu, imut" },
  { level: "N5", type: "adj-i", kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "menyenangkan" },
  { level: "N5", type: "adj-i", kanji: "面白い", kana: "おもしろい", romaji: "omoshiroi", meaning: "menarik, lucu" },
  { level: "N5", type: "adj-i", kanji: "つまらない", kana: "つまらない", romaji: "tsumaranai", meaning: "membosankan" },
  { level: "N5", type: "adj-i", kanji: "痛い", kana: "いたい", romaji: "itai", meaning: "merasa nyeri, sakit" },
  { level: "N5", type: "adj-i", kanji: "欲しい", kana: "ほしい", romaji: "hoshii", meaning: "ingin mendapatkan" },
  { level: "N5", type: "adj-i", kanji: "無い", kana: "ない", romaji: "nai", meaning: "tidak ada" },
  { level: "N5", type: "adj-i", kanji: "丸い", kana: "まるい", romaji: "marui", meaning: "bundar, bulat" },
  { level: "N5", type: "adj-i", kanji: "かっこいい", kana: "かっこいい", romaji: "kakkoii", meaning: "keren, terlihat bagus" },

  { level: "N5", type: "adj-na", kanji: "好き", kana: "すき", romaji: "suki", meaning: "suka" },
  { level: "N5", type: "adj-na", kanji: "嫌い", kana: "きらい", romaji: "kirai", meaning: "tidak suka, benci" },
  { level: "N5", type: "adj-na", kanji: "大好き", kana: "だいすき", romaji: "daisuki", meaning: "suka sekali" },
  { level: "N5", type: "adj-na", kanji: "大嫌い", kana: "だいきらい", romaji: "daikirai", meaning: "benci sekali" },
  { level: "N5", type: "adj-na", kanji: "綺麗", kana: "きれい", romaji: "kirei", meaning: "cantik, bersih" },
  { level: "N5", type: "adj-na", kanji: "賑やか", kana: "にぎやか", romaji: "nigiyaka", meaning: "ramai" },
  { level: "N5", type: "adj-na", kanji: "静か", kana: "しずか", romaji: "shizuka", meaning: "tenang" },
  { level: "N5", type: "adj-na", kanji: "便利", kana: "べんり", romaji: "benri", meaning: "praktis" },
  { level: "N5", type: "adj-na", kanji: "不便", kana: "ふべん", romaji: "fuben", meaning: "tidak praktis" },
  { level: "N5", type: "adj-na", kanji: "有名", kana: "ゆうめい", romaji: "yuumei", meaning: "terkenal" },
  { level: "N5", type: "adj-na", kanji: "色々", kana: "いろいろ", romaji: "iroiro", meaning: "bermacam-macam" },
  { level: "N5", type: "adj-na", kanji: "大丈夫", kana: "だいじょうぶ", romaji: "daijoubu", meaning: "tidak apa-apa, aman" },
  { level: "N5", type: "adj-na", kanji: "大切", kana: "たいせつ", romaji: "taisetsu", meaning: "penting" },
  { level: "N5", type: "adj-na", kanji: "駄目", kana: "だめ", romaji: "dame", meaning: "tidak boleh, rusak" },
  { level: "N5", type: "adj-na", kanji: "上手", kana: "じょうず", romaji: "jouzu", meaning: "pandai" },
  { level: "N5", type: "adj-na", kanji: "下手", kana: "へた", romaji: "heta", meaning: "tidak pandai" },
  { level: "N5", type: "adj-na", kanji: "暇", kana: "ひま", romaji: "hima", meaning: "senggang, luang" },
  { level: "N5", type: "adj-na", kanji: "立派", kana: "りっぱ", romaji: "rippa", meaning: "megah, layak dihormati" },
  { level: "N5", type: "adj-na", kanji: "大変", kana: "たいへん", romaji: "taihen", meaning: "berat (kasus/peristiwa)" },
  { level: "N5", type: "adj-na", kanji: "親切", kana: "しんせつ", romaji: "shinsetsu", meaning: "baik hati, ramah" },
  { level: "N5", type: "adj-na", kanji: "ハンサム", kana: "はんさむ", romaji: "hansamu", meaning: "ganteng" },
  { level: "N5", type: "adj-na", kanji: "嫌", kana: "いや", romaji: "iya", meaning: "tidak suka, benci" },
  { level: "N5", type: "adj-na", kanji: "丈夫", kana: "じょうぶ", romaji: "joubu", meaning: "kuat, kokoh" },
  { level: "N5", type: "adj-na", kanji: "同じ", kana: "おなじ", romaji: "onaji", meaning: "sama" },
  { level: "N5", type: "adj-na", kanji: "真っ直ぐ", kana: "まっすぐ", romaji: "massugu", meaning: "lurus" },

  { level: "N4", type: "adj-i", kanji: "細い", kana: "ほそい", romaji: "hosoi", meaning: "ramping, tipis" },
  { level: "N4", type: "adj-i", kanji: "薄い", kana: "うすい", romaji: "usui", meaning: "tipis, encer (rasa)" },
  { level: "N4", type: "adj-i", kanji: "固い", kana: "かたい", romaji: "katai", meaning: "keras" },
  { level: "N4", type: "adj-i", kanji: "柔らかい", kana: "やわらかい", romaji: "yawarakai", meaning: "lunak, empuk" },
  { level: "N4", type: "adj-i", kanji: "細かい", kana: "こまかい", romaji: "komakai", meaning: "kecil (uang/detail)" },
  { level: "N4", type: "adj-i", kanji: "強い", kana: "つよい", romaji: "tsuyoi", meaning: "kuat" },
  { level: "N4", type: "adj-i", kanji: "弱い", kana: "よわい", romaji: "yowai", meaning: "lemah" },
  { level: "N4", type: "adj-i", kanji: "ぬるい", kana: "ぬるい", romaji: "nurui", meaning: "kurang panas, suam-suam kuku" },
  { level: "N4", type: "adj-i", kanji: "酸っぱい", kana: "すっぱい", romaji: "suppai", meaning: "asam" },
  { level: "N4", type: "adj-i", kanji: "塩辛い", kana: "しおからい", romaji: "shiokarai", meaning: "asin" },
  { level: "N4", type: "adj-i", kanji: "苦い", kana: "にがい", romaji: "nigai", meaning: "pahit" },
  { level: "N4", type: "adj-i", kanji: "蒸し暑い", kana: "むしあつい", romaji: "mushiatsui", meaning: "panas gerah" },
  { level: "N4", type: "adj-i", kanji: "珍しい", kana: "めずらしい", romaji: "mezurashii", meaning: "langka" },
  { level: "N4", type: "adj-i", kanji: "おかしい", kana: "おかしい", romaji: "okashii", meaning: "aneh, lucu" },
  { level: "N4", type: "adj-i", kanji: "うまい", kana: "うまい", romaji: "umai", meaning: "enak, pandai" },
  { level: "N4", type: "adj-i", kanji: "ひどい", kana: "ひどい", romaji: "hidoi", meaning: "kejam, parah" },
  { level: "N4", type: "adj-i", kanji: "うるさい", kana: "うるさい", romaji: "urusai", meaning: "berisik" },
  { level: "N4", type: "adj-i", kanji: "正しい", kana: "ただしい", romaji: "tadashii", meaning: "benar" },
  { level: "N4", type: "adj-i", kanji: "すごい", kana: "すごい", romaji: "sugoi", meaning: "hebat" },
  { level: "N4", type: "adj-i", kanji: "素晴らしい", kana: "すばらしい", romaji: "subarashii", meaning: "luar biasa" },
  { level: "N4", type: "adj-i", kanji: "えらい", kana: "えらい", romaji: "erai", meaning: "pintar, hebat, berkuasa" },
  { level: "N4", type: "adj-i", kanji: "仲がいい", kana: "なかがいい", romaji: "naka ga ii", meaning: "rukun, akrab" },
  { level: "N4", type: "adj-i", kanji: "厳しい", kana: "きびしい", romaji: "kibishii", meaning: "tegas, ketat" },
  { level: "N4", type: "adj-i", kanji: "嬉しい", kana: "うれしい", romaji: "ureshii", meaning: "senang, gembira" },
  { level: "N4", type: "adj-i", kanji: "寂しい", kana: "さびしい", romaji: "sabishii", meaning: "merasa sepi" },
  { level: "N4", type: "adj-i", kanji: "怖い", kana: "こわい", romaji: "kowai", meaning: "takut" },
  { level: "N4", type: "adj-i", kanji: "悲しい", kana: "かなしい", romaji: "kanashii", meaning: "sedih" },
  { level: "N4", type: "adj-i", kanji: "恥ずかしい", kana: "はずかしい", romaji: "hazukashii", meaning: "malu" },
  { level: "N4", type: "adj-i", kanji: "眠い", kana: "ねむい", romaji: "nemui", meaning: "mengantuk" },

  { level: "N4", type: "adj-na", kanji: "残念", kana: "ざんねん", romaji: "zannen", meaning: "menyayangkan, kecewa" },
  { level: "N4", type: "adj-na", kanji: "心配", kana: "しんぱい", romaji: "shinpai", meaning: "khawatir" },
  { level: "N4", type: "adj-na", kanji: "不安", kana: "ふあん", romaji: "fuan", meaning: "cemas" },
  { level: "N4", type: "adj-na", kanji: "複雑", kana: "ふくざつ", romaji: "fukuzatsu", meaning: "rumit" },
  { level: "N4", type: "adj-na", kanji: "簡単", kana: "かんたん", romaji: "kantan", meaning: "mudah, gampang" },
  { level: "N4", type: "adj-na", kanji: "幸せ", kana: "しあわせ", romaji: "shiawase", meaning: "bahagia" },
  { level: "N4", type: "adj-na", kanji: "素敵", kana: "すてき", romaji: "suteki", meaning: "bagus (mempesona)" },
  { level: "N4", type: "adj-na", kanji: "安全", kana: "あんぜん", romaji: "anzen", meaning: "aman" },
  { level: "N4", type: "adj-na", kanji: "危険", kana: "きけん", romaji: "kiken", meaning: "berbahaya" },
  { level: "N4", type: "adj-na", kanji: "大事", kana: "だいじ", romaji: "daiji", meaning: "penting" },
  { level: "N4", type: "adj-na", kanji: "変", kana: "へん", romaji: "hen", meaning: "aneh" },
  { level: "N4", type: "adj-na", kanji: "無駄", kana: "むだ", romaji: "muda", meaning: "sia-sia" },
  { level: "N4", type: "adj-na", kanji: "急", kana: "きゅう", romaji: "kyuu", meaning: "mendadak" },
  { level: "N4", type: "adj-na", kanji: "得意", kana: "とくい", romaji: "tokui", meaning: "pandai, jago" },
  { level: "N4", type: "adj-na", kanji: "苦手", kana: "にがて", romaji: "nigate", meaning: "tidak pandai, lemah" },
  { level: "N4", type: "adj-na", kanji: "可哀想", kana: "かわいそう", romaji: "kawaisou", meaning: "kasihan" },
  { level: "N4", type: "adj-na", kanji: "楽", kana: "らく", romaji: "raku", meaning: "enteng, mudah" },
  { level: "N4", type: "adj-na", kanji: "無理", kana: "むり", romaji: "muri", meaning: "mustahil" },
  { level: "N4", type: "adj-na", kanji: "おしゃれ", kana: "おしゃれ", romaji: "oshare", meaning: "modis, bergaya" },
  { level: "N4", type: "adj-na", kanji: "丁寧", kana: "ていねい", romaji: "teinei", meaning: "sopan, halus, teliti" },
  { level: "N4", type: "adj-na", kanji: "真面目", kana: "まじめ", romaji: "majime", meaning: "rajin, serius, jujur" },
  { level: "N4", type: "adj-na", kanji: "不真面目", kana: "ふまじめ", romaji: "fumajime", meaning: "tidak serius, tidak jujur" },
  { level: "N4", type: "adj-na", kanji: "一生懸命", kana: "いっしょうけんめい", romaji: "isshoukenmei", meaning: "sungguh-sungguh" },
  { level: "N4", type: "adj-na", kanji: "盛ん", kana: "さかん", romaji: "sakan", meaning: "populer" },
  { level: "N4", type: "adj-na", kanji: "邪魔", kana: "じゃま", romaji: "jama", meaning: "mengganggu" },
  { level: "N4", type: "adj-na", kanji: "十分", kana: "じゅうぶん", romaji: "juubun", meaning: "cukup" },
  { level: "N4", type: "adj-na", kanji: "適当", kana: "てきとう", romaji: "tekitou", meaning: "tepat, sesuai" },
  { level: "N4", type: "adj-na", kanji: "特別", kana: "とくべつ", romaji: "tokubetsu", meaning: "khusus, spesial" },
  { level: "N4", type: "adj-na", kanji: "自由", kana: "じゆう", romaji: "jiyuu", meaning: "bebas" },
  { level: "N4", type: "adj-na", kanji: "熱心", kana: "ねっしん", romaji: "nesshin", meaning: "dengan sungguh hati, rajin" },
  { level: "N4", type: "adj-na", kanji: "必要", kana: "ひつよう", romaji: "hitsuyou", meaning: "perlu" },
  { level: "N4", type: "adj-na", kanji: "別", kana: "べつ", romaji: "betsu", meaning: "lain, beda" },
  { level: "N4", type: "adj-na", kanji: "不思議", kana: "ふしぎ", romaji: "fushigi", meaning: "ajaib" },
  { level: "N4", type: "adj-na", kanji: "意地悪", kana: "いじわる", romaji: "ijiwaru", meaning: "bersifat tega, jahat" },

  { level: "N3", type: "adj-i", kanji: "粗い", kana: "あらい", romaji: "arai", meaning: "kasar" },
  { level: "N3", type: "adj-i", kanji: "濃い", kana: "こい", romaji: "koi", meaning: "pekat" },
  { level: "N3", type: "adj-i", kanji: "詳しい", kana: "くわしい", romaji: "kuwashii", meaning: "detail, rinci" },
  { level: "N3", type: "adj-i", kanji: "親しい", kana: "したしい", romaji: "shitashii", meaning: "akrab" },
  { level: "N3", type: "adj-i", kanji: "美しい", kana: "うつくしい", romaji: "utsukushii", meaning: "indah" },
  { level: "N3", type: "adj-i", kanji: "大人しい", kana: "おとなしい", romaji: "otonashii", meaning: "lemah lembut, pendiam" },
  { level: "N3", type: "adj-i", kanji: "羨ましい", kana: "うらやましい", romaji: "urayamashii", meaning: "iri hati" },
  { level: "N3", type: "adj-i", kanji: "懐かしい", kana: "なつかしい", romaji: "natsukashii", meaning: "terkenang, kangen" },
  
  { level: "N3", type: "adj-na", kanji: "豪華", kana: "ごうか", romaji: "gouka", meaning: "mewah" },
  { level: "N3", type: "adj-na", kanji: "伝統的", kana: "でんとうてき", romaji: "dentouteki", meaning: "tradisional" },
  { level: "N3", type: "adj-na", kanji: "活発", kana: "かっぱつ", romaji: "kappatsu", meaning: "aktif" },
  { level: "N3", type: "adj-na", kanji: "誠実", kana: "せいじつ", romaji: "seijitsu", meaning: "tulus hati, setia" },
  { level: "N3", type: "adj-na", kanji: "わがまま", kana: "わがまま", romaji: "wagamama", meaning: "bersifat egois" },
  { level: "N3", type: "adj-na", kanji: "頑固", kana: "がんこ", romaji: "ganko", meaning: "keras kepala" },
  { level: "N3", type: "adj-na", kanji: "素直", kana: "すなお", romaji: "sunao", meaning: "patuh, polos" },
  { level: "N3", type: "adj-na", kanji: "勝ち気", kana: "かちき", romaji: "kachiki", meaning: "tidak mau kalah" },
  { level: "N3", type: "adj-na", kanji: "神経質", kana: "しんけいしつ", romaji: "shinkeishitsu", meaning: "sensitif, khawatir berlebihan" },

  { level: "N5", type: "noun-place", kanji: "場所", kana: "ばしょ", romaji: "basho", meaning: "tempat" },
  { level: "N5", type: "noun-place", kanji: "建物/ビル", kana: "たてもの/びる", romaji: "tatemono/biru", meaning: "bangunan" },
  { level: "N5", type: "noun-place", kanji: "公園", kana: "こうえん", romaji: "kouen", meaning: "taman" },
  { level: "N4", type: "noun-place", kanji: "動物園", kana: "どうぶつえん", romaji: "doubutsuen", meaning: "kebun binatang" },
  { level: "N5", type: "noun-place", kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "sekolah" },
  { level: "N4", type: "noun-place", kanji: "空港", kana: "くうこう", romaji: "kuukou", meaning: "bandara" },
  { level: "N3", type: "noun-place", kanji: "港", kana: "みなと", romaji: "minato", meaning: "pelabuhan" },
  { level: "N5", type: "noun-place", kanji: "銀行", kana: "ぎんこう", romaji: "ginkou", meaning: "bank" },
  { level: "N5", type: "noun-place", kanji: "駅", kana: "えき", romaji: "eki", meaning: "stasiun" },
  { level: "N5", type: "noun-place", kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "rumah sakit" },
  { level: "N2", type: "noun-place", kanji: "刑務所", kana: "けいむしょ", romaji: "keimusho", meaning: "penjara" },
  { level: "N4", type: "noun-place", kanji: "郵便局", kana: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "kantor post" },
  { level: "N4", type: "noun-place", kanji: "事務所", kana: "じむしょ", romaji: "jimusho", meaning: "kantor" },
  { level: "N5", type: "noun-place", kanji: "大学", kana: "だいがく", romaji: "daigaku", meaning: "universitas" },
  { level: "N4", type: "noun-place", kanji: "寮", kana: "りょう", romaji: "ryou", meaning: "asrama" },
  { level: "N3", type: "noun-place", kanji: "寄宿舎", kana: "きしゅくしゃ", romaji: "kishukusha", meaning: "asrama mahasiswa" },
  { level: "N3", type: "noun-place", kanji: "合宿", kana: "がっしゅく", romaji: "gasshuku", meaning: "perkemahan" },
  { level: "N4", type: "noun-place", kanji: "図書館", kana: "としょかん", romaji: "toshokan", meaning: "perpustakaan" },
  { level: "N4", type: "noun-place", kanji: "映画館", kana: "えいがかん", romaji: "eigakan", meaning: "bioskop" },
  { level: "N4", type: "noun-place", kanji: "水族館", kana: "すいぞくかん", romaji: "suizokukan", meaning: "aquarium" },
  { level: "N4", type: "noun-place", kanji: "博物館", kana: "はくぶつかん", romaji: "hakubutsukan", meaning: "musium" },
  { level: "N3", type: "noun-place", kanji: "美術館", kana: "びじゅつかん", romaji: "bijutsukan", meaning: "musium seni" },
  { level: "N4", type: "noun-place", kanji: "体育館", kana: "たいいくかん", romaji: "taiikukan", meaning: "gimnasium" },
  { level: "N3", type: "noun-place", kanji: "記念館", kana: "きねんかん", romaji: "kinenkan", meaning: "monumen/tugu peringatan" },
  { level: "N3", type: "noun-place", kanji: "大使館", kana: "たいしかん", romaji: "taishikan", meaning: "kedutaan" },
  { level: "N4", type: "noun-place", kanji: "旅館", kana: "りょかん", romaji: "ryokan", meaning: "penginapan" },
  { level: "N4", type: "noun-place", kanji: "スタジアム", kana: "すたじあむ", romaji: "sutajiamu", meaning: "stadion" },
  { level: "N5", type: "noun-place", kanji: "ホテル", kana: "ほてる", romaji: "hoteru", meaning: "hotel" },
  { level: "N5", type: "noun-place", kanji: "アパート", kana: "あぱーと", romaji: "apaato", meaning: "apartement" },
  { level: "N5", type: "noun-place", kanji: "デパート", kana: "でぱーと", romaji: "depaato", meaning: "departement" },
  { level: "N5", type: "noun-place", kanji: "レストラン", kana: "れすとらん", romaji: "resutoran", meaning: "restoran" },
  { level: "N4", type: "noun-place", kanji: "市場", kana: "いちば", romaji: "ichiba", meaning: "pasar/market" },
  { level: "N4", type: "noun-place", kanji: "工場", kana: "こうじょう", romaji: "koujou", meaning: "pabrik" },
  { level: "N3", type: "noun-place", kanji: "会場", kana: "かいじょう", romaji: "kaijou", meaning: "tempat rapat" },
  { level: "N5", type: "noun-place", kanji: "食堂", kana: "しょくどう", romaji: "shokudou", meaning: "kafeteria" },
  { level: "N4", type: "noun-place", kanji: "交番", kana: "こうばん", romaji: "kouban", meaning: "kantor polisi" },
  { level: "N4", type: "noun-place", kanji: "神社", kana: "じんじゃ", romaji: "jinja", meaning: "tempat suci" },
  { level: "N4", type: "noun-place", kanji: "寺", kana: "てら", romaji: "tera", meaning: "kuil" },
  { level: "N4", type: "noun-place", kanji: "モスク", kana: "もすく", romaji: "mosuku", meaning: "masjid" },
  { level: "N4", type: "noun-place", kanji: "教会", kana: "きょうかい", romaji: "kyoukai", meaning: "gereja" },
  { level: "N3", type: "noun-place", kanji: "保育園", kana: "ほいくえん", romaji: "hoikuen", meaning: "play group" },
  { level: "N3", type: "noun-place", kanji: "幼稚園", kana: "ようちえん", romaji: "youchien", meaning: "taman kanak-kanak" },
  { level: "N3", type: "noun-place", kanji: "植物園", kana: "しょくぶつえん", romaji: "shokubutsuen", meaning: "kebun raya" },
  { level: "N5", type: "noun-place", kanji: "家", kana: "うち/いえ", romaji: "uchi/ie", meaning: "rumah" },
  { level: "N4", type: "noun-place", kanji: "近所", kana: "きんじょ", romaji: "kinjo", meaning: "tetangga" },
  { level: "N3", type: "noun-place", kanji: "食料品店", kana: "しょくりょうひんてん", romaji: "shokuryouhinten", meaning: "toko makanan" },
  { level: "N4", type: "noun-place", kanji: "花屋", kana: "はなや", romaji: "hanaya", meaning: "toko bunga" },
  { level: "N4", type: "noun-place", kanji: "薬屋", kana: "くすりや", romaji: "kusuriya", meaning: "apotik" },
  { level: "N4", type: "noun-place", kanji: "魚屋", kana: "さかなや", romaji: "sakanaya", meaning: "pasar ikan" },
  { level: "N4", type: "noun-place", kanji: "肉屋", kana: "にくや", romaji: "nikuya", meaning: "toko daging" },
  { level: "N4", type: "noun-place", kanji: "八百屋", kana: "やおや", romaji: "yaoya", meaning: "toko buah dan sayuran" },
  { level: "N4", type: "noun-place", kanji: "床屋", kana: "とおや", romaji: "tokoya", meaning: "tukang cukur" },
  { level: "N4", type: "noun-place", kanji: "パン屋", kana: "ぱんや", romaji: "panya", meaning: "toko roti" },
  { level: "N3", type: "noun-place", kanji: "質屋", kana: "しちや", romaji: "shichiya", meaning: "tempat penggadaian" },
  { level: "N3", type: "noun-place", kanji: "居酒屋", kana: "いざかや", romaji: "izakaya", meaning: "bar" },
  { level: "N5", type: "noun-place", kanji: "喫茶店", kana: "きっさてん", romaji: "kissaten", meaning: "kedai kopi" },
  { level: "N4", type: "noun-place", kanji: "温泉", kana: "おんせん", romaji: "onsen", meaning: "pemandian air panas" },
  { level: "N3", type: "noun-place", kanji: "風呂屋", kana: "ふろや", romaji: "furoya", meaning: "wc umum" },
  { level: "N3", type: "noun-place", kanji: "露天風呂", kana: "ろてんぶろ", romaji: "rotenburo", meaning: "pemandian di alam terbuka" },
  { level: "N5", type: "question", kanji: "何分", kana: "なんぷん", romaji: "nan-pun", meaning: "berapa menit?" },
  { level: "N5", type: "question", kanji: "何曜日", kana: "なんようび", romaji: "nanyoubi", meaning: "hari apa?" },
  { level: "N5", type: "question", kanji: "何日", kana: "なんにち", romaji: "nannichi", meaning: "tanggal berapa, berapa hari?" },
  { level: "N5", type: "question", kanji: "何月", kana: "なんがつ", romaji: "nan gatsu", meaning: "bulan apa?" },
  { level: "N5", type: "question", kanji: "何秒", kana: "なんびょう", romaji: "nan-byoo", meaning: "berapa detik?" },
  { level: "N5", type: "question", kanji: "何時", kana: "なんじ", romaji: "nan-ji", meaning: "jam berapa?" },
  
  { level: "N5", type: "noun-counter", kanji: "1分", kana: "いっぷん", romaji: "ip-pun", meaning: "1 menit" },
  { level: "N5", type: "noun-counter", kanji: "2分", kana: "にふん", romaji: "nifun", meaning: "2 menit" },
  { level: "N5", type: "noun-counter", kanji: "3分", kana: "さんぷん", romaji: "san-pun", meaning: "3 menit" },
  { level: "N5", type: "noun-counter", kanji: "4分", kana: "よんぷん", romaji: "yon-pun", meaning: "4 menit" },
  { level: "N5", type: "noun-counter", kanji: "5分", kana: "ごふん", romaji: "gofun", meaning: "5 menit" },
  { level: "N5", type: "noun-counter", kanji: "6分", kana: "ろっぷん", romaji: "rop-pun", meaning: "6 menit" },
  { level: "N5", type: "noun-counter", kanji: "7分", kana: "ななふん", romaji: "nanafun", meaning: "7 menit" },
  { level: "N5", type: "noun-counter", kanji: "8分", kana: "はっぷん", romaji: "hap-pun", meaning: "8 menit" },
  { level: "N5", type: "noun-counter", kanji: "9分", kana: "きゅうふん", romaji: "kyuu-fun", meaning: "9 menit" },
  { level: "N5", type: "noun-counter", kanji: "10分", kana: "じっぷん", romaji: "jip-pun", meaning: "10 menit" },
  { level: "N5", type: "noun-counter", kanji: "20分", kana: "にじっぷん", romaji: "ni-jip-pun", meaning: "20 menit" },
  { level: "N5", type: "noun-counter", kanji: "30分", kana: "san-jup-pun", romaji: "san-jip-pun", meaning: "30 menit" },
  { level: "N5", type: "noun-counter", kanji: "一日", kana: "ついたち", romaji: "tsuitachi", meaning: "tanggal 1" },
  { level: "N5", type: "noun-counter", kanji: "二日", kana: "ふつか", romaji: "futsuka", meaning: "tanggal 2" },
  { level: "N5", type: "noun-counter", kanji: "三日", kana: "みっか", romaji: "mikka", meaning: "tanggal 3" },
  { level: "N5", type: "noun-counter", kanji: "四日", kana: "よっか", romaji: "yokka", meaning: "tanggal 4" },
  { level: "N5", type: "noun-counter", kanji: "五日", kana: "いつか", romaji: "itsuka", meaning: "tanggal 5" },
  { level: "N5", type: "noun-counter", kanji: "六日", kana: "むいか", romaji: "muika", meaning: "tanggal 6" },
  { level: "N5", type: "noun-counter", kanji: "七日", kana: "なのか", romaji: "nanoka", meaning: "tanggal 7" },
  { level: "N5", type: "noun-counter", kanji: "八日", kana: "ようか", romaji: "youka", meaning: "tanggal 8" },
  { level: "N5", type: "noun-counter", kanji: "九日", kana: "ここのか", romaji: "kokonoka", meaning: "tanggal 9" },
  { level: "N5", type: "noun-counter", kanji: "十日", kana: "とおか", romaji: "tooka", meaning: "tanggal 10" },
  { level: "N5", type: "noun-counter", kanji: "二十日", kana: "はつか", romaji: "hatsuka", meaning: "tanggal 20" },
  { level: "N5", type: "noun-counter", kanji: "1時", kana: "いちじ", romaji: "ichi-ji", meaning: "pukul 1" },
  { level: "N5", type: "noun-counter", kanji: "1秒", kana: "いちびょう", romaji: "ichi-byoo", meaning: "1 detik" },
  
  { level: "N5", type: "noun-time", kanji: "月曜日", kana: "げつようび", romaji: "getsuyoubi", meaning: "senin" },
  { level: "N5", type: "noun-time", kanji: "火曜日", kana: "かようび", romaji: "kayoubi", meaning: "selasa" },
  { level: "N5", type: "noun-time", kanji: "水曜日", kana: "すいようび", romaji: "suiyoubi", meaning: "rabu" },
  { level: "N5", type: "noun-time", kanji: "木曜日", kana: "もくようび", romaji: "mokuyoubi", meaning: "kamis" },
  { level: "N5", type: "noun-time", kanji: "金曜日", kana: "きんようび", romaji: "kinyoubi", meaning: "jumat" },
  { level: "N5", type: "noun-time", kanji: "土曜日", kana: "どようび", romaji: "doyoubi", meaning: "sabtu" },
  { level: "N5", type: "noun-time", kanji: "日曜日", kana: "にちようび", romaji: "nichiyoubi", meaning: "minggu" },
  { level: "N5", type: "noun-time", kanji: "季節", kana: "きせつ", romaji: "kisetsu", meaning: "musim" },
  { level: "N5", type: "noun-time", kanji: "春", kana: "はる", romaji: "haru", meaning: "musim semi" },
  { level: "N5", type: "noun-time", kanji: "夏", kana: "なつ", romaji: "natsu", meaning: "musim panas" },
  { level: "N5", type: "noun-time", kanji: "秋", kana: "あき", romaji: "aki", meaning: "musim gugur" },
  { level: "N5", type: "noun-time", kanji: "冬", kana: "ふゆ", romaji: "fuyu", meaning: "musim dingin" },

  { level: "N5", type: "noun-month", kanji: "一月", kana: "いちがつ", romaji: "ichigatsu", meaning: "januari" },
  { level: "N5", type: "noun-month", kanji: "二月", kana: "にがつ", romaji: "nigatsu", meaning: "februari" },
  { level: "N5", type: "noun-month", kanji: "三月", kana: "さんがつ", romaji: "sangatsu", meaning: "maret" },
  { level: "N5", type: "noun-month", kanji: "四月", kana: "しがつ", romaji: "shigatsu", meaning: "april" },
  { level: "N5", type: "noun-month", kanji: "五月", kana: "ごがつ", romaji: "gogatsu", meaning: "mei" },
  { level: "N5", type: "noun-month", kanji: "六月", kana: "ろくがつ", romaji: "rokugatsu", meaning: "juni" },
  { level: "N5", type: "noun-month", kanji: "七月", kana: "しちがつ", romaji: "shichigatsu", meaning: "juli" },
  { level: "N5", type: "noun-month", kanji: "八月", kana: "はちがつ", romaji: "hachigatsu", meaning: "agustus" },
  { level: "N5", type: "noun-month", kanji: "九月", kana: "くがつ", romaji: "kugatsu", meaning: "september" },
  { level: "N5", type: "noun-month", kanji: "十月", kana: "じゅうがつ", romaji: "juugatsu", meaning: "oktober" },
  { level: "N5", type: "noun-month", kanji: "十一月", kana: "じゅういちがつ", romaji: "juuichigatsu", meaning: "november" },
  { level: "N5", type: "noun-month", kanji: "十二月", kana: "じゅうにがつ", romaji: "juunigatsu", meaning: "desember" },
  
  { level: "N5", type: "noun-weather", kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "cuaca" },
  { level: "N5", type: "noun-weather", kanji: "雨", kana: "あめ", romaji: "ame", meaning: "hujan" },
  { level: "N5", type: "noun-weather", kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "salju" },
  { level: "N5", type: "noun-weather", kanji: "雲", kana: "くも", romaji: "kumo", meaning: "awan" },
  { level: "N5", type: "noun-weather", kanji: "晴れ", kana: "はれ", romaji: "hare", meaning: "cerah" },
  { level: "N5", type: "noun-weather", kanji: "曇り", kana: "くもり", romaji: "kumori", meaning: "mendung" },
  
  { level: "N5", type: "noun-family", kanji: "家族", kana: "かぞく", romaji: "kazoku", meaning: "Keluarga" },
  { level: "N5", type: "noun-family", kanji: "父", kana: "ちち", romaji: "chichi", meaning: "Ayah (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "母", kana: "はは", romaji: "haha", meaning: "Ibu (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "お父さん", kana: "おとうさん", romaji: "otousan", meaning: "Ayah (Orang Lain)" },
  { level: "N5", type: "noun-family", kanji: "お母さん", kana: "おかあさん", romaji: "okaasan", meaning: "Ibu (Orang Lain)" },
  { level: "N5", type: "noun-family", kanji: "両親", kana: "りょうしん", romaji: "ryoushin", meaning: "Kedua Orang Tua" },
  { level: "N5", type: "noun-family", kanji: "兄", kana: "あに", romaji: "ani", meaning: "Kakak Laki-laki (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "姉", kana: "あね", romaji: "ane", meaning: "Kakak Perempuan (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "弟", kana: "おとうと", romaji: "otouto", meaning: "Adik Laki-laki (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "妹", kana: "いもうと", romaji: "imouto", meaning: "Adik Perempuan (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "お兄さん", kana: "おにいさん", romaji: "oniisan", meaning: "Kakak Laki-laki (Orang Lain)" },
  { level: "N5", type: "noun-family", kanji: "お姉さん", kana: "おねえさん", romaji: "oneesan", meaning: "Kakak Perempuan (Orang Lain)" },
  { level: "N5", type: "noun-family", kanji: "夫", kana: "おっと", romaji: "otto", meaning: "Suami (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "妻", kana: "つま", romaji: "tsuma", meaning: "Istri (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "子供", kana: "こども", romaji: "kodomo", meaning: "Anak" },

  { level: "N5", type: "noun-body", kanji: "頭", kana: "あたま", romaji: "atama", meaning: "Kepala" },
  { level: "N5", type: "noun-body", kanji: "顔", kana: "かお", romaji: "kao", meaning: "Wajah, Muka" },
  { level: "N5", type: "noun-body", kanji: "髪", kana: "かみ", romaji: "kami", meaning: "Rambut" },
  { level: "N5", type: "noun-body", kanji: "目", kana: "め", romaji: "me", meaning: "Mata" },
  { level: "N5", type: "noun-body", kanji: "耳", kana: "みみ", romaji: "mimi", meaning: "Telinga" },
  { level: "N5", type: "noun-body", kanji: "鼻", kana: "はな", romaji: "hana", meaning: "Hidung" },
  { level: "N5", type: "noun-body", kanji: "口", kana: "くち", romaji: "kuchi", meaning: "Mulut" },
  { level: "N5", type: "noun-body", kanji: "歯", kana: "は", romaji: "ha", meaning: "Gigi" },
  { level: "N4", type: "noun-body", kanji: "首", kana: "くび", romaji: "kubi", meaning: "Leher" },
  { level: "N5", type: "noun-body", kanji: "手", kana: "て", romaji: "te", meaning: "Tangan" },
  { level: "N4", type: "noun-body", kanji: "腕", kana: "うで", romaji: "ude", meaning: "Lengan" },
  { level: "N4", type: "noun-body", kanji: "指", kana: "ゆび", romaji: "yubi", meaning: "Jari" },
  { level: "N4", type: "noun-body", kanji: "胸", kana: "むね", romaji: "mune", meaning: "Dada" },
  { level: "N5", type: "noun-body", kanji: "お腹", kana: "おなか", romaji: "onaka", meaning: "Perut" },
  { level: "N4", type: "noun-body", kanji: "背中", kana: "せなか", romaji: "senaka", meaning: "Punggung" },
  { level: "N5", type: "noun-body", kanji: "足", kana: "あし", romaji: "ashi", meaning: "Kaki" },

  { level: "N5", type: "noun-animal", kanji: "犬", kana: "いぬ", romaji: "inu", meaning: "Anjing" },
  { level: "N5", type: "noun-animal", kanji: "猫", kana: "ねこ", romaji: "neko", meaning: "Kucing" },
  { level: "N5", type: "noun-animal", kanji: "鳥", kana: "とり", romaji: "tori", meaning: "Burung" },
  { level: "N5", type: "noun-animal", kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "Ikan" },
  { level: "N4", type: "noun-animal", kanji: "牛", kana: "うし", romaji: "ushi", meaning: "Sapi" },
  { level: "N4", type: "noun-animal", kanji: "馬", kana: "うま", romaji: "uma", meaning: "Kuda" },
  { level: "N4", type: "noun-animal", kanji: "豚", kana: "ぶた", romaji: "buta", meaning: "Babi" },
  { level: "N4", type: "noun-animal", kanji: "猿", kana: "さる", romaji: "saru", meaning: "Monyet" },
  { level: "N4", type: "noun-animal", kanji: "虫", kana: "むし", romaji: "mushi", meaning: "Serangga" },

  { level: "N5", type: "noun-vehicle", kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "Mobil" },
  { level: "N5", type: "noun-vehicle", kanji: "電車", kana: "でんしゃ", romaji: "densha", meaning: "Kereta Listrik" },
  { level: "N5", type: "noun-vehicle", kanji: "自転車", kana: "じてんしゃ", romaji: "jitensha", meaning: "Sepeda" },
  { level: "N5", type: "noun-vehicle", kanji: "飛行機", kana: "ひこうき", romaji: "hikouki", meaning: "Pesawat Terbang" },
  { level: "N5", type: "noun-vehicle", kanji: "船", kana: "ふね", romaji: "fune", meaning: "Kapal Laut" },
  { level: "N5", type: "noun-vehicle", kanji: "地下鉄", kana: "ちかてつ", romaji: "chikatetsu", meaning: "Kereta Bawah Tanah" },
  { level: "N5", type: "noun-vehicle", kanji: "新幹線", kana: "しんかんせん", romaji: "shinkansen", meaning: "Kereta Peluru" },
  { level: "N5", type: "noun-vehicle", kanji: "バス", kana: "ばす", romaji: "basu", meaning: "Bus" },
  { level: "N5", type: "noun-vehicle", kanji: "タクシー", kana: "たくしー", romaji: "takushii", meaning: "Taksi" },
  { level: "N4", type: "noun-vehicle", kanji: "オートバイ", kana: "おーとばい", romaji: "ootobai", meaning: "Sepeda Motor" },
  { level: "N4", type: "noun-place", kanji: "船便", kana: "ふなびん", romaji: "funabin", meaning: "Pos Laut" },
  { level: "N4", type: "noun-place", kanji: "航空便", kana: "こうくうびん", romaji: "koukuubin", meaning: "Pos Udara" },

  { level: "N5", type: "noun-place", kanji: "病院", kana: "びょういん", romaji: "byouin", meaning: "Rumah Sakit" },
  { level: "N5", type: "noun-profession", kanji: "医者", kana: "いしゃ", romaji: "isha", meaning: "Dokter" },
  { level: "N5", type: "noun-medical", kanji: "薬", kana: "くすり", romaji: "kusuri", meaning: "Obat" },
  { level: "N5", type: "noun-medical", kanji: "病気", kana: "びょうき", romaji: "byouki", meaning: "Penyakit, Sakit" },
  { level: "N4", type: "noun-medical", kanji: "風邪", kana: "かぜ", romaji: "kaze", meaning: "Masuk Angin, Flu" },
  { level: "N4", type: "noun-medical", kanji: "熱", kana: "ねつ", romaji: "netsu", meaning: "Demam, Panas" },
  { level: "N4", type: "noun-medical", kanji: "注射", kana: "ちゅうしゃ", romaji: "chuusha", meaning: "Suntikan" },
  { level: "N4", type: "noun-medical", kanji: "怪我", kana: "けが", romaji: "kega", meaning: "Luka, Cedera" },
  { level: "N4", type: "noun-medical", kanji: "血", kana: "ち", romaji: "chi", meaning: "Darah" },
  { level: "N4", type: "noun-profession", kanji: "歯医者", kana: "はいしゃ", romaji: "haisha", meaning: "Dokter Gigi" },
  { level: "N4", type: "noun-profession", kanji: "看護師", kana: "かんごし", romaji: "kangoshi", meaning: "Perawat" },
  { level: "N4", type: "noun-medical", kanji: "具合", kana: "ぐあい", romaji: "guai", meaning: "Kondisi (Kesehatan)" },

  { level: "N5", type: "noun-family", kanji: "娘", kana: "むすめ", romaji: "musume", meaning: "Anak Perempuan (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "息子", kana: "むすこ", romaji: "musuko", meaning: "Anak Laki-laki (Sendiri)" },
  { level: "N5", type: "noun-family", kanji: "孫", kana: "まご", romaji: "mago", meaning: "Cucu" },
  { level: "N5", type: "noun-family", kanji: "夫婦", kana: "ふうふ", romaji: "fuufu", meaning: "Suami Istri" },
  { level: "N5", type: "noun-family", kanji: "兄弟", kana: "きょうだい", romaji: "kyoudai", meaning: "Saudara" },
  { level: "N5", type: "noun-family", kanji: "姉妹", kana: "しまい", romaji: "shimai", meaning: "Saudara Perempuan" },
  { level: "N5", type: "noun-family", kanji: "伯母さん", kana: "おばさん", romaji: "obasan", meaning: "Bibi, Tante" },
  { level: "N5", type: "noun-family", kanji: "伯父さん", kana: "おじさん", romaji: "ojisan", meaning: "Paman, Om" },
  { level: "N5", type: "noun-family", kanji: "お祖父さん", kana: "おじいさん", romaji: "ojiisan", meaning: "Kakek" },
  { level: "N5", type: "noun-family", kanji: "お祖母さん", kana: "おばあさん", romaji: "obaasan", meaning: "Nenek" },

  { level: "N5", type: "noun-number", kanji: "零, ゼロ", kana: "れい, ぜろ", romaji: "rei, zero", meaning: "Nol (0)" },
  { level: "N5", type: "noun-number", kanji: "一", kana: "いち", romaji: "ichi", meaning: "Satu (1)" },
  { level: "N5", type: "noun-number", kanji: "二", kana: "に", romaji: "ni", meaning: "Dua (2)" },
  { level: "N5", type: "noun-number", kanji: "三", kana: "さん", romaji: "san", meaning: "Tiga (3)" },
  { level: "N5", type: "noun-number", kanji: "四", kana: "よん, し", romaji: "yon, shi", meaning: "Empat (4)" },
  { level: "N5", type: "noun-number", kanji: "五", kana: "ご", romaji: "go", meaning: "Lima (5)" },
  { level: "N5", type: "noun-number", kanji: "六", kana: "ろく", romaji: "roku", meaning: "Enam (6)" },
  { level: "N5", type: "noun-number", kanji: "七", kana: "なな, しち", romaji: "nana, shichi", meaning: "Tujuh (7)" },
  { level: "N5", type: "noun-number", kanji: "八", kana: "はち", romaji: "hachi", meaning: "Delapan (8)" },
  { level: "N5", type: "noun-number", kanji: "九", kana: "きゅう, く", romaji: "kyuu, ku", meaning: "Sembilan (9)" },
  { level: "N5", type: "noun-number", kanji: "十", kana: "じゅう", romaji: "juu", meaning: "Sepuluh (10)" },
  { level: "N5", type: "noun-number", kanji: "百", kana: "ひゃく", romaji: "hyaku", meaning: "Seratus (100)" },
  { level: "N5", type: "noun-number", kanji: "千", kana: "せん", romaji: "sen", meaning: "Seribu (1.000)" },
  { level: "N5", type: "noun-number", kanji: "万", kana: "まん", romaji: "man", meaning: "Sepuluh Ribu (10.000)" },

  // ==========================================
  // 🟢 LEVEL N5 - KATA BANTU BILANGAN (COUNTERS)
  // ==========================================
  // 1. Satuan Benda Umum (~Tsu)
  { level: "N5", type: "noun-counter", kanji: "一つ", kana: "ひとつ", romaji: "hitotsu", meaning: "1 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "二つ", kana: "ふたつ", romaji: "futatsu", meaning: "2 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "三つ", kana: "みっつ", romaji: "mittsu", meaning: "3 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "四つ", kana: "よっつ", romaji: "yottsu", meaning: "4 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "五つ", kana: "いつつ", romaji: "itsutsu", meaning: "5 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "十", kana: "とお", romaji: "too", meaning: "10 Buah (Benda Umum)" },
  { level: "N5", type: "noun-counter", kanji: "幾つ", kana: "いくつ", romaji: "ikutsu", meaning: "Berapa Buah?" },

  // 2. Satuan Orang (~Nin)
  { level: "N5", type: "noun-counter", kanji: "一人", kana: "ひとり", romaji: "hitori", meaning: "1 Orang" },
  { level: "N5", type: "noun-counter", kanji: "二人", kana: "ふたり", romaji: "futari", meaning: "2 Orang" },
  { level: "N5", type: "noun-counter", kanji: "三人", kana: "さんにん", romaji: "sannin", meaning: "3 Orang" },
  { level: "N5", type: "noun-counter", kanji: "四人", kana: "よにん", romaji: "yonin", meaning: "4 Orang" },
  { level: "N5", type: "question", kanji: "何人", kana: "なんにん", romaji: "nannin", meaning: "Berapa Orang?" },
];

const patternData = {
  N5: [
    { pattern: "です", example: "私は学生です。", meaning: "Adalah." },
    { pattern: "ます", example: "私は毎日勉強します。", meaning: "Bentuk sopan." },
    { pattern: "ません", example: "私はコーヒーを飲みません。", meaning: "Bentuk negatif sopan." },
    { pattern: "でした", example: "昨日は暑かったです。", meaning: "Bentuk lampau." },
    { pattern: "ではありません", example: "これは本ではありません。", meaning: "Bukan." },
    { pattern: "か", example: "これは何ですか？", meaning: "Pertanyaan." },
    { pattern: "も", example: "私も学生です。", meaning: "Juga." },
    { pattern: "～の", example: "これは日本の車です。", meaning: "Kepemilikan/keterangan noun." },
    { pattern: "～を", example: "私はパンを食べます。", meaning: "Penanda objek langsung." },
    { pattern: "～に", example: "7時に起きます。", meaning: "Penanda waktu/tujuan keberadaan." },
    { pattern: "～で", example: "図書館で勉強します。", meaning: "Penanda tempat kegiatan/alat." },
    { pattern: "～へ", example: "日本へ行きます。", meaning: "Arah/tujuan." },
    { pattern: "～から～まで", example: "9時から5時まで働きます。", meaning: "Dari sampai." },
    { pattern: "～と", example: "友達と映画を見ます。", meaning: "Bersama/dengan." },
    { pattern: "～や～など", example: "机の上に本やノートなどがあります。", meaning: "Daftar tidak lengkap." },
    { pattern: "～がほしい", example: "新しい辞書がほしいです。", meaning: "Ingin benda." },
    { pattern: "～たい", example: "日本へ行きたいです。", meaning: "Ingin melakukan sesuatu." },
    { pattern: "～ませんか", example: "いっしょに昼ご飯を食べませんか。", meaning: "Ajakan halus." },
    { pattern: "～ましょう", example: "少し休みましょう。", meaning: "Mari kita..." },
    { pattern: "～てください", example: "ここに名前を書いてください。", meaning: "Permintaan sopan." },
    { pattern: "～てもいいです", example: "ここで写真を撮ってもいいです。", meaning: "Izin melakukan sesuatu." },
    { pattern: "～てはいけません", example: "ここでタバコを吸ってはいけません。", meaning: "Larangan." },
    { pattern: "～ています", example: "今、雨が降っています。", meaning: "Sedang berlangsung/keadaan." },
    { pattern: "～に行きます", example: "友達と買い物に行きます。", meaning: "Pergi untuk melakukan V-masu stem." },
    { pattern: "～たことがあります", example: "富士山に登ったことがあります。", meaning: "Pernah mengalami." },
    { pattern: "～たり～たりします", example: "日曜日は掃除をしたり、音楽を聞いたりします。", meaning: "Contoh aktivitas yang dilakukan." },
    { pattern: "～くて, ～で", example: "この店は安くておいしいです。", meaning: "Menggabung sifat/kalimat." },
    { pattern: "～から", example: "今日は寒いですから、コートを着ます。", meaning: "Alasan/sebab." },
    { pattern: "～ので", example: "用事があるので、先に帰ります。", meaning: "Alasan lebih lembut." },
    { pattern: "～と思います", example: "明日は晴れると思います。", meaning: "Menyatakan pendapat." },
    { pattern: "～つもりです", example: "来年、日本へ留学するつもりです。", meaning: "Rencana/niat." },
    { pattern: "～前に", example: "寝る前に歯を磨きます。", meaning: "Sebelum." },
    { pattern: "～後で", example: "仕事の後で買い物します。", meaning: "Sesudah." },
    { pattern: "～時半", example: "9時半 (Ku-ji-han)", meaning: "Menunjukkan waktu setengah atau lewat 30 menit" },
    { pattern: "～時～分", example: "1時15分 (Ichi-ji juu-go-fun)", meaning: "Menunjukkan satuan jam dan menit secara spesifik" }
  ],
  
  N4: [
    { 
      pattern: "〜し〜し", 
      example: "ラーメンはかんたんにできるし、安いし、おいしい。 (Ramen gampang dibuat, murah dan enak)", 
      meaning: "Mengungkapkan beberapa alasan sekaligus atau menyebutkan hal/sifat yang setara." 
    },
    { 
      pattern: "〜て, 〜で", 
      example: "しゅくだいをわすれて、先生にしかられた。 (Karena lupa PR, dimarahi sensei)", 
      meaning: "Menunjukkan penyebab atau alasan dari suatu kejadian." 
    },
    { 
      pattern: "〜んです", 
      example: "A: どうしたんですか。 B: 頭がいたいんです。 (A: Ada apa? B: Kepalaku sakit)", 
      meaning: "Memberikan penjelasan, alasan, atau penekanan pada suatu kondisi." 
    },
    { 
      pattern: "それで", 
      example: "ここはコーヒーが100円です。それで、人気があるんです。 (Disini kopinya 100 yen. Karenanya populer)", 
      meaning: "Menyatakan sebab-akibat (Dan, karenanya, oleh sebab itu)." 
    },
    { 
      pattern: "〜ので", 
      example: "用事があるので、お先にしつれいします。 (Karena ada keperluan, maaf ya aku duluan)", 
      meaning: "Menyatakan alasan secara objektif dan lebih halus dari 'kara'." 
    },
    { 
      pattern: "〜てあげる", 
      example: "ルームメートに、料理を作ってあげました。 (Aku memasakkan makanan untuk teman sekamar)", 
      meaning: "Melakukan suatu tindakan atau kebaikan untuk orang lain." 
    },
    { 
      pattern: "〜てくれる", 
      example: "わかい人が、にもつを持ってくれました。 (Pemuda memberikan bantuan dengan membawa barangku)", 
      meaning: "Seseorang melakukan sesuatu/kebaikan untuk pembicara atau keluarga pembicara." 
    },
    { 
      pattern: "〜てもらう", 
      example: "田中さんに、ノートを貸してもらった。 (Tanaka meminjamkan buku catatan untukku)", 
      meaning: "Menerima suatu perlakuan, bantuan, atau kebaikan dari orang lain." 
    },
    { 
      pattern: "〜てくれませんか, 〜てくださいませんか", 
      example: "もっと勉強したいので、教えていただけませんか。 (Karena ingin belajar lagi, bisakah mengajarkan aku?)", 
      meaning: "Meminta tolong dengan sopan (Bisakah Anda...?, Maukah Anda...?)." 
    },
    { 
      pattern: "可能形 (Bentuk Potensial)", 
      example: "この水は飲める。 (Air ini bisa diminum)", 
      meaning: "Menyatakan kesanggupan, kemampuan, atau kemungkinan (Bisa, Dapat)." 
    },
    { 
      pattern: "命令形 (Bentuk Perintah)", 
      example: "早くしろ！ (Cepat lakukan!)", 
      meaning: "Memberikan perintah secara tegas dan kasar." 
    },
    { 
      pattern: "禁止形 (Bentuk Melarang)", 
      example: "ここでタバコを吸うな！ (Jangan merokok di sini!)", 
      meaning: "Melarang seseorang melakukan sesuatu dengan tegas (Jangan...!)." 
    },
    { 
      pattern: "仮定形 (〜ば)", 
      example: "この薬を飲めば、なおります。 (Jika minum obat ini, maka akan sembuh)", 
      meaning: "Menyatakan syarat atau pengandaian (Jika... maka...)." 
    },
    { 
      pattern: "意向形 (Bentuk Maksud)", 
      example: "夏休みは、海に行こう。 (Liburan musim panas, ayo ke laut)", 
      meaning: "Menyatakan ajakan, niat, atau kemauan diri sendiri (Ayo, Mari, Aku akan...)." 
    },
    { 
      pattern: "受身形 (Bentuk Pasif)", 
      example: "先生にほめられました。 (Aku dipuji oleh guru)", 
      meaning: "Menyatakan kalimat pasif (Di-, Ter-), sering kali mengandung nuansa kerugian/kekecewaan." 
    },
    { 
      pattern: "使役形 (Bentuk Kausatif)", 
      example: "母は子どもに野菜を食べさせます。 (Ibu membuat/menyuruh anaknya makan sayur)", 
      meaning: "Menyuruh, membiarkan, atau membuat orang lain melakukan sesuatu." 
    },
    { 
      pattern: "使役受身形 (Bentuk Kausatif-Pasif)", 
      example: "母に野菜を食べさせられました。 (Aku dipaksa makan sayur oleh ibu)", 
      meaning: "Terpaksa atau dipaksa melakukan sesuatu oleh orang lain." 
    },
    { 
      pattern: "〜見える, 〜聞こえる", 
      example: "部屋から、テレビの音が聞こえます。 (Dari kamar terdengar suara televisi)", 
      meaning: "Kemampuan melihat/mendengar secara alami tanpa niat (Terlihat, Terdengar)." 
    },
    { 
      pattern: "〜てある", 
      example: "予定はカレンダーに書いてあります。 (Rencananya tertulis di kalendar)", 
      meaning: "Menunjukkan kondisi/keadaan benda setelah seseorang sengaja melakukan sesuatu terhadapnya." 
    },
    { 
      pattern: "〜てしまう", 
      example: "昨日買ったジュースは飲んでしまいました。 (Jus yang dibeli kemarin telah habis diminum)", 
      meaning: "Menyatakan suatu tindakan telah selesai sepenuhnya, atau mengekspresikan penyesalan/kekecewaan." 
    },
    { 
      pattern: "〜ている (Kondisi)", 
      example: "かぎがかかっています。 (Pintunya terkunci)", 
      meaning: "Menunjukkan keadaan, hasil dari suatu tindakan yang masih berlanjut sampai sekarang." 
    },
    { 
      pattern: "〜と言う", 
      example: "鈴木さんは、明日休むと言っていました。 (Suzuki telah berkata bahwa besok libur)", 
      meaning: "Mengutip perkataan orang lain (Seseorang berkata bahwa...)." 
    },
    { 
      pattern: "〜たところ", 
      example: "たった今、食べたところです。 (Barusan saja makan)", 
      meaning: "Menyatakan suatu tindakan baru saja selesai dilakukan sesaat yang lalu." 
    },
    { 
      pattern: "まだ 〜ている", 
      example: "まだ雨が降っています。 (Masih hujan)", 
      meaning: "Menyatakan suatu keadaan atau kejadian masih sedang berlangsung (Masih...)." 
    },
    { 
      pattern: "〜たばかり", 
      example: "先月、新しい会社に入ったばかりでしょう？ (Bulan lalu, baru saja masuk perusahaan baru, kan?)", 
      meaning: "Merasa bahwa suatu tindakan baru saja terjadi (menurut perasaan pembicara)." 
    },
    { 
      pattern: "〜たほうがいい, 〜ないほうがいい", 
      example: "今日は、おふろに入らないほうがいいですよ。 (Hari ini lebih baik tidak mandi)", 
      meaning: "Memberikan saran atau nasihat (Lebih baik..., Sebaiknya tidak...)." 
    },
    { 
      pattern: "〜なくてもいい", 
      example: "今、しなくてもいいですよ。 (Sekarang tidak melakukannya juga tidak apa-apa)", 
      meaning: "Menyatakan ketiadaan kewajiban (Tidak perlu, Tidak harus...)." 
    },
    { 
      pattern: "〜という意味", 
      example: "この漢字は、くつをぬげという意味です。 (Kanji ini berarti lepaskan sepatu)", 
      meaning: "Menjelaskan arti atau makna dari suatu kata/simbol." 
    },
    { 
      pattern: "〜ないで", 
      example: "昨日、寝ないで勉強したんです。 (Tadi malam, belajar tanpa tidur)", 
      meaning: "Menyatakan melakukan suatu tindakan tanpa melakukan tindakan lain (Tanpa...)." 
    },
    { 
      pattern: "〜やすい, 〜にくい", 
      example: "字が小さくて、読みにくいです。 (Hurufnya kecil dan susah dibaca)", 
      meaning: "Menyatakan tingkat kesulitan suatu tindakan (Mudah untuk..., Sulit untuk...)." 
    },
    { 
      pattern: "〜あとで", 
      example: "仕事のあとで、ごはんを食べに行きます。 (Setelah bekerja, pergi makan)", 
      meaning: "Menyatakan urutan kejadian (Setelah...)." 
    },
    { 
      pattern: "〜までに", 
      example: "あさってまでにレポートを出してください。 (Sebelum 2 hari kedepan, kumpulkan laporannya)", 
      meaning: "Menyatakan batas waktu paling lambat, deadline (Selambat-lambatnya sebelum...)." 
    },
    { 
      pattern: "〜ながら", 
      example: "テレビを見ながら、ごはんを食べます。 (Makan sambil menonton TV)", 
      meaning: "Melakukan dua kegiatan dalam satu waktu (Sambil...)." 
    },
    { 
      pattern: "〜すぎる", 
      example: "このズボンは長すぎます。 (Celana panjang ini terlalu panjang)", 
      meaning: "Menyatakan keadaan yang berlebihan atau melampaui batas wajar (Terlalu...)." 
    },
    { 
      pattern: "〜しか 〜ない", 
      example: "ひとつしかありません。 (Hanya punya satu)", 
      meaning: "Menyatakan batasan dengan kuat, selalu diikuti kalimat negatif (Hanya..., Tidak ada selain...)." 
    },
    { 
      pattern: "〜で (Batas)", 
      example: "10万円で買える車はありますか。 (Mobil yang bisa dibeli dengan batas 100 ribu yen apakah ada?)", 
      meaning: "Menunjukkan batasan waktu, harga, atau kuantitas (Dalam batas, Seharga...)." 
    },
    { 
      pattern: "〜とか", 
      example: "カラオケとかゲームとかをします。 (Akan diadakan hal seperti game dan karaoke)", 
      meaning: "Memberikan beberapa contoh dari sekumpulan hal (seperti... atau...)." 
    },
    { 
      pattern: "〜でも", 
      example: "のどがかわきましたね。お茶でも飲みませんか。 (Aku haus. Bagaimana jika minum teh atau sesuatu yang lain?)", 
      meaning: "Menawarkan atau menyarankan suatu hal sebagai salah satu pilihan (...atau sejenisnya)." 
    },
    { 
      pattern: "〜のは, 〜のが", 
      example: "ゲームをするのは、おもしろいです。 (Bermain game itu menyenangkan)", 
      meaning: "Menominalkan (mengubah menjadi kata benda) suatu kalimat/kata kerja." 
    },
    { 
      pattern: "〜と (Syarat Alami)", 
      example: "おさけを飲むと、顔が赤くなるんです。 (Jika minum sake, maka muka akan merah)", 
      meaning: "Menyatakan syarat yang hasilnya otomatis atau alami terjadi (Jika A, maka pasti B)." 
    },
    { 
      pattern: "〜たら", 
      example: "テストが悪かったら、どうしよう。 (Jika tesnya jelek, bagaimana?)", 
      meaning: "Pengandaian bebas atau menyatakan kejadian berurutan (Jika, Kalau, Setelah)." 
    },
    { 
      pattern: "〜なら", 
      example: "大阪に行くなら、たこやきを食べてください。 (Jika pergi ke Osaka, makanlah Takoyaki)", 
      meaning: "Memberikan saran atau pendapat berdasarkan topik/informasi yang sedang dibicarakan." 
    },
    { 
      pattern: "〜のに", 
      example: "勉強したのに、テスト0点でした。 (Padahal sudah belajar, dapat nilai 0)", 
      meaning: "Menyatakan pertentangan yang menimbulkan rasa kaget, kecewa, atau tidak puas (Padahal...)." 
    },
    { 
      pattern: "〜ても", 
      example: "雨が降っても、行きましょう。 (Meskipun hujan, mari kita pergi)", 
      meaning: "Menyatakan syarat yang berlawanan dengan hasil (Sekalipun, Walaupun...)." 
    },
    { 
      pattern: "〜場合は", 
      example: "間に合わない場合は、れんらくしてください。 (Pada saat tidak tepat waktu, hubungi aku)", 
      meaning: "Menyatakan kemungkinan suatu kejadian atau situasi darurat (Dalam kasus, Pada saat...)." 
    },
    { 
      pattern: "〜ようだ, 〜みたいだ", 
      example: "せきも出るし、かぜをひいたようです。 (Batuk juga, sepertinya masuk angin)", 
      meaning: "Menyatakan dugaan subjektif berdasarkan pengamatan atau kesan pembicara (Sepertinya...)." 
    },
    { 
      pattern: "〜そうだ (Kabar/Rumor)", 
      example: "田中さんは、中国語が話せるそうです。 (Tanaka katanya bisa bicara bahasa cina)", 
      meaning: "Menyampaikan informasi yang didengar dari pihak/sumber lain (Katanya, Kudengar...)." 
    },
    { 
      pattern: "〜そうだ (Rupa/Kesan)", 
      example: "このスープ、からそうですね。 (Sup ini sepertinya pedas)", 
      meaning: "Menyatakan kesan atau tebakan langsung secara visual (Kelihatannya, Sepertinya...)." 
    },
    { 
      pattern: "〜でしょう, 〜だろう", 
      example: "明日は、午後から雨が降るでしょう。 (Besok dari siang akan hujan, kan?)", 
      meaning: "Menyatakan dugaan, perkiraan, atau meminta persetujuan lawan bicara (...kan?, Mungkin...)." 
    },
    { 
      pattern: "〜と思う", 
      example: "それはかなりむずかしいと思います。 (Aku pikir itu cukup sulit)", 
      meaning: "Menyatakan opini, pendapat, atau pemikiran pembicara (Menurutku, Aku pikir...)." 
    },
    { 
      pattern: "〜はず", 
      example: "月よう日だから、開いているはずです。 (Karena senin, pasti buka)", 
      meaning: "Menyatakan keyakinan kuat berdasarkan alasan yang logis (Seharusnya, Pasti...)." 
    },
    { 
      pattern: "〜なさい", 
      example: "もう一度、よく聞きなさい。 (Sekali lagi, dengarkanlah baik-baik)", 
      meaning: "Kalimat perintah halus namun tegas (biasanya dari atasan ke bawahan atau orang tua ke anak)." 
    },
    { 
      pattern: "〜ようと思う", 
      example: "夏休みは、海に行こうと思っています。 (Liburan musim panas, aku berniat akan ke laut)", 
      meaning: "Menyatakan niat, maksud, atau rencana yang sedang dipikirkan (Aku bermaksud...)." 
    },
    { 
      pattern: "〜予定です, 〜つもりです", 
      example: "来年、日本に行くつもりです。 (Tahun depan berencana pergi ke Jepang)", 
      meaning: "Menyatakan rencana atau niat yang sudah diputuskan sebelumnya." 
    },
    { 
      pattern: "〜てみる", 
      example: "この服、着てみてもいいですか。 (Baju ini, bolehkah mencoba memakainya?)", 
      meaning: "Mencoba melakukan sesuatu untuk mengetahui hasilnya." 
    },
    { 
      pattern: "〜ておく", 
      example: "出かける前に、子どもに夜ごはんを作っておいた。 (Sebelum keluar, membuat makan malam untuk anak-anak sebagai persiapan)", 
      meaning: "Melakukan suatu tindakan sebagai persiapan untuk masa depan." 
    },
    { 
      pattern: "〜ように (Tujuan)", 
      example: "みんなに聞こえるように、話してください。 (Agar terdengar oleh semuanya, bicaralah)", 
      meaning: "Menyatakan tujuan atau harapan (Agar, Supaya), biasanya dipakai dengan kata kerja bentuk potensial/negatif." 
    },
    { 
      pattern: "〜ために", 
      example: "もっとはやく走るために、毎日練習しています。 (Agar larinya lebih cepat, setiap hari latihan)", 
      meaning: "Menyatakan tujuan yang kuat dengan kemauan sendiri (Untuk, Demi...)." 
    },
    { 
      pattern: "〜ようになる", 
      example: "英語が話せるようになりました。 (Sudah bisa bicara bahasa Inggris)", 
      meaning: "Menyatakan perubahan keadaan dari tidak bisa menjadi bisa, atau sebaliknya." 
    },
    { 
      pattern: "〜ことになる", 
      example: "父が入院することになりました。 (Diputuskan bahwa ayah masuk Rumah Sakit)", 
      meaning: "Menyatakan suatu keputusan atau aturan yang ditetapkan bukan oleh diri sendiri." 
    },
    { 
      pattern: "〜がする", 
      example: "にぎやかな声がしますね。 (Terdengar suara keramaian ya)", 
      meaning: "Dapat merasakan sesuatu melalui indra penciuman, pendengaran, atau perasaan (Terdengar, Tercium)." 
    },
    { 
      pattern: "〜ようにする", 
      example: "毎日運動して、何でも食べるようにしています。 (Setiap hari berusaha olahraga dan makan apa saja)", 
      meaning: "Menyatakan usaha atau kebiasaan yang sengaja dilakukan secara terus-menerus (Mengusahakan, Berusaha untuk...)." 
    },
    { 
      pattern: "〜ことにする", 
      example: "今年は国に帰らないことにしました。 (Tahun ini aku putuskan tidak akan pulang)", 
      meaning: "Menyatakan keputusan yang dibuat oleh diri sendiri secara sadar (Memutuskan untuk...)." 
    },
    { 
      pattern: "〜てくる", 
      example: "ちょっと、コンビニに行ってきます。 (Aku akan pergi ke minimarket sebentar lalu balik lagi)", 
      meaning: "Melakukan sesuatu (atau pergi) kemudian akan kembali lagi." 
    },
    { 
      pattern: "〜かどうか", 
      example: "おいしいかどうか、食べないとわからない。 (Enak atau tidak, jika tidak dicoba makan tidak akan tahu)", 
      meaning: "Menyisipkan keraguan atau pertanyaan ke dalam kalimat (Apakah ... atau tidak)." 
    },
    { 
      pattern: "〜さ", 
      example: "富士山の高さを知っていますか。 (Apakah kamu tahu ketinggian gunung Fuji?)", 
      meaning: "Mengubah kata sifat menjadi kata benda untuk menunjukkan ukuran atau tingkat (Ketinggian, Kepanasan, dll)." 
    },
    { 
      pattern: "尊敬語, 謙譲語 (Keigo)", 
      example: "部長、ランチはめしあがりましたか。 (Manajer, sudah makan siang?)", 
      meaning: "Bentuk bahasa sopan/hormat (Sonkeigo untuk meninggikan lawan bicara, Kenjougo untuk merendahkan diri)." 
    }
  ]
};
